export {
  STUDIO_PROJECT_FORMAT,
  STUDIO_PROJECT_SCHEMA_ID,
  STUDIO_PROJECT_VERSION,
  studioArtifactSchema,
  studioAnnotationRegionSchema,
  studioAnnotationTargetSchema,
  studioCompositionSchema,
  studioIdSchema,
  studioLayerSchema,
  studioNarrativeSchema,
  studioProjectSchema,
  studioReviewHistorySchema,
  studioReviewAnnotationSchema,
  studioReviewAuthorSchema,
  studioReviewRevisionSchema,
  studioSceneRenderSchema,
  studioSceneSchema,
  studioScriptHookSchema,
  studioSemanticEventSchema,
  studioSemanticTargetSchema,
  studioSemanticTrackSchema,
  type StudioArtifact,
  type StudioAnnotationRegion,
  type StudioAnnotationTarget,
  type StudioComposition,
  type StudioLayer,
  type StudioNarrative,
  type StudioProject,
  type StudioReviewHistory,
  type StudioReviewAnnotation,
  type StudioReviewAuthor,
  type StudioReviewRevision,
  type StudioScene,
  type StudioSceneRender,
  type StudioScriptHook,
  type StudioSemanticEvent,
  type StudioSemanticTarget,
  type StudioSemanticTrack,
} from "./project-schema.js";
export {
  STUDIO_VIDEO_REVIEW_DIMENSIONS,
  renderAndReviewStudioVideo,
  resumeStudioVideoReview,
  StudioVideoReviewError,
  studioVideoReviewFindingSchema,
  studioVideoReviewReportSchema,
  type RenderStudioReviewVideoOptions,
  type ResumeStudioVideoReviewOptions,
  type StudioReviewMedia,
  type StudioVideoReviewClarification,
  type StudioVideoReviewClarificationCheckpoint,
  type StudioVideoReviewComparison,
  type StudioVideoReviewDecision,
  type StudioVideoReviewDimension,
  type StudioVideoReviewFinding,
  type StudioVideoReviewReport,
  type StudioVideoReviewRequest,
  type StudioVideoReviewResult,
  type StudioVideoReviewSeverity,
} from "./video-review.js";
export {
  StudioProjectValidationError,
  importStoryboardConfig,
  loadStudioProject,
  parseStudioProjectJson,
  saveStudioProject,
  serializeStudioProject,
  studioProjectToStoryboardConfig,
  validateStudioProject,
  type ImportStoryboardOptions,
  type StudioProjectValidationIssue,
} from "./project.js";
export {
  StudioProjectCompileError,
  compileStudioProject,
  compileStudioProjectFile,
  type CompileStudioProjectOptions,
} from "./compile.js";
export {
  compileStudioInteractiveProject,
  inspectStudioHealingPage,
  StudioInteractiveSceneError,
  type CompileStudioInteractiveProjectOptions,
  type CompileStudioInteractiveProjectResult,
  type StudioHealingDomCandidate,
  type StudioHealingPageInspection,
  type StudioInteractiveSegment,
  type StudioSceneHookContext,
} from "./interactive-compile.js";
export {
  resumeStudioHealingLoop,
  runStudioHealingLoop,
  StudioHealingError,
  type RunStudioHealingLoopOptions,
  type StudioAiAcceptDecision,
  type StudioAiClarificationDecision,
  type StudioAiEditDecision,
  type StudioAiHealingDecision,
  type StudioAiReviewDecision,
  type StudioAiUnrecoverableDecision,
  type StudioAutomationChange,
  type StudioAutomationEvidence,
  type StudioAutomationPhase,
  type StudioClarificationAnswer,
  type StudioHealRequest,
  type StudioHealingClarificationCheckpoint,
  type StudioHealingLoopResult,
  type StudioJson,
  type StudioReplayFailure,
  type StudioReviewRequest,
} from "./healing.js";
export {
  StudioInteractionError,
  compileStudioSemanticTracks,
  resolveStudioSemanticTarget,
  runStudioSemanticPlan,
  runStudioSemanticStep,
  runStudioSemanticTracks,
  type CompileStudioSemanticTracksOptions,
  type RunStudioSemanticPlanOptions,
  type RunStudioSemanticStepOptions,
  type StudioScriptHookContext,
  type StudioSemanticPlan,
  type StudioSemanticStep,
} from "./interactions.js";
export {
  buildStudioCursorChoreography,
  inspectStudioCursorTargets,
  planStudioCursorChoreography,
  type PlanStudioCursorChoreographyOptions,
  type StudioCursorBox,
  type StudioCursorChoreography,
  type StudioCursorEventOverride,
  type StudioCursorInteractionTiming,
  type StudioCursorPoint,
  type StudioCursorTargetEvidence,
} from "./cursor-choreography.js";
export {
  StudioInteractionObservationError,
  observeStudioInteraction,
  observeStudioSemanticStep,
  type ObserveStudioInteractionOptions,
  type StudioElementChange,
  type StudioEvidenceClassification,
  type StudioInteractionEvidence,
  type StudioInteractionSignal,
  type StudioMutationEvidence,
  type StudioObservationPhase,
  type StudioObservedElement,
  type StudioObservedRect,
} from "./interaction-observer.js";
export {
  buildStudioProjectJsonSchema,
  studioProjectJsonSchemaText,
} from "./project-json-schema.js";
