// GENERATED FILE -- do not hand-edit. Regenerate with:
//   node tools/generate-script-extensions.mjs
//
// The codepoint ranges where Unicode's Script_Extensions (scx) property is
// NOT the trivial {Script} set -- i.e. every Common/Inherited codepoint that
// carries a restricted set of scripts it is conventionally used WITH (CJK
// punctuation, combining marks shared across scripts, etc). Every other
// codepoint's Script_Extensions equals {Script} by the Unicode Character
// Database's own design (UAX #24), so this table only needs to hold the
// exceptions -- confirmed empirically by the generator, not merely assumed.
//
// `primary` is the codepoint's Script property (always "Common" or
// "Inherited" here); `scripts` is its Script_Extensions member set, in the
// order Node's ICU/Unicode data reports Script_Extensions membership.
// Consumed by `src/render/script-segmentation.ts` to mirror Blink's
// `ScriptRunIterator` set-intersection walk (platform/fonts/script_run_iterator.cc,
// `ICUScriptData::GetScripts` + `ScriptRunIterator::MergeSets`, rev 7d859f27)
// instead of treating every Common/Inherited character as unconditionally
// neutral.
export interface ScriptExtensionsRange {
  readonly lo: number;
  readonly hi: number;
  readonly primary: "Common" | "Inherited";
  readonly scripts: readonly string[];
}

export const SCRIPT_EXTENSIONS_RANGES: readonly ScriptExtensionsRange[] = [
  { lo: 0xB7, hi: 0xB7, primary: "Common", scripts: ["Avestan", "Carian", "Coptic", "Duployan", "Elbasan", "Georgian", "Glagolitic", "Gothic", "Greek", "Gunjala_Gondi", "Han", "Latin", "Lydian", "Mahajani", "Old_Permic", "Shavian"] },
  { lo: 0x2BC, hi: 0x2BC, primary: "Common", scripts: ["Bengali", "Cyrillic", "Devanagari", "Latin", "Lisu", "Thai"] },
  { lo: 0x2C7, hi: 0x2C7, primary: "Common", scripts: ["Bopomofo", "Latin"] },
  { lo: 0x2C9, hi: 0x2CB, primary: "Common", scripts: ["Bopomofo", "Latin"] },
  { lo: 0x2CD, hi: 0x2CD, primary: "Common", scripts: ["Latin", "Lisu"] },
  { lo: 0x2D7, hi: 0x2D7, primary: "Common", scripts: ["Latin", "Thai"] },
  { lo: 0x2D9, hi: 0x2D9, primary: "Common", scripts: ["Bopomofo", "Latin"] },
  { lo: 0x300, hi: 0x300, primary: "Inherited", scripts: ["Cherokee", "Coptic", "Cyrillic", "Greek", "Latin", "Old_Permic", "Tai_Le"] },
  { lo: 0x301, hi: 0x301, primary: "Inherited", scripts: ["Cherokee", "Cyrillic", "Greek", "Latin", "Osage", "Tai_Le"] },
  { lo: 0x302, hi: 0x302, primary: "Inherited", scripts: ["Cherokee", "Cyrillic", "Latin", "Tifinagh"] },
  { lo: 0x303, hi: 0x303, primary: "Inherited", scripts: ["Glagolitic", "Latin", "Syriac", "Thai"] },
  { lo: 0x304, hi: 0x304, primary: "Inherited", scripts: ["Caucasian_Albanian", "Cherokee", "Coptic", "Cyrillic", "Gothic", "Greek", "Latin", "Osage", "Syriac", "Tifinagh"] },
  { lo: 0x305, hi: 0x305, primary: "Inherited", scripts: ["Coptic", "Elbasan", "Glagolitic", "Gothic", "Katakana", "Latin"] },
  { lo: 0x306, hi: 0x306, primary: "Inherited", scripts: ["Cyrillic", "Greek", "Latin", "Old_Permic"] },
  { lo: 0x307, hi: 0x307, primary: "Inherited", scripts: ["Coptic", "Duployan", "Hebrew", "Latin", "Old_Permic", "Syriac", "Tai_Le", "Tifinagh"] },
  { lo: 0x308, hi: 0x308, primary: "Inherited", scripts: ["Armenian", "Cyrillic", "Duployan", "Gothic", "Greek", "Hebrew", "Latin", "Old_Permic", "Syriac", "Tai_Le"] },
  { lo: 0x309, hi: 0x309, primary: "Inherited", scripts: ["Latin", "Tifinagh"] },
  { lo: 0x30A, hi: 0x30A, primary: "Inherited", scripts: ["Duployan", "Latin", "Syriac"] },
  { lo: 0x30B, hi: 0x30B, primary: "Inherited", scripts: ["Cherokee", "Cyrillic", "Latin", "Osage"] },
  { lo: 0x30C, hi: 0x30C, primary: "Inherited", scripts: ["Cherokee", "Latin", "Tai_Le"] },
  { lo: 0x30D, hi: 0x30D, primary: "Inherited", scripts: ["Latin"] },
  { lo: 0x30E, hi: 0x30E, primary: "Inherited", scripts: ["Ethiopic", "Latin"] },
  { lo: 0x310, hi: 0x310, primary: "Inherited", scripts: ["Latin"] },
  { lo: 0x311, hi: 0x311, primary: "Inherited", scripts: ["Cyrillic", "Latin"] },
  { lo: 0x313, hi: 0x313, primary: "Inherited", scripts: ["Greek", "Latin", "Old_Permic"] },
  { lo: 0x320, hi: 0x320, primary: "Inherited", scripts: ["Latin", "Syriac"] },
  { lo: 0x323, hi: 0x323, primary: "Inherited", scripts: ["Cherokee", "Duployan", "Katakana", "Latin", "Syriac"] },
  { lo: 0x324, hi: 0x324, primary: "Inherited", scripts: ["Cherokee", "Duployan", "Latin", "Syriac"] },
  { lo: 0x325, hi: 0x325, primary: "Inherited", scripts: ["Latin", "Syriac"] },
  { lo: 0x32D, hi: 0x32E, primary: "Inherited", scripts: ["Latin", "Syriac"] },
  { lo: 0x330, hi: 0x330, primary: "Inherited", scripts: ["Cherokee", "Latin", "Syriac"] },
  { lo: 0x331, hi: 0x331, primary: "Inherited", scripts: ["Caucasian_Albanian", "Cherokee", "Gothic", "Latin", "Thai"] },
  { lo: 0x342, hi: 0x342, primary: "Inherited", scripts: ["Greek"] },
  { lo: 0x345, hi: 0x345, primary: "Inherited", scripts: ["Greek"] },
  { lo: 0x358, hi: 0x358, primary: "Inherited", scripts: ["Latin", "Osage"] },
  { lo: 0x35E, hi: 0x35E, primary: "Inherited", scripts: ["Caucasian_Albanian", "Latin"] },
  { lo: 0x363, hi: 0x36F, primary: "Inherited", scripts: ["Latin"] },
  { lo: 0x374, hi: 0x374, primary: "Common", scripts: ["Coptic", "Greek"] },
  { lo: 0x485, hi: 0x486, primary: "Inherited", scripts: ["Cyrillic", "Latin"] },
  { lo: 0x60C, hi: 0x60C, primary: "Common", scripts: ["Arabic", "Hanifi_Rohingya", "Nko", "Syriac", "Thaana"] },
  { lo: 0x61B, hi: 0x61B, primary: "Common", scripts: ["Arabic", "Hanifi_Rohingya", "Nko", "Syriac", "Thaana"] },
  { lo: 0x61F, hi: 0x61F, primary: "Common", scripts: ["Adlam", "Arabic", "Hanifi_Rohingya", "Nko", "Syriac", "Thaana"] },
  { lo: 0x640, hi: 0x640, primary: "Common", scripts: ["Adlam", "Arabic", "Hanifi_Rohingya", "Mandaic", "Manichaean", "Psalter_Pahlavi", "Sogdian", "Syriac"] },
  { lo: 0x64B, hi: 0x655, primary: "Inherited", scripts: ["Arabic", "Syriac"] },
  { lo: 0x670, hi: 0x670, primary: "Inherited", scripts: ["Arabic", "Syriac"] },
  { lo: 0x951, hi: 0x951, primary: "Inherited", scripts: ["Bengali", "Devanagari", "Grantha", "Gujarati", "Gurmukhi", "Kannada", "Latin", "Malayalam", "Oriya", "Sharada", "Tamil", "Telugu", "Tirhuta"] },
  { lo: 0x952, hi: 0x952, primary: "Inherited", scripts: ["Bengali", "Devanagari", "Grantha", "Gujarati", "Gurmukhi", "Kannada", "Latin", "Malayalam", "Oriya", "Tamil", "Telugu", "Tirhuta"] },
  { lo: 0x964, hi: 0x964, primary: "Common", scripts: ["Bengali", "Devanagari", "Dogra", "Grantha", "Gujarati", "Gunjala_Gondi", "Gurmukhi", "Kannada", "Khudawadi", "Mahajani", "Malayalam", "Masaram_Gondi", "Nandinagari", "Oriya", "Sinhala", "Syloti_Nagri", "Takri", "Tamil", "Telugu", "Tirhuta"] },
  { lo: 0x965, hi: 0x965, primary: "Common", scripts: ["Bengali", "Devanagari", "Dogra", "Grantha", "Gujarati", "Gunjala_Gondi", "Gurmukhi", "Kannada", "Khudawadi", "Limbu", "Mahajani", "Malayalam", "Masaram_Gondi", "Nandinagari", "Oriya", "Sinhala", "Syloti_Nagri", "Takri", "Tamil", "Telugu", "Tirhuta"] },
  { lo: 0x10FB, hi: 0x10FB, primary: "Common", scripts: ["Georgian", "Glagolitic", "Latin"] },
  { lo: 0x16EB, hi: 0x16ED, primary: "Common", scripts: ["Runic"] },
  { lo: 0x1735, hi: 0x1736, primary: "Common", scripts: ["Buhid", "Hanunoo", "Tagalog", "Tagbanwa"] },
  { lo: 0x1802, hi: 0x1803, primary: "Common", scripts: ["Mongolian", "Phags_Pa"] },
  { lo: 0x1805, hi: 0x1805, primary: "Common", scripts: ["Mongolian", "Phags_Pa"] },
  { lo: 0x1CD0, hi: 0x1CD0, primary: "Inherited", scripts: ["Bengali", "Devanagari", "Grantha", "Kannada"] },
  { lo: 0x1CD1, hi: 0x1CD1, primary: "Inherited", scripts: ["Devanagari"] },
  { lo: 0x1CD2, hi: 0x1CD2, primary: "Inherited", scripts: ["Bengali", "Devanagari", "Grantha", "Kannada"] },
  { lo: 0x1CD3, hi: 0x1CD3, primary: "Common", scripts: ["Devanagari", "Grantha", "Kannada"] },
  { lo: 0x1CD4, hi: 0x1CD4, primary: "Inherited", scripts: ["Devanagari"] },
  { lo: 0x1CD5, hi: 0x1CD6, primary: "Inherited", scripts: ["Bengali", "Devanagari"] },
  { lo: 0x1CD7, hi: 0x1CD7, primary: "Inherited", scripts: ["Devanagari", "Sharada"] },
  { lo: 0x1CD8, hi: 0x1CD8, primary: "Inherited", scripts: ["Bengali", "Devanagari"] },
  { lo: 0x1CD9, hi: 0x1CD9, primary: "Inherited", scripts: ["Devanagari", "Sharada"] },
  { lo: 0x1CDA, hi: 0x1CDA, primary: "Inherited", scripts: ["Devanagari", "Kannada", "Malayalam", "Oriya", "Tamil", "Telugu"] },
  { lo: 0x1CDB, hi: 0x1CDB, primary: "Inherited", scripts: ["Devanagari"] },
  { lo: 0x1CDC, hi: 0x1CDD, primary: "Inherited", scripts: ["Devanagari", "Sharada"] },
  { lo: 0x1CDE, hi: 0x1CDF, primary: "Inherited", scripts: ["Devanagari"] },
  { lo: 0x1CE0, hi: 0x1CE0, primary: "Inherited", scripts: ["Devanagari", "Sharada"] },
  { lo: 0x1CE1, hi: 0x1CE1, primary: "Common", scripts: ["Bengali", "Devanagari"] },
  { lo: 0x1CE2, hi: 0x1CE8, primary: "Inherited", scripts: ["Devanagari"] },
  { lo: 0x1CE9, hi: 0x1CE9, primary: "Common", scripts: ["Devanagari", "Nandinagari"] },
  { lo: 0x1CEA, hi: 0x1CEA, primary: "Common", scripts: ["Bengali", "Devanagari"] },
  { lo: 0x1CEB, hi: 0x1CEC, primary: "Common", scripts: ["Devanagari"] },
  { lo: 0x1CED, hi: 0x1CED, primary: "Inherited", scripts: ["Bengali", "Devanagari"] },
  { lo: 0x1CEE, hi: 0x1CF1, primary: "Common", scripts: ["Devanagari"] },
  { lo: 0x1CF2, hi: 0x1CF2, primary: "Common", scripts: ["Bengali", "Devanagari", "Grantha", "Kannada", "Malayalam", "Nandinagari", "Oriya", "Sinhala", "Telugu", "Tirhuta"] },
  { lo: 0x1CF3, hi: 0x1CF3, primary: "Common", scripts: ["Devanagari", "Grantha"] },
  { lo: 0x1CF4, hi: 0x1CF4, primary: "Inherited", scripts: ["Devanagari", "Grantha", "Kannada"] },
  { lo: 0x1CF5, hi: 0x1CF6, primary: "Common", scripts: ["Bengali", "Devanagari"] },
  { lo: 0x1CF7, hi: 0x1CF7, primary: "Common", scripts: ["Bengali"] },
  { lo: 0x1CF8, hi: 0x1CF9, primary: "Inherited", scripts: ["Devanagari", "Grantha"] },
  { lo: 0x1CFA, hi: 0x1CFA, primary: "Common", scripts: ["Nandinagari"] },
  { lo: 0x1DC0, hi: 0x1DC1, primary: "Inherited", scripts: ["Greek"] },
  { lo: 0x1DF8, hi: 0x1DF8, primary: "Inherited", scripts: ["Cyrillic", "Latin", "Syriac"] },
  { lo: 0x202F, hi: 0x202F, primary: "Common", scripts: ["Latin", "Mongolian", "Phags_Pa"] },
  { lo: 0x204F, hi: 0x204F, primary: "Common", scripts: ["Adlam", "Arabic"] },
  { lo: 0x205A, hi: 0x205A, primary: "Common", scripts: ["Carian", "Georgian", "Glagolitic", "Lycian", "Old_Hungarian", "Old_Turkic"] },
  { lo: 0x205D, hi: 0x205D, primary: "Common", scripts: ["Carian", "Greek", "Meroitic_Hieroglyphs", "Old_Hungarian"] },
  { lo: 0x20F0, hi: 0x20F0, primary: "Inherited", scripts: ["Devanagari", "Grantha", "Latin"] },
  { lo: 0x2E17, hi: 0x2E17, primary: "Common", scripts: ["Coptic", "Latin"] },
  { lo: 0x2E30, hi: 0x2E30, primary: "Common", scripts: ["Avestan", "Old_Turkic"] },
  { lo: 0x2E31, hi: 0x2E31, primary: "Common", scripts: ["Avestan", "Carian", "Georgian", "Kaithi", "Lydian", "Old_Hungarian", "Samaritan"] },
  { lo: 0x2E3C, hi: 0x2E3C, primary: "Common", scripts: ["Duployan"] },
  { lo: 0x2E41, hi: 0x2E41, primary: "Common", scripts: ["Adlam", "Arabic", "Old_Hungarian"] },
  { lo: 0x2E43, hi: 0x2E43, primary: "Common", scripts: ["Cyrillic", "Glagolitic"] },
  { lo: 0x2FF0, hi: 0x2FFF, primary: "Common", scripts: ["Han", "Tangut"] },
  { lo: 0x3001, hi: 0x3001, primary: "Common", scripts: ["Bopomofo", "Han", "Hangul", "Hiragana", "Katakana", "Mongolian", "Yi"] },
  { lo: 0x3002, hi: 0x3002, primary: "Common", scripts: ["Bopomofo", "Han", "Hangul", "Hiragana", "Katakana", "Mongolian", "Phags_Pa", "Yi"] },
  { lo: 0x3003, hi: 0x3003, primary: "Common", scripts: ["Bopomofo", "Han", "Hangul", "Hiragana", "Katakana"] },
  { lo: 0x3006, hi: 0x3006, primary: "Common", scripts: ["Han"] },
  { lo: 0x3008, hi: 0x3009, primary: "Common", scripts: ["Bopomofo", "Han", "Hangul", "Hiragana", "Katakana", "Mongolian", "Tibetan", "Yi"] },
  { lo: 0x300A, hi: 0x300B, primary: "Common", scripts: ["Bopomofo", "Han", "Hangul", "Hiragana", "Katakana", "Lisu", "Mongolian", "Tibetan", "Yi"] },
  { lo: 0x300C, hi: 0x3011, primary: "Common", scripts: ["Bopomofo", "Han", "Hangul", "Hiragana", "Katakana", "Yi"] },
  { lo: 0x3013, hi: 0x3013, primary: "Common", scripts: ["Bopomofo", "Han", "Hangul", "Hiragana", "Katakana"] },
  { lo: 0x3014, hi: 0x301B, primary: "Common", scripts: ["Bopomofo", "Han", "Hangul", "Hiragana", "Katakana", "Yi"] },
  { lo: 0x301C, hi: 0x301F, primary: "Common", scripts: ["Bopomofo", "Han", "Hangul", "Hiragana", "Katakana"] },
  { lo: 0x302A, hi: 0x302D, primary: "Inherited", scripts: ["Bopomofo", "Han"] },
  { lo: 0x3030, hi: 0x3030, primary: "Common", scripts: ["Bopomofo", "Han", "Hangul", "Hiragana", "Katakana"] },
  { lo: 0x3031, hi: 0x3035, primary: "Common", scripts: ["Hiragana", "Katakana"] },
  { lo: 0x3037, hi: 0x3037, primary: "Common", scripts: ["Bopomofo", "Han", "Hangul", "Hiragana", "Katakana"] },
  { lo: 0x303C, hi: 0x303D, primary: "Common", scripts: ["Han", "Hiragana", "Katakana"] },
  { lo: 0x303E, hi: 0x303F, primary: "Common", scripts: ["Han"] },
  { lo: 0x3099, hi: 0x309A, primary: "Inherited", scripts: ["Hiragana", "Katakana"] },
  { lo: 0x309B, hi: 0x309C, primary: "Common", scripts: ["Hiragana", "Katakana"] },
  { lo: 0x30A0, hi: 0x30A0, primary: "Common", scripts: ["Hiragana", "Katakana"] },
  { lo: 0x30FB, hi: 0x30FB, primary: "Common", scripts: ["Bopomofo", "Han", "Hangul", "Hiragana", "Katakana", "Yi"] },
  { lo: 0x30FC, hi: 0x30FC, primary: "Common", scripts: ["Hiragana", "Katakana"] },
  { lo: 0x3190, hi: 0x319F, primary: "Common", scripts: ["Han"] },
  { lo: 0x31C0, hi: 0x31E5, primary: "Common", scripts: ["Han"] },
  { lo: 0x31EF, hi: 0x31EF, primary: "Common", scripts: ["Han", "Tangut"] },
  { lo: 0x3220, hi: 0x3247, primary: "Common", scripts: ["Han"] },
  { lo: 0x3280, hi: 0x32B0, primary: "Common", scripts: ["Han"] },
  { lo: 0x32C0, hi: 0x32CB, primary: "Common", scripts: ["Han"] },
  { lo: 0x32FF, hi: 0x32FF, primary: "Common", scripts: ["Han"] },
  { lo: 0x3358, hi: 0x3370, primary: "Common", scripts: ["Han"] },
  { lo: 0x337B, hi: 0x337F, primary: "Common", scripts: ["Han"] },
  { lo: 0x33E0, hi: 0x33FE, primary: "Common", scripts: ["Han"] },
  { lo: 0xA700, hi: 0xA707, primary: "Common", scripts: ["Han", "Latin"] },
  { lo: 0xA830, hi: 0xA832, primary: "Common", scripts: ["Devanagari", "Dogra", "Gujarati", "Gurmukhi", "Kaithi", "Kannada", "Khojki", "Khudawadi", "Mahajani", "Malayalam", "Modi", "Nandinagari", "Sharada", "Takri", "Tirhuta"] },
  { lo: 0xA833, hi: 0xA835, primary: "Common", scripts: ["Devanagari", "Dogra", "Gujarati", "Gurmukhi", "Kaithi", "Kannada", "Khojki", "Khudawadi", "Mahajani", "Modi", "Nandinagari", "Sharada", "Takri", "Tirhuta"] },
  { lo: 0xA836, hi: 0xA837, primary: "Common", scripts: ["Devanagari", "Dogra", "Gujarati", "Gurmukhi", "Kaithi", "Khojki", "Khudawadi", "Mahajani", "Modi", "Takri", "Tirhuta"] },
  { lo: 0xA838, hi: 0xA838, primary: "Common", scripts: ["Devanagari", "Dogra", "Gujarati", "Gurmukhi", "Kaithi", "Khojki", "Khudawadi", "Mahajani", "Modi", "Sharada", "Takri", "Tirhuta"] },
  { lo: 0xA839, hi: 0xA839, primary: "Common", scripts: ["Devanagari", "Dogra", "Gujarati", "Gurmukhi", "Kaithi", "Khojki", "Khudawadi", "Mahajani", "Modi", "Takri", "Tirhuta"] },
  { lo: 0xA92E, hi: 0xA92E, primary: "Common", scripts: ["Kayah_Li", "Latin", "Myanmar"] },
  { lo: 0xA9CF, hi: 0xA9CF, primary: "Common", scripts: ["Buginese", "Javanese"] },
  { lo: 0xFD3E, hi: 0xFD3F, primary: "Common", scripts: ["Arabic", "Nko"] },
  { lo: 0xFE45, hi: 0xFE46, primary: "Common", scripts: ["Bopomofo", "Han", "Hangul", "Hiragana", "Katakana"] },
  { lo: 0xFF61, hi: 0xFF65, primary: "Common", scripts: ["Bopomofo", "Han", "Hangul", "Hiragana", "Katakana", "Yi"] },
  { lo: 0xFF70, hi: 0xFF70, primary: "Common", scripts: ["Hiragana", "Katakana"] },
  { lo: 0xFF9E, hi: 0xFF9F, primary: "Common", scripts: ["Hiragana", "Katakana"] },
  { lo: 0x10100, hi: 0x10102, primary: "Common", scripts: ["Cypriot", "Linear_B"] },
  { lo: 0x10107, hi: 0x10133, primary: "Common", scripts: ["Cypriot", "Linear_A", "Linear_B"] },
  { lo: 0x10137, hi: 0x1013F, primary: "Common", scripts: ["Cypriot", "Linear_B"] },
  { lo: 0x102E0, hi: 0x102E0, primary: "Inherited", scripts: ["Arabic", "Coptic"] },
  { lo: 0x102E1, hi: 0x102FB, primary: "Common", scripts: ["Arabic", "Coptic"] },
  { lo: 0x1133B, hi: 0x1133B, primary: "Inherited", scripts: ["Grantha", "Tamil"] },
  { lo: 0x1BCA0, hi: 0x1BCA3, primary: "Common", scripts: ["Duployan"] },
  { lo: 0x1D360, hi: 0x1D371, primary: "Common", scripts: ["Han"] },
  { lo: 0x1F250, hi: 0x1F251, primary: "Common", scripts: ["Han"] },
];
