/** @jsxRuntime automatic */
/** @jsxImportSource kerfjs */

/**
 * HTML Test Suite Runner
 *
 * Runs domotion against every HTML file under `external/html-test/`.
 * For each file:
 *   1. Render HTML in Playwright (Chromium) -> PNG ("expected")
 *   2. Capture element tree -> SVG -> render SVG -> PNG ("actual")
 *   3. Diff and record result
 *
 * The fixture tree is the `brianwestphal/html-test` GitHub repo; it lives at
 * `external/html-test/` which is gitignored. Bootstrap with:
 *
 *   git clone https://github.com/brianwestphal/html-test.git external/html-test
 *
 * `HTML_TEST_DIR` can be overridden via the `HTML_TEST_DIR` env var if you
 * want to run against a different checkout / branch.
 *
 * Outputs:
 *   - tests/output/html-test/<name>-{expected,actual,diff}.png
 *   - tests/output/html-test/results.json  (for ticket generation)
 *   - tests/output/html-test/index.html    (visual overview)
 *
 * Usage: npx tsx tests/html-test-suite.tsx [--only 07-svg-shapes]
 */

import { chromium, type BrowserContext, type Page } from "@playwright/test";
import { mkdirSync, writeFileSync, readdirSync, statSync, existsSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { captureElementTreeWithWarnings, elementTreeToSvg, embedRemoteImages } from "../src/render/element-tree-to-svg.js";
import { discoverAndRegisterWebfonts } from "../src/capture/index.js";
import { rasterizeConicGradients } from "../src/render/conic-raster.js";
import { raw } from "kerfjs";
import { comparePngs, MIN_REGION_AREA, REGION_DILATE_PX, SIGNIFICANT_PIXEL_DIST, TILE_PX, type DiffVerdict } from "./compare-pngs.js";
import { lowerProcessPriority, resolveWorkerCount, runJobsInPool } from "./worker-pool.js";

const __dirname = dirname(fileURLToPath(import.meta.url));
const PACKAGE_ROOT = resolve(__dirname, "..");
const HTML_TEST_DIR = process.env.HTML_TEST_DIR != null && process.env.HTML_TEST_DIR !== ""
  ? resolve(process.env.HTML_TEST_DIR)
  : resolve(PACKAGE_ROOT, "external/html-test");
// Anchor output under this package's tests/ regardless of cwd so runs from
// inside  don't create a stray 
// subtree (the reason SK-991 was filed).
const OUTPUT_DIR = resolve(__dirname, "output/html-test");
const WIDTH = 1024;
const HEIGHT = 768;

/**
 * Per-fixture capture-height overrides for html-test files whose content
 * exceeds the 1024 × 768 default viewport (DM-781). The 768 px default
 * truncated the bottom of fixtures whose content stack was longer than the
 * viewport (e.g. `19-deep-color-mix` at 856 px, `niche-text-box-trim` at
 * 1680 px, `32-real-world-blog-post` at 4216 px); the captured PNG missed
 * sections that the test was actually checking. Generated by a one-time
 * Playwright probe (DM-781) over every `external/html-test/**.html`
 * fixture; the value is `ceil((max element-bottom + 8) / 8) * 8` — i.e.
 * the lowest visible element's bottom edge rounded up to the next 8 px
 * with an 8 px safety buffer.
 *
 * Width is fixed at 1024 px; only height needs overriding. Add a new entry
 * here whenever a fixture grows past the existing height — re-run the
 * probe (see `tools/probe-html-test-heights.mjs`) and copy the row in.
 */
const FIXTURE_HEIGHT_OVERRIDES: Record<string, number> = {
  "02-deep-bidi-isolate": 1272,
  "02-deep-line-breaking": 1064,
  "02-text-entities": 824,
  "02-text-symbols": 1752,
  "03-lists-style-image-position": 896,
  "03-lists-style-types": 1152,
  "03-lists-ul-ol": 1240,
  "04-deep-anonymous-boxes": 1056,
  "04-deep-border-conflict": 1024,
  "05-links-anchors": 1792,
  "06-deep-color-scheme-forms": 1448,
  "06-deep-field-sizing": 1248,
  "06-deep-input-baseline": 1072,
  "06-forms-input-types": 832,
  "06-forms-style-buttons": 1160,
  "06-forms-style-fieldset": 1632,
  "06-forms-style-focus": 1184,
  "06-forms-style-input-groups": 1144,
  "06-forms-style-layouts": 2056,
  "06-forms-style-progress-meter": 1128,
  "06-forms-style-range": 880,
  "06-forms-style-select": 1104,
  "06-forms-style-text-inputs": 1296,
  "06-forms-style-textarea": 2240,
  "07-deep-image-rendering": 2568,
  "07-deep-svg-markers-strokes": 2256,
  "07-deep-svg-presentation-attrs": 1792,
  "07-deep-svg-textpath-filters": 1712,
  "07-deep-svg-use-href": 824,
  "08-deep-details-accordion": 2304,
  "08-deep-popover-backdrop": 1240,
  "09-sectioning-landmarks": 784,
  "10-deep-attr-quoting": 1256,
  "10-deep-form-state-pseudos": 2432,
  "10-deep-has-complex": 1848,
  "10-deep-nth-of-type": 1960,
  "10-sel-combinators": 880,
  "10-sel-pseudo-logical": 896,
  "10-sel-pseudo-structural": 832,
  "10-sel-pseudo-ui-state": 912,
  "11-box-units": 960,
  "11-deep-box-sizing-mix": 1312,
  "11-deep-content-visibility": 3136,
  "11-deep-env-safe-area": 1104,
  "11-deep-intrinsic-sizing": 1568,
  "11-deep-margin-collapse-edges": 2336,
  "11-deep-math-functions": 2744,
  "11-deep-percent-resolution": 1248,
  "11-deep-viewport-units": 4112,
  "12-deep-display-contents": 920,
  "12-deep-display-syntax": 984,
  "13-deep-anchor-positioning": 1304,
  "13-deep-containing-block": 2648,
  "13-deep-cross-sc-z-index": 1456,
  "13-deep-fixed-in-transform": 2416,
  "13-deep-stacking-context-creators": 952,
  "13-deep-sticky-condensing-header": 1896,
  "13-deep-sticky-edges": 1376,
  "13-deep-z-index-flex-grid": 1032,
  "13-deep-z-index-negative": 1040,
  "13-pos-fixed": 1576,
  "13-pos-sticky": 1568,
  "14-deep-float-bfc": 1320,
  "14-deep-float-interactions": 1600,
  "15-deep-flex-aspect-ratio": 1336,
  "15-deep-flex-baseline": 1136,
  "15-deep-flex-min-auto": 952,
  "15-deep-flex-order-vs-z": 920,
  "15-flex-alignment": 2400,
  "15-flex-container": 1400,
  "15-flex-items": 864,
  "16-deep-grid-baseline": 1160,
  "16-deep-grid-implicit": 1880,
  "16-deep-grid-min-max-content": 1216,
  "16-deep-subgrid-lines": 960,
  "16-grid-alignment": 2088,
  "16-grid-auto-flow": 816,
  "16-grid-template": 824,
  "17-bg-color-image": 1904,
  "17-deep-bg-attachment-fixed": 1832,
  "17-deep-bg-clip-text": 1104,
  "17-deep-image-set": 1992,
  "17-deep-sprite-icons": 840,
  "18-deep-borders-mixed-sides": 1360,
  "18-deep-decoration-clone": 1648,
  "18-deep-radius-overflow": 1448,
  "18-deep-shadow-stacking": 1440,
  "19-deep-color-mix": 864,
  "19-deep-color-spaces": 1344,
  "19-deep-relative-color": 1032,
  "20-deep-decoration-detail": 1040,
  "20-deep-first-letter-line": 3680,
  "20-deep-font-feature-values": 2664,
  "20-deep-font-features": 1392,
  "20-deep-font-palette": 1888,
  "20-deep-hanging-punctuation": 2752,
  "20-deep-line-box-baselines": 1144,
  "20-deep-selection-highlight": 2032,
  "20-deep-tab-size": 2184,
  "20-deep-text-emphasis": 1576,
  "20-deep-text-stroke": 2976,
  "20-deep-text-underline-position": 2240,
  "20-deep-vertical-align": 1264,
  "20-deep-wavy-underline-descenders": 1400,
  "20-deep-writing-mode-mixed": 2096,
  "20-text-line-spacing": 1016,
  "20-text-wrapping": 1608,
  "20-writing-mode": 960,
  "21-deep-anisotropic-scale": 1248,
  "21-deep-transform-3d-preserve": 1224,
  "21-deep-transform-box": 1336,
  "21-deep-transform-origin": 1064,
  "21-transform-2d": 1096,
  "22-backdrop-filter": 840,
  "22-blend-modes": 1984,
  "22-deep-blend-groups": 2224,
  "22-deep-filter-paint-bounds": 2048,
  "22-deep-filter-stacking": 1512,
  "22-deep-isolation": 1392,
  "23-deep-clip-path-shapes": 1520,
  "23-deep-mask-composite": 1440,
  "23-deep-mask-fade-edges": 1752,
  "24-counters": 1128,
  "24-deep-counter-scope": 1360,
  "24-deep-counter-style": 3200,
  "24-deep-initial-letter": 1496,
  "24-deep-pseudo-shapes": 872,
  "25-deep-line-clamp": 1424,
  "25-deep-overflow-auto-positioned": 1352,
  "25-deep-overflow-clip": 1416,
  "25-deep-scrollbar-style": 1568,
  "25-overscroll": 2424,
  "25-scroll-snap": 1376,
  "26-deep-forced-colors": 1768,
  "27-deep-page-margin-boxes": 1520,
  "27-page": 1328,
  "28-deep-container-types": 1184,
  "28-deep-layer-import": 984,
  "28-deep-nesting-complex": 1344,
  "28-deep-scope": 1552,
  "29-deep-layer-priority": 1296,
  "29-deep-property-registration": 1184,
  "29-deep-where-is-specificity": 1040,
  "30-deep-resize-overflow": 1304,
  "30-resize": 792,
  "31-deep-inert-hidden": 1760,
  "31-global-attrs": 784,
  "32-real-world-blog-post": 4216,
  "32-real-world-mobile-app-frame": 984,
  "32-real-world-news-card": 1952,
  "32-real-world-pricing-table": 1392,
  "33-columns-basic": 1800,
  "33-deep-columns-break": 2024,
  "34-mathml-basic": 1784,
  "34-mathml-layout": 1632,
  "niche-align-content-block": 1992,
  "niche-anchor-position-try": 2480,
  "niche-command-invokers": 1296,
  "niche-cross-fade-images": 2472,
  "niche-css-function-rule": 1384,
  "niche-if-function": 1144,
  "niche-logical-clear-caption": 2304,
  "niche-mask-border": 1792,
  "niche-reading-flow": 1360,
  "niche-scroll-markers": 1760,
  "niche-scroll-state-queries": 1584,
  "niche-select-customizable": 808,
  "niche-shadow-dom-declarative": 1256,
  "niche-style-queries": 1808,
  "niche-svg-view-switch": 1944,
  "niche-text-box-trim": 1680,
  "niche-webkit-box-reflect": 1480,
  "niche-zoom-text-rendering": 2112,
};

/** Effective capture height for a fixture: the override when one exists,
 *  otherwise the 768 px default. */
function captureHeightFor(name: string): number {
  return FIXTURE_HEIGHT_OVERRIDES[name] ?? HEIGHT;
}
// Pass criterion, AA detector, and tile metrics are shared with the simpler
// runner via tests/compare-pngs.ts (DM-383). PASS_THRESHOLD_NON_AA_PIXELS,
// TILE_PX, and SIGNIFICANT_PIXEL_DIST are imported above.

/**
 * Tests intentionally deferred because the feature has no SVG equivalent or
 * requires a future refactor tracked by a dedicated ticket. Skipped tests
 * still render (so the artifacts exist for manual inspection) but don't count
 * against the pass/fail tally.
 */
const SKIP_TESTS: Record<string, string> = {
  "22-backdrop-filter": "SVG has no backdrop-filter equivalent in img-rendered SVG",
  "17-gradient-conic": "SVG 2 conic-gradient is not shipped in browsers",
  "17-gradient-repeating": "edge cases in repeating gradient stop spacing — low priority",
  "21-transform-3d": "CSS transforms deferred in SK-435 (layout-coord refactor needed)",
  "21-deep-transform-3d-preserve": "preserve-3d cube composition deferred in SK-435 (same territory as 21-transform-3d)",
  "27-page": "@page rules are print-media only, not relevant to static screen capture",
  // DM-725: `-webkit-box-reflect` paints a mirrored copy of the element box
  // below / above / left / right of itself. SVG has no direct equivalent —
  // would need a `<filter>` chain with feGaussianBlur + feImage or a
  // duplicated subtree with transform-flip + opacity gradient. Author note
  // says "skip for now".
  "niche-webkit-box-reflect": "DM-725: -webkit-box-reflect has no direct SVG equivalent; user-flagged for skip until we ship a duplicated-subtree + gradient-mask approach",
};

/**
 * Tests whose remaining diff vs Chrome is below the bar for a real fidelity
 * bug — typically text-antialiasing scatter, sub-pixel layout shifts, or
 * minor glyph-shape differences that the diff harness still picks up as
 * regions but a human reviewer has signed off as "looks correct". Entries
 * here count as PASS in the suite summary; the diff regions are still
 * recorded so a regression that breaks something NEW shows up in the
 * runner's region count. The value is a one-line justification — usually
 * the ticket id where the rendering was reviewed.
 */
const ACCEPTED_DIFFS: Record<string, string> = {
  // DM-774: paint-order test renders the seven nested layers in the correct
  // back-to-front order with correct colors / geometry; the residual diff is
  // text antialiasing + arrow-glyph substitution in the header / caption
  // paragraphs only. Reviewed visually; accepted as a stable baseline.
  "13-deep-stacking-paint-order": "DM-774: text antialiasing + arrow-glyph substitution only; geometry / paint order are correct",
  // DM-771: <select> single-choice / optgroup / size=N listbox / multiple
  // listbox all render with correct UA chrome (chevrons, item rows,
  // selected-row highlight). Residual diff is text-baseline antialiasing
  // scatter on the option rows + the closed-dropdown's chevron column.
  // Reviewed visually; accepted.
  "06-forms-select": "DM-771: <select> UA chrome correct; residual diff is text-baseline antialiasing scatter on option rows",
  // DM-772: overflow visible / hidden / scroll / auto / clip / x/y test —
  // all six boxes paint their content with the correct clip behavior.
  // Residual diff is text-baseline antialiasing scatter inside each box.
  // Reviewed visually; accepted.
  "25-overflow-values": "DM-772: clip behavior correct on all six boxes; residual diff is text-baseline antialiasing scatter",
  // DM-760: the original "text covered" issue (a gray rectangle obscuring
  // the middle of the Pass-criteria paragraph) is fixed by the DM-721
  // inline `box-decoration-break` work + DM-781 height override — the
  // paragraph + inline `<code>` chips now wrap and paint correctly.
  // Residual diff is text-baseline antialiasing on the paragraph + a
  // sub-pixel padding shift on the wrapping `<code>:user-invalid</code>`
  // span. Reviewed visually; accepted.
  "10-deep-form-state-pseudos": "DM-760: paragraph text + inline code chips render correctly; residual diff is antialiasing + sub-pixel wrap padding",
  // DM-757: SVG markers + curve with directional marker + stroke
  // dasharray / dashoffset / linecap / linejoin / miterlimit + paint-order
  // + vector-effect: non-scaling-stroke + nested <svg> viewBox all render
  // correctly to the eye. Residual diff is text-baseline antialiasing on
  // the Pass-criteria paragraph and inline `<code>` annotations only.
  // Reviewed visually; accepted.
  "07-deep-svg-markers-strokes": "DM-757: SVG marker / stroke / paint-order rendering correct; residual diff is text antialiasing on the caption paragraph",
  // DM-763: @container scroll-state(snapped / stuck) styling test —
  // sticky headers, snap-target highlights, and section colorations all
  // render correctly. Residual diff is text antialiasing on labels.
  "niche-scroll-state-queries": "DM-763: scroll-state container queries render correctly; residual diff is text antialiasing",
  // DM-748: Basic <table> with <caption> / <thead> / <tbody> / <tfoot> /
  // <th scope=…>. All grid lines, header bolding, and column-scoped header
  // emphasis paint correctly. Residual diff is text antialiasing inside
  // the table cells.
  "04-table-basic": "DM-748: <table> grid + caption + scope cells render correctly; residual diff is text antialiasing",
  // DM-744: `font-stretch` keyword + percentage scale. SF Pro's stretch
  // axis is driven correctly by the captured font-variation-settings; the
  // Hamburgefontsiv samples render at the requested stretches. Residual
  // diff is text antialiasing on the wide-axis variants.
  "20-font-stretch": "DM-744: font-stretch keyword / percentage map correctly; residual diff is text antialiasing on the variant samples",
  // DM-743: <meta> tags page — purely informational; no visible boxes /
  // shapes / images. Residual diff is text antialiasing on the descriptor
  // labels and their values.
  "01-structure-meta": "DM-743: meta-tag fixture renders correctly; residual diff is text antialiasing on the descriptor labels",
  // DM-742: `scrollbar-gutter: stable / both-edges` reserve-the-scrollbar
  // pattern. The reserved-gutter padding shows on the static layout
  // correctly (boxes with no overflow still reserve the scrollbar gutter,
  // boxes with overflow paint content inside the gutter). Residual diff
  // is text antialiasing inside the labeled boxes.
  "25-scrollbar-gutter": "DM-742: scrollbar-gutter reserve behavior correct; residual diff is text antialiasing inside the demo boxes",
  // DM-735: font-family generics test — serif / sans-serif / monospace /
  // cursive / fantasy / system-ui / ui-* / math / emoji / fangsong samples
  // resolve to the right system font on macOS. Fallback stack chain ("DoesNotExist",
  // Georgia, "Times New Roman", serif) demonstrates the chain falls through
  // to Georgia / serif as expected. Residual diff is text antialiasing.
  "20-font-family": "DM-735: font-family generics + fallback chain resolve correctly; residual diff is text antialiasing",
  // DM-734: line-height / letter-spacing / word-spacing keyword + length +
  // percentage + unitless. Sample paragraphs render with correct spacing
  // and the inline labels show the active value. Residual diff is text
  // antialiasing on the labels and demonstrators.
  "20-text-line-spacing": "DM-734: line-height / letter-spacing / word-spacing values render correctly; residual diff is text antialiasing",
  // DM-733: text-align (left / right / center / justify / start / end with
  // RTL + last-line keywords) aligns correctly to spec; minor sub-pixel
  // shifting on the justify variant + RTL start-as-right diff is below the
  // bar for a fidelity bug. User-signed-off as a baseline.
  "20-text-align": "DM-733: text-align variants align correctly; residual diff is sub-pixel shifting on justify + RTL labels",
};

interface TestResult {
  name: string;
  category: string;
  /** Count of pixels that differ between expected and actual AND are not
   *  classified as glyph anti-aliasing by the Yee detector. Diagnostic only;
   *  pass/fail uses `regionCount` (DM-715). */
  nonAaPixels: number;
  /** Same count expressed as a fraction of total image pixels (diagnostic). */
  nonAaPixelPct: number;
  diffPct: number;
  /** Image-wide fraction of pixels with >SIGNIFICANT_PIXEL_DIST distance. */
  sigPixelPct: number;
  /** Worst tile's average color distance as a %. */
  worstTilePct: number;
  /** Worst tile's fraction of pixels with >SIGNIFICANT_PIXEL_DIST distance. */
  worstTileSignificantPct: number;
  /** Rect of the worst tile (x, y, w, h) in the image. */
  worstTileRect?: { x: number; y: number; w: number; h: number };
  /** DM-715: connected-components region count on the dilated non-AA-diff
   *  mask. Pass requires 0. */
  regionCount: number;
  /** Total ORIGINAL non-AA-diff pixel area within surviving regions. */
  totalChangedArea: number;
  /** Max per-pixel normalized color distance % inside any surviving region. */
  maxRegionSeverity: number;
  /** Non-AA-diff pixels that fell into culled (sub-`MIN_REGION_AREA`)
   *  components; treated as scatter and ignored by pass/fail. */
  scatteredPixels: number;
  /** Pixels absorbed by the neighborhood-tolerant shift filter. */
  shiftedPixels: number;
  /** Connected components that passed the area floor but were culled for
   *  low high-severity fraction (typical of font-substitution / glyph-
   *  shape differences). They aren't real structural change. */
  shiftyRegionCount: number;
  shiftyRegionArea: number;
  /** Surviving area as a percentage of the image (more intuitive than the
   *  raw pixel count). */
  coveragePct: number;
  /** Qualitative tier — `clean`/`trivial`/`minor`/`moderate`/`major`. */
  verdict: DiffVerdict;
  /** Per-region breakdown (top 32 by area). */
  regions: Array<{ area: number; maxSeverity: number; highSevFraction: number; x: number; y: number; w: number; h: number }>;
  pass: boolean;
  skipped?: boolean;
  skipReason?: string;
  /** When set, the test is in `ACCEPTED_DIFFS` and counts as PASS despite
   *  non-zero `regionCount`. Carries the user's justification so the suite
   *  summary can surface it. */
  acceptedReason?: string;
  bodyBg: string;
  error?: string;
  warnings?: Array<{ selector: string; feature: string; detail: string }>;
}


function categoryOf(name: string): string {
  // Subdir-prefixed names (e.g. `niche-foo`) take their subdir as the
  // category. DM-714: added 19 fixtures under `external/html-test/niche/`
  // for experimental/Chrome-only CSS coverage; bucketed separately so the
  // category breakdown shows their pass rate next to the spec-bucket tests.
  // Subdirectory names must start with a letter so they don't collide with
  // the digit-prefixed spec buckets (`14-float-*` etc). Match only the
  // FIRST hyphen-bounded segment so `niche-text-box-trim` lands in the
  // `niche` bucket rather than `niche-text-box`.
  const sub = /^([a-z][a-z0-9]*)-/.exec(name);
  if (sub != null) return sub[1];
  const m = /^(\d+)-([a-z]+)/.exec(name);
  if (m != null) return `${m[1]}-${m[2]}`;
  return "other";
}

/** DM-714: walk HTML_TEST_DIR recursively. Returns relative paths with `/`
 *  separator (e.g. `niche/foo.html`). Subdirs whose name starts with `.` or
 *  `_` are skipped; everything else under the root is walked. */
function walkHtmlFiles(rootDir: string): string[] {
  const out: string[] = [];
  function visit(dir: string, prefix: string): void {
    let entries: string[];
    try { entries = readdirSync(dir); } catch { return; }
    for (const name of entries) {
      if (name.startsWith(".") || name.startsWith("_")) continue;
      const fullPath = resolve(dir, name);
      const relPath = prefix === "" ? name : `${prefix}/${name}`;
      let isDir = false;
      try { isDir = statSync(fullPath).isDirectory(); } catch { continue; }
      if (isDir) {
        visit(fullPath, relPath);
      } else if (name.endsWith(".html") && relPath !== "index.html") {
        out.push(relPath);
      }
    }
  }
  visit(rootDir, "");
  return out.sort();
}

interface HtmlTestWorker {
  context: BrowserContext;
  page: Page;
  compareContext: BrowserContext;
  comparePage: Page;
}

async function runOneHtmlTest(file: string, w: HtmlTestWorker): Promise<TestResult> {
  // DM-714: `file` is a relative path under HTML_TEST_DIR (e.g. `01-foo.html`
  // or `niche/foo.html`). Flatten subdir separators to `-` so the output
  // PNGs and the visible "name" in results live at the top of OUTPUT_DIR;
  // `srcPath` still resolves correctly through the un-flattened path.
  const name = file.replace(/\.html$/, "").replace(/\//g, "-");
  const srcPath = resolve(HTML_TEST_DIR, file);
  const expectedPath = resolve(OUTPUT_DIR, `${name}-expected.png`);
  const actualPath = resolve(OUTPUT_DIR, `${name}-actual.png`);
  const diffPath = resolve(OUTPUT_DIR, `${name}-diff.png`);
  const svgPath = resolve(OUTPUT_DIR, `${name}.svg`);

  let nonAaPixels = Number.MAX_SAFE_INTEGER;
  let nonAaPixelPct = 100;
  let diffPct = 100;
  let sigPixelPct = 100;
  let worstTilePct = 100;
  let worstTileSignificantPct = 100;
  let worstTileRect: { x: number; y: number; w: number; h: number } | undefined;
  let regionCount = Number.MAX_SAFE_INTEGER;
  let totalChangedArea = 0;
  let maxRegionSeverity = 0;
  let scatteredPixels = 0;
  let shiftedPixels = 0;
  let shiftyRegionCount = 0;
  let shiftyRegionArea = 0;
  let coveragePct = 100;
  let verdict: DiffVerdict = "major";
  let regions: Array<{ area: number; maxSeverity: number; highSevFraction: number; x: number; y: number; w: number; h: number }> = [];
  let bodyBg = "#ffffff";
  let err: string | undefined;
  let capWarnings: Array<{ selector: string; feature: string; detail: string }> = [];

  // DM-781: per-fixture capture height. Fixtures whose content extends past
  // the 768 px default get the override; everything else uses the default.
  // Resize the viewport BEFORE the navigation so the initial layout (and
  // anything keyed off media queries / vh units / IntersectionObserver) sees
  // the height the test was designed for.
  const fixtureHeight = captureHeightFor(name);

  try {
    if (fixtureHeight !== HEIGHT) {
      await w.page.setViewportSize({ width: WIDTH, height: fixtureHeight });
    } else {
      // Reset back to default in case the previous fixture in this worker
      // bumped the viewport — keeps screenshot dimensions consistent across
      // jobs run on the same page.
      const vp = w.page.viewportSize();
      if (vp != null && vp.height !== HEIGHT) {
        await w.page.setViewportSize({ width: WIDTH, height: HEIGHT });
      }
    }
    await w.page.goto(`file://${srcPath}`);
    await w.page.waitForTimeout(150);

    bodyBg = await w.page.evaluate(() => {
      const cs = getComputedStyle(document.body);
      const bg = cs.backgroundColor;
      if (bg === "rgba(0, 0, 0, 0)" || bg === "transparent") return "#ffffff";
      return bg;
    });

    await w.page.screenshot({ path: expectedPath, clip: { x: 0, y: 0, width: WIDTH, height: fixtureHeight } });

    // Pick up any @font-face rules — covers both url(...) downloads and
    // local(...) aliases (DM-303). Without this, fixtures using
    // `font-family: "MyFamily"` declared via @font-face render in the
    // chain-fallback face (`serif` → Times) instead of the local() target.
    try { await discoverAndRegisterWebfonts(w.page); } catch { /* best-effort */ }

    // captureElementTreeWithWarnings returns warnings inline so concurrent
    // workers don't race on the lastCaptureWarnings module global (DM-456).
    const cap = await captureElementTreeWithWarnings(w.page, "body", { x: 0, y: 0, width: WIDTH, height: fixtureHeight });
    capWarnings = cap.warnings;
    // DM-512: demos always emit self-contained SVGs.
    // DM-527: thread the per-suite warnings array so concurrent workers
    // don't race on the lastCaptureWarnings module global.
    await embedRemoteImages(cap.tree, { warnings: capWarnings });
    // DM-549: rasterize conic-gradient layers (no-op when tree has none).
    await rasterizeConicGradients(cap.tree);
    const svgContent = elementTreeToSvg(cap.tree, WIDTH, fixtureHeight);
    const svgDoc = `<?xml version="1.0" encoding="UTF-8"?><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${WIDTH} ${fixtureHeight}" width="${WIDTH}" height="${fixtureHeight}"><rect width="${WIDTH}" height="${fixtureHeight}" fill="${bodyBg}" />${svgContent}</svg>`;
    writeFileSync(svgPath, svgDoc);

    // Load the SVG directly as the top-level document. Wrapping it in <img>
    // blocks external resource loads inside the SVG for security, which
    // masked rendering fidelity for any test using background:url() or <img>.
    // Loading the SVG as a document lets those external file:// refs resolve.
    await w.page.goto(`file://${svgPath}`);
    await w.page.waitForTimeout(200);
    await w.page.screenshot({ path: actualPath, clip: { x: 0, y: 0, width: WIDTH, height: fixtureHeight } });

    const cmp = await comparePngs(w.comparePage, expectedPath, actualPath, diffPath, TILE_PX, SIGNIFICANT_PIXEL_DIST);
    nonAaPixels = cmp.nonAaPixels;
    nonAaPixelPct = cmp.nonAaPixelPct;
    diffPct = cmp.diffPct;
    sigPixelPct = cmp.sigPixelPct;
    worstTilePct = cmp.worstTilePct;
    worstTileSignificantPct = cmp.worstTileSignificantPct;
    worstTileRect = cmp.worstTileRect;
    regionCount = cmp.regionCount;
    totalChangedArea = cmp.totalChangedArea;
    maxRegionSeverity = cmp.maxRegionSeverity;
    scatteredPixels = cmp.scatteredPixels;
    shiftedPixels = cmp.shiftedPixels;
    shiftyRegionCount = cmp.shiftyRegionCount;
    shiftyRegionArea = cmp.shiftyRegionArea;
    coveragePct = cmp.coveragePct;
    verdict = cmp.verdict;
    regions = cmp.regions;
  } catch (e) {
    err = e instanceof Error ? e.message : String(e);
  }

  const skipReason = SKIP_TESTS[name];
  const skipped = skipReason != null;
  const acceptedReason = ACCEPTED_DIFFS[name];
  const accepted = !skipped && err == null && acceptedReason != null;
  const pass = !skipped && err == null && (regionCount === 0 || accepted);
  return {
    name,
    category: categoryOf(name),
    nonAaPixels,
    nonAaPixelPct,
    diffPct,
    sigPixelPct,
    worstTilePct,
    worstTileSignificantPct,
    worstTileRect,
    regionCount,
    totalChangedArea,
    maxRegionSeverity,
    scatteredPixels,
    shiftedPixels,
    shiftyRegionCount,
    shiftyRegionArea,
    coveragePct,
    verdict,
    regions,
    pass,
    skipped,
    skipReason,
    acceptedReason: accepted ? acceptedReason : undefined,
    bodyBg,
    error: err,
    warnings: capWarnings.length > 0 ? capWarnings : undefined,
  };
}

async function main(): Promise<void> {
  const args = process.argv.slice(2);
  const onlyArg = args.includes("--only") ? args[args.indexOf("--only") + 1] : null;

  mkdirSync(OUTPUT_DIR, { recursive: true });

  if (!existsSync(HTML_TEST_DIR)) {
    console.error(`html-test fixtures missing at ${HTML_TEST_DIR}`);
    console.error(`Clone the fixture repo with:`);
    console.error(`  git clone https://github.com/brianwestphal/html-test.git external/html-test`);
    console.error(`(or set HTML_TEST_DIR to point at an existing checkout)`);
    process.exitCode = 1;
    return;
  }
  // DM-714: walk recursively so subdir-grouped fixtures (`niche/*.html`,
  // future additions) are picked up automatically.
  const files = walkHtmlFiles(HTML_TEST_DIR);

  // --only is matched against the flattened name (with `/` → `-`) so callers
  // can pass either form: `--only niche-foo` and `--only niche/foo` both work.
  const onlyNorm = onlyArg != null ? onlyArg.replace(/\//g, "-") : null;
  const testFiles = onlyNorm != null
    ? files.filter((f) => f.replace(/\//g, "-").startsWith(onlyNorm))
    : files;
  if (testFiles.length === 0) {
    console.log(`No test files matched (onlyArg=${onlyArg ?? "(none)"}).`);
    return;
  }

  // DM-459: yield CPU to interactive work — Chromium subprocesses inherit.
  lowerProcessPriority();
  const workerCount = resolveWorkerCount();
  const overrideCount = testFiles.filter((f) => {
    const name = f.replace(/\.html$/, "").replace(/\//g, "-");
    return FIXTURE_HEIGHT_OVERRIDES[name] != null;
  }).length;
  const overrideNote = overrideCount > 0
    ? ` (${overrideCount} fixture${overrideCount === 1 ? "" : "s"} use a taller capture height per DM-781)`
    : "";
  console.log(`Running ${testFiles.length} html-test files (viewport ${WIDTH}x${HEIGHT}${overrideNote}) with ${workerCount} workers...\n`);

  const browser = await chromium.launch();

  const results = await runJobsInPool<string, HtmlTestWorker, TestResult>({
    jobs: testFiles,
    workers: workerCount,
    setup: async () => {
      const context = await browser.newContext({ viewport: { width: WIDTH, height: HEIGHT } });
      const page = await context.newPage();
      // DM-479: 90 s instead of Playwright's 30 s default.
      page.setDefaultTimeout(90_000);
      page.setDefaultNavigationTimeout(90_000);
      const compareContext = await browser.newContext({ viewport: { width: WIDTH * 2, height: HEIGHT } });
      const comparePage = await compareContext.newPage();
      comparePage.setDefaultTimeout(90_000);
      comparePage.setDefaultNavigationTimeout(90_000);
      await comparePage.goto("about:blank");
      return { context, page, compareContext, comparePage };
    },
    teardown: async (w) => {
      await w.context.close();
      await w.compareContext.close();
    },
    runJob: async (file, w) => runOneHtmlTest(file, w),
    onResult: (result) => {
      const { name, pass, skipped, acceptedReason, error: err, warnings, verdict, regionCount, coveragePct } = result;
      const status = skipped
        ? "- SKIP"
        : acceptedReason != null
        ? "~ ACCEPT"
        : pass ? "✓ PASS" : "✗ FAIL";
      const warnBadge = warnings != null ? ` (${warnings.length}w)` : "";
      // Headline: verdict tier + region count + coverage %. Three things,
      // each immediately interpretable: "minor" tells you it's small,
      // "3 regions" tells you how many spots to look at, "0.28% of image"
      // tells you how much area is wrong.
      const headline = (skipped ?? false)
        ? ""
        : ` ${verdict} · ${regionCount} region${regionCount === 1 ? "" : "s"} · ${coveragePct.toFixed(2)}% of image`;
      console.log(`  ${status}  ${name.padEnd(40)}${headline}${warnBadge}${err != null ? `  ERR: ${err}` : ""}`);
    },
  });

  await browser.close();

  writeFileSync(resolve(OUTPUT_DIR, "results.json"), JSON.stringify(results, null, 2));

  const indexHtml = buildIndexHtml(results);
  writeFileSync(resolve(OUTPUT_DIR, "index.html"), indexHtml);

  const passed = results.filter((r) => r.pass).length;
  const skipped = results.filter((r) => r.skipped).length;
  const failed = results.length - passed - skipped;
  console.log(`\n${passed} passed, ${failed} failed, ${skipped} skipped out of ${results.length}`);
  console.log(`\nArtifacts: ${OUTPUT_DIR}`);
  console.log(`Visual index: file://${resolve(OUTPUT_DIR, "index.html")}`);

  const byCategory = new Map<string, { total: number; failed: number; avgDiff: number }>();
  for (const r of results) {
    const entry = byCategory.get(r.category) ?? { total: 0, failed: 0, avgDiff: 0 };
    entry.total++;
    entry.avgDiff += r.diffPct;
    if (!r.pass) entry.failed++;
    byCategory.set(r.category, entry);
  }

  console.log(`\nBy category (category: fails/total avg%):`);
  const catKeys = Array.from(byCategory.keys()).sort();
  for (const key of catKeys) {
    const v = byCategory.get(key)!;
    console.log(`  ${key.padEnd(24)} ${v.failed}/${v.total}  avg ${(v.avgDiff / v.total).toFixed(1)}%`);
  }

  if (failed > 0) process.exitCode = 1;
}

const INDEX_CSS = `
body{font:13px -apple-system,sans-serif;margin:16px;background:#f6f8fa}
table{width:100%;border-collapse:collapse}
th,td{text-align:left;padding:6px 8px;border-bottom:1px solid #e1e4e8;vertical-align:top}
tr.pass{background:#f0fff4}
tr.fail{background:#fff5f5}
tr.skip{background:#f6f8fa;opacity:0.7}
.name{font-family:monospace;font-size:12px}
.status{font-weight:600}
.tile{color:#6e7681;font-size:11px}
.imgs img{width:180px;height:135px;object-fit:contain;background:#fff;border:1px solid #d0d7de;margin-right:4px}
h1{margin:0 0 12px}
.err{color:#cf222e;font-family:monospace;font-size:11px}
.skip-note{color:#8b949e;font-size:11px;font-style:italic;margin-top:4px}
.warn-list{font-size:11px;color:#6e7681;margin:4px 0 0 14px;padding:0}
.warn-list li{margin:1px 0}
.legend{font-size:12px;color:#6e7681;margin-bottom:8px}
`;

function ResultRow({ r }: { r: TestResult }) {
  const status = r.skipped ? "SKIP" : r.pass ? "PASS" : "FAIL";
  const cls = r.skipped ? "skip" : r.pass ? "pass" : "fail";
  return (
    <tr className={cls}>
      <td className="name">{r.name}</td>
      <td className="status">{status}</td>
      <td className="diff">
        <div><b>{`${r.verdict} · ${r.regionCount} region${r.regionCount === 1 ? "" : "s"}`}</b></div>
        <div className="tile">{`${r.coveragePct.toFixed(2)}% of image`}</div>
        <div className="tile">{`shifty ${r.shiftyRegionCount} · shifted ${r.shiftedPixels} · scatter ${r.scatteredPixels}`}</div>
        <div className="tile">{`raw avg ${r.diffPct.toFixed(2)}% · non-AA ${r.nonAaPixels} px`}</div>
      </td>
      <td className="imgs">
        <a href={`${r.name}-expected.png`}><img src={`${r.name}-expected.png`} /></a>
        <a href={`${r.name}-actual.png`}><img src={`${r.name}-actual.png`} /></a>
        <a href={`${r.name}-diff.png`}><img src={`${r.name}-diff.png`} /></a>
      </td>
      <td className="err-cell">
        {r.error != null ? <div className="err">{r.error}</div> : null}
        {r.skipReason != null ? <div className="skip-note">{`skipped: ${r.skipReason}`}</div> : null}
        {(r.warnings ?? []).length > 0 ? (
          <ul className="warn-list">
            {(r.warnings ?? []).map((w) => (
              <li><b>{w.feature}</b>{` · ${w.selector} — ${w.detail}`}</li>
            ))}
          </ul>
        ) : null}
      </td>
    </tr>
  );
}

function MetricsLegend() {
  return (
    <p className="legend">
      {`Verdicts: clean (no regions) · trivial (≤2 regions, <0.05% coverage) · minor (≤5 regions, <0.5%) · moderate (≤15 regions, <2%) · major (everything past that). Pipeline (DM-715): neighborhood-tolerant shift filter → Yee AA filter → 3-px dilation + flood-fill → area + high-severity gates. "shifty" = font-substitution regions culled by the high-sev gate; "scatter" = sub-area components; "shifted" = pixels absorbed by neighborhood matching. Big shifty/shifted with low region count means the filters did real work. Magenta outlines on diff.png mark surviving regions; yellow box marks the worst tile.`}
    </p>
  );
}

function IndexLayout({ results }: { results: TestResult[] }) {
  const passCount = results.filter((r) => r.pass).length;
  const failCount = results.filter((r) => !r.pass && !r.skipped).length;
  const skipCount = results.filter((r) => r.skipped).length;
  return (
    <html>
      <head>
        <meta charset="utf-8" />
        <title>domotion html-test results</title>
        <style>{raw(INDEX_CSS)}</style>
      </head>
      <body>
        <h1>{`domotion vs html-test (${results.length} files; ${passCount} pass · ${failCount} fail · ${skipCount} skip)`}</h1>
        <MetricsLegend />
        <table>
          <thead><tr><th>File</th><th>Status</th><th>Diff</th><th>Expected · Actual · Diff</th><th>Notes</th></tr></thead>
          <tbody>
            {results.map((r) => <ResultRow r={r} />)}
          </tbody>
        </table>
      </body>
    </html>
  );
}

function buildIndexHtml(results: TestResult[]): string {
  return `<!DOCTYPE html>${(<IndexLayout results={results} />).toString()}`;
}

void main();
