// Root adapter over the text-engine workspace's public entry points (packages/text-engine/README.md).
export {
  clearEmbeddedFonts,
  clearGlyphDefs,
  clearWebfonts,
  type EmbeddedFontBuildDiagnostic,
  type FontVariantEmojiOverride,
  getEmbeddedFontFaceCss,
  getFontInstance,
  getGlyphDefs,
  getGlyphDefsSince,
  getRenderTextMode,
  glyphDefCount,
  isRenderTextMode,
  registerLocalFontAlias,
  registerWebfont,
  RENDER_TEXT_MODES,
  type RenderTextMode,
  resolveFontKey,
  restoreGeneration,
  type SessionGenericFamilyOverrides,
  setRenderTextMode,
  snapshotGeneration,
  truncateGlyphDefs,
  withRenderTextMode,
} from "@domotion/text-engine/font-resolution";
