// Root adapter over the text-engine workspace's public entry points (packages/text-engine/README.md).
export {
  beginCharacterFallbackDocument,
  blinkGenericFamilyFromDeclaredStack,
  clearEmbeddedFonts,
  clearFontResolutionCaches,
  clearGlyphDefs,
  clearWebfonts,
  createFontFallbackSemanticContext,
  createFontRendererSession,
  declaredFamilyHeadIdentity,
  type EmbeddedFontBuildDiagnostic,
  endCharacterFallbackDocument,
  fallbackFontChain,
  fontHasSupportedColorTable,
  type FontInstance,
  type FontRun,
  type FontVariantEmojiOverride,
  getEmbeddedFontBuildDiagnostics,
  getEmbeddedFontFaceCss,
  getFontInstance,
  getFontSourceInfo,
  getGlyphDefs,
  getGlyphDefsSince,
  getRenderTextMode,
  getSessionGenericFamilyOverrides,
  glyphDefCount,
  glyphIdForCp,
  invalidateFontEnvironmentCaches,
  isRenderTextMode,
  ITALIC_SLNT,
  opticalCutOpszFor,
  platformFontKeys,
  registerLocalFontAlias,
  registerWebfont,
  RENDER_TEXT_MODES,
  type RenderTextMode,
  resetGeneration,
  resolveFont,
  resolveFontForCodepoint,
  resolveFontKey,
  resolveFontKeyChain,
  resolveFontSpec,
  restoreGeneration,
  selectCharacterFallbackRendererScope,
  type SessionGenericFamilyOverrides,
  setRenderTextMode,
  setSessionGenericFamilyOverrides,
  shapingFaceFor,
  skiaLastResortFamilyQuestionOrder,
  skiaLastResortInitialFamily,
  snapshotGeneration,
  stackPrimaryIsSystemUi,
  stretchPercent,
  truncateGlyphDefs,
  win32FallbackChain,
  withFontRendererSession,
  withRenderTextMode,
  withSessionGenericFamilyOverrides,
  withSystemFallbackResolution,
} from "@domotion/text-engine/font-resolution";
