// GENERATED table: Unicode script property-value name -> ISO 15924 script tag.
//
// Derived mechanically from HarfBuzz's own script enum
// (external/harfbuzz/src/hb-script-list.h, rev 4de187d 2026-07-31): each
// HB_SCRIPT_* constant IS the ISO 15924 tag hb_buffer_set_script accepts, and
// the enum name lowercased into Title_Case matches the UCD script name
// `unicode-properties` reports for all but two entries, patched by hand:
//   - Canadian_Aboriginal (UCD name; the hb enum spells it CANADIAN_SYLLABICS) -> Cans
//   - SignWriting (UCD name; the hb enum's mechanical casing gives Signwriting) -> Sgnw
// Verified exhaustively: every script name `unicode-properties` getScript()
// returns over U+0000..U+10FFFF resolves through this map.
//
// Blink never lets HarfBuzz guess the script: ShapeSegment passes the
// RunSegmenter segment's script into ShapeRange -> hb_buffer_set_script
// (platform/fonts/shaping/harfbuzz_shaper.cc:1120-1123 -> :339-341, rev
// 7d859f27). This table is what lets the cluster-granularity splitter do the
// same with the names our segmenter (script-segmentation.ts) produces.
export const SCRIPT_NAME_TO_ISO15924: Record<string, string> = {
  "Adlam": "Adlm",
  "Ahom": "Ahom",
  "Anatolian_Hieroglyphs": "Hluw",
  "Arabic": "Arab",
  "Armenian": "Armn",
  "Avestan": "Avst",
  "Balinese": "Bali",
  "Bamum": "Bamu",
  "Bassa_Vah": "Bass",
  "Batak": "Batk",
  "Bengali": "Beng",
  "Beria_Erfe": "Berf",
  "Bhaiksuki": "Bhks",
  "Bopomofo": "Bopo",
  "Brahmi": "Brah",
  "Braille": "Brai",
  "Buginese": "Bugi",
  "Buhid": "Buhd",
  "Canadian_Aboriginal": "Cans",
  "Canadian_Syllabics": "Cans",
  "Carian": "Cari",
  "Caucasian_Albanian": "Aghb",
  "Chakma": "Cakm",
  "Cham": "Cham",
  "Cherokee": "Cher",
  "Chorasmian": "Chrs",
  "Common": "Zyyy",
  "Coptic": "Copt",
  "Cuneiform": "Xsux",
  "Cypriot": "Cprt",
  "Cypro_Minoan": "Cpmn",
  "Cyrillic": "Cyrl",
  "Deseret": "Dsrt",
  "Devanagari": "Deva",
  "Dives_Akuru": "Diak",
  "Dogra": "Dogr",
  "Duployan": "Dupl",
  "Egyptian_Hieroglyphs": "Egyp",
  "Elbasan": "Elba",
  "Elymaic": "Elym",
  "Ethiopic": "Ethi",
  "Garay": "Gara",
  "Georgian": "Geor",
  "Glagolitic": "Glag",
  "Gothic": "Goth",
  "Grantha": "Gran",
  "Greek": "Grek",
  "Gujarati": "Gujr",
  "Gunjala_Gondi": "Gong",
  "Gurmukhi": "Guru",
  "Gurung_Khema": "Gukh",
  "Han": "Hani",
  "Hangul": "Hang",
  "Hanifi_Rohingya": "Rohg",
  "Hanunoo": "Hano",
  "Hatran": "Hatr",
  "Hebrew": "Hebr",
  "Hiragana": "Hira",
  "Imperial_Aramaic": "Armi",
  "Inherited": "Zinh",
  "Inscriptional_Pahlavi": "Phli",
  "Inscriptional_Parthian": "Prti",
  "Javanese": "Java",
  "Kaithi": "Kthi",
  "Kannada": "Knda",
  "Katakana": "Kana",
  "Kawi": "Kawi",
  "Kayah_Li": "Kali",
  "Kharoshthi": "Khar",
  "Khitan_Small_Script": "Kits",
  "Khmer": "Khmr",
  "Khojki": "Khoj",
  "Khudawadi": "Sind",
  "Kirat_Rai": "Krai",
  "Lao": "Laoo",
  "Latin": "Latn",
  "Lepcha": "Lepc",
  "Limbu": "Limb",
  "Linear_A": "Lina",
  "Linear_B": "Linb",
  "Lisu": "Lisu",
  "Lycian": "Lyci",
  "Lydian": "Lydi",
  "Mahajani": "Mahj",
  "Makasar": "Maka",
  "Malayalam": "Mlym",
  "Mandaic": "Mand",
  "Manichaean": "Mani",
  "Marchen": "Marc",
  "Masaram_Gondi": "Gonm",
  "Math": "Zmth",
  "Medefaidrin": "Medf",
  "Meetei_Mayek": "Mtei",
  "Mende_Kikakui": "Mend",
  "Meroitic_Cursive": "Merc",
  "Meroitic_Hieroglyphs": "Mero",
  "Miao": "Plrd",
  "Modi": "Modi",
  "Mongolian": "Mong",
  "Mro": "Mroo",
  "Multani": "Mult",
  "Myanmar": "Mymr",
  "Nabataean": "Nbat",
  "Nag_Mundari": "Nagm",
  "Nandinagari": "Nand",
  "New_Tai_Lue": "Talu",
  "Newa": "Newa",
  "Nko": "Nkoo",
  "Nushu": "Nshu",
  "Nyiakeng_Puachue_Hmong": "Hmnp",
  "Ogham": "Ogam",
  "Ol_Chiki": "Olck",
  "Ol_Onal": "Onao",
  "Old_Hungarian": "Hung",
  "Old_Italic": "Ital",
  "Old_North_Arabian": "Narb",
  "Old_Permic": "Perm",
  "Old_Persian": "Xpeo",
  "Old_Sogdian": "Sogo",
  "Old_South_Arabian": "Sarb",
  "Old_Turkic": "Orkh",
  "Old_Uyghur": "Ougr",
  "Oriya": "Orya",
  "Osage": "Osge",
  "Osmanya": "Osma",
  "Pahawh_Hmong": "Hmng",
  "Palmyrene": "Palm",
  "Pau_Cin_Hau": "Pauc",
  "Phags_Pa": "Phag",
  "Phoenician": "Phnx",
  "Psalter_Pahlavi": "Phlp",
  "Rejang": "Rjng",
  "Runic": "Runr",
  "Samaritan": "Samr",
  "Saurashtra": "Saur",
  "Sharada": "Shrd",
  "Shavian": "Shaw",
  "Siddham": "Sidd",
  "Sidetic": "Sidt",
  "SignWriting": "Sgnw",
  "Signwriting": "Sgnw",
  "Sinhala": "Sinh",
  "Sogdian": "Sogd",
  "Sora_Sompeng": "Sora",
  "Soyombo": "Soyo",
  "Sundanese": "Sund",
  "Sunuwar": "Sunu",
  "Syloti_Nagri": "Sylo",
  "Syriac": "Syrc",
  "Tagalog": "Tglg",
  "Tagbanwa": "Tagb",
  "Tai_Le": "Tale",
  "Tai_Tham": "Lana",
  "Tai_Viet": "Tavt",
  "Tai_Yo": "Tayo",
  "Takri": "Takr",
  "Tamil": "Taml",
  "Tangsa": "Tnsa",
  "Tangut": "Tang",
  "Telugu": "Telu",
  "Thaana": "Thaa",
  "Thai": "Thai",
  "Tibetan": "Tibt",
  "Tifinagh": "Tfng",
  "Tirhuta": "Tirh",
  "Todhri": "Todr",
  "Tolong_Siki": "Tols",
  "Toto": "Toto",
  "Tulu_Tigalari": "Tutg",
  "Ugaritic": "Ugar",
  "Unknown": "Zzzz",
  "Vai": "Vaii",
  "Vithkuqi": "Vith",
  "Wancho": "Wcho",
  "Warang_Citi": "Wara",
  "Yezidi": "Yezi",
  "Yi": "Yiii",
  "Zanabazar_Square": "Zanb",
};
