// Root adapter over the text-engine workspace's public entry points (packages/text-engine/README.md).
export {
  clearEmbeddedFonts,
  clearGlyphDefs,
  clearWebfonts,
  type FontSynthesisAllowance,
  getFontInstance,
  getGlyphDefs,
  getRenderTextMode,
  registerLocalFontAlias,
  registerWebfont,
  type RenderTextMode,
  restoreGeneration,
  setRenderTextMode,
  snapshotGeneration,
} from "@domotion/text-engine/font-resolution";
export {
  computeSkipInkGaps,
  cssWeightOf,
  getDecorationMetrics,
  isStretchyFenceChar,
  measureEmphasisMarkMetrics,
  measureInkMetrics,
  measureTruncationMarker,
  renderRadicalGlyph,
  renderSourceOwnedTextBoundary,
  renderStretchyFenceGlyph,
  renderTextAsPath,
  selectedGlyphRasterSpans,
} from "@domotion/text-engine/text";
