// AUTO-GENERATED by tools/probe-983-genroutes.mjs — do not edit by hand.
// Source data: /tmp/unicode-fonts.json (produced by tools/probe-983-sweep.mjs).
// Maps Unicode blocks to the macOS font family Chrome's CoreText fallback
// picks via CDP `CSS.getPlatformFontsForNode`. Consulted by
// `darwinFallbackChain` as the final fallback when no hand-coded route
// matches a given codepoint. Fonts marked `extractor: "native"` here
// crash fontkit ("invalid array length" in ArrayPrototypeSplice during
// GSUB shaping — verified per-font by spawnSync probe in the generator);
// the renderer routes them through the macOS CoreText glyph-helper.

export interface UnicodeFontEntry { path: string; postscriptName?: string; extractor?: "fontkit" | "native" }

export const UNICODE_FONT_PATHS: Record<string, UnicodeFontEntry> = {
  "u-sf-pro-text": { path: "/System/Library/Fonts/SFNS.ttf" },
  "u-helvetica-neue": { path: "/System/Library/Fonts/Helvetica.ttc", postscriptName: "Helvetica" },
  "u-noto-sans": { path: "/Library/Fonts/NotoSans-Regular.ttf" },
  "u-mshtakan": { path: "/System/Library/Fonts/Supplemental/Mshtakan.ttc", postscriptName: "Mshtakan" },
  "u-arial-unicode-ms": { path: "/System/Library/Fonts/Supplemental/Arial Unicode.ttf" },
  "u-geeza-pro": { path: "/System/Library/Fonts/GeezaPro.ttc", postscriptName: "GeezaPro" },
  "u-noto-sans-syriac": { path: "/System/Library/Fonts/Supplemental/NotoSansSyriac-Regular.ttf" },
  "u-noto-sans-thaana": { path: "/System/Library/Fonts/Supplemental/NotoSansThaana-Regular.ttf" },
  "u-noto-sans-nko": { path: "/System/Library/Fonts/Supplemental/NotoSansNKo-Regular.ttf" },
  "u-noto-sans-samaritan": { path: "/System/Library/Fonts/Supplemental/NotoSansSamaritan-Regular.ttf" },
  "u-noto-sans-mandaic": { path: "/System/Library/Fonts/Supplemental/NotoSansMandaic-Regular.ttf" },
  "u-sf-arabic": { path: "/System/Library/Fonts/SFArabic.ttf" },
  "u-itf-devanagari": { path: "/System/Library/Fonts/Supplemental/DevanagariMT.ttc", postscriptName: "DevanagariMT" },
  "u-kohinoor-bangla": { path: "/System/Library/Fonts/KohinoorBangla.ttc", postscriptName: "KohinoorBangla-Regular" },
  "u-gurmukhi-sangam-mn": { path: "/System/Library/Fonts/Supplemental/Gurmukhi Sangam MN.ttc", postscriptName: "GurmukhiSangamMN", extractor: "native" as const },
  "u-kohinoor-gujarati": { path: "/System/Library/Fonts/KohinoorGujarati.ttc", postscriptName: "KohinoorGujarati-Regular" },
  "u-oriya-sangam-mn": { path: "/System/Library/Fonts/Supplemental/Oriya Sangam MN.ttc", postscriptName: "OriyaSangamMN" },
  "u-tamil-sangam-mn": { path: "/System/Library/Fonts/Supplemental/Tamil Sangam MN.ttc", postscriptName: "TamilSangamMN" },
  "u-kohinoor-telugu": { path: "/System/Library/Fonts/KohinoorTelugu.ttc", postscriptName: "KohinoorTelugu-Regular" },
  "u-kannada-sangam-mn": { path: "/System/Library/Fonts/Supplemental/Kannada Sangam MN.ttc", postscriptName: "KannadaSangamMN" },
  "u-sf-malayalam": { path: "/System/Library/Fonts/Supplemental/Malayalam Sangam MN.ttc", postscriptName: "MalayalamSangamMN" },
  "u-sinhala-sangam-mn": { path: "/System/Library/Fonts/Supplemental/Sinhala Sangam MN.ttc", postscriptName: "SinhalaSangamMN" },
  "u-sukhumvit-set": { path: "/System/Library/Fonts/Supplemental/SukhumvitSet.ttc", postscriptName: "SukhumvitSet-Text" },
  "u-lao-sangam-mn": { path: "/System/Library/Fonts/Supplemental/Lao Sangam MN.ttf" },
  "u-kailasa": { path: "/System/Library/Fonts/Supplemental/Kailasa.ttc", postscriptName: "Kailasa" },
  "u-myanmar-sangam-mn": { path: "/System/Library/Fonts/Supplemental/Myanmar Sangam MN.ttc", postscriptName: "MyanmarSangamMN" },
  "u-apple-sd-gothic-neo": { path: "/System/Library/Fonts/AppleSDGothicNeo.ttc", postscriptName: "AppleSDGothicNeo-Regular" },
  "u-kefa-iii": { path: "/System/Library/Fonts/Supplemental/KefaIII.ttf" },
  "u-plantagenet-cherokee": { path: "/System/Library/Fonts/Supplemental/PlantagenetCherokee.ttf" },
  "u-euphemia-ucas": { path: "/System/Library/Fonts/Supplemental/EuphemiaCAS.ttc", postscriptName: "EuphemiaUCAS" },
  "u-apple-symbols": { path: "/System/Library/Fonts/Apple Symbols.ttf" },
  "u-noto-sans-tagalog": { path: "/System/Library/Fonts/Supplemental/NotoSansTagalog-Regular.ttf" },
  "u-noto-sans-hanunoo": { path: "/System/Library/Fonts/Supplemental/NotoSansHanunoo-Regular.ttf" },
  "u-noto-sans-buhid": { path: "/System/Library/Fonts/Supplemental/NotoSansBuhid-Regular.ttf" },
  "u-noto-sans-tagbanwa": { path: "/System/Library/Fonts/Supplemental/NotoSansTagbanwa-Regular.ttf" },
  "u-khmer-sangam-mn": { path: "/System/Library/Fonts/Supplemental/Khmer Sangam MN.ttf" },
  "u-noto-sans-mongolian": { path: "/System/Library/Fonts/Supplemental/NotoSansMongolian-Regular.ttf", extractor: "native" as const },
  "u-noto-sans-limbu": { path: "/System/Library/Fonts/Supplemental/NotoSansLimbu-Regular.ttf" },
  "u-noto-sans-tai-le": { path: "/System/Library/Fonts/Supplemental/NotoSansTaiLe-Regular.ttf" },
  "u-noto-sans-newtailue": { path: "/System/Library/Fonts/Supplemental/NotoSansNewTaiLue-Regular.ttf" },
  "u-noto-sans-buginese": { path: "/System/Library/Fonts/Supplemental/NotoSansBuginese-Regular.ttf" },
  "u-noto-sans-tai-tham": { path: "/System/Library/Fonts/Supplemental/NotoSansTaiTham-Regular.ttf" },
  "u-noto-serif-balinese": { path: "/System/Library/Fonts/Supplemental/NotoSerifBalinese-Regular.ttf", extractor: "native" as const },
  "u-noto-sans-sundanese": { path: "/System/Library/Fonts/Supplemental/NotoSansSundanese-Regular.ttf", extractor: "native" as const },
  "u-noto-sans-batak": { path: "/System/Library/Fonts/Supplemental/NotoSansBatak-Regular.ttf" },
  "u-noto-sans-lepcha": { path: "/System/Library/Fonts/Supplemental/NotoSansLepcha-Regular.ttf" },
  "u-noto-sans-ol-chiki": { path: "/System/Library/Fonts/Supplemental/NotoSansOlChiki-Regular.ttf" },
  "u-grantha-sangam-mn": { path: "/System/Library/Fonts/Supplemental/Tamil Sangam MN.ttc", postscriptName: "GranthaSangamMN-Regular", extractor: "native" as const },
  "u-arial": { path: "/System/Library/Fonts/Supplemental/Arial.ttf" },
  "u-stix-two-math": { path: "/System/Library/Fonts/Supplemental/STIXTwoMath.otf" },
  "u-noto-sans-glagolitic": { path: "/System/Library/Fonts/Supplemental/NotoSansGlagolitic-Regular.ttf" },
  "u-noto-sans-coptic": { path: "/System/Library/Fonts/Supplemental/NotoSansCoptic-Regular.ttf", extractor: "native" as const },
  "u-noto-sans-tifinagh": { path: "/System/Library/Fonts/Supplemental/NotoSansTifinagh-Regular.otf" },
  "u-hiragino-sans-gb": { path: "/System/Library/Fonts/Hiragino Sans GB.ttc", postscriptName: "HiraginoSansGB-W3" },
  "u-heiti-sc": { path: "/System/Library/Fonts/STHeiti Light.ttc", postscriptName: "STHeitiSC-Light" },
  "u-hiragino-sans": { path: "/System/Library/Fonts/ヒラギノ角ゴシック W3.ttc", postscriptName: "HiraKakuProN-W3" },
  "u-noto-sans-kr": { path: "/Library/Fonts/NotoSansKR-Regular.otf" },
  "u-noto-sans-yi": { path: "/System/Library/Fonts/Supplemental/NotoSansYi-Regular.ttf" },
  "u-noto-sans-lisu": { path: "/System/Library/Fonts/Supplemental/NotoSansLisu-Regular.ttf" },
  "u-noto-sans-vai": { path: "/System/Library/Fonts/Supplemental/NotoSansVai-Regular.ttf" },
  "u-noto-sans-bamum": { path: "/System/Library/Fonts/Supplemental/NotoSansBamum-Regular.ttf" },
  "u-noto-sans-syloti-nagri": { path: "/System/Library/Fonts/Supplemental/NotoSansSylotiNagri-Regular.ttf" },
  "u-muktamahee-regular": { path: "/System/Library/Fonts/MuktaMahee.ttc", postscriptName: "MuktaMahee-Regular" },
  "u-noto-sans-phagspa": { path: "/System/Library/Fonts/Supplemental/NotoSansPhagsPa-Regular.ttf" },
  "u-noto-sans-saurashtra": { path: "/System/Library/Fonts/Supplemental/NotoSansSaurashtra-Regular.ttf", extractor: "native" as const },
  "u-noto-sans-kayah-li": { path: "/System/Library/Fonts/Supplemental/NotoSansKayahLi-Regular.ttf" },
  "u-noto-sans-rejang": { path: "/System/Library/Fonts/Supplemental/NotoSansRejang-Regular.ttf" },
  "u-noto-sans-javanese": { path: "/System/Library/Fonts/Supplemental/NotoSansJavanese-Regular.otf", extractor: "native" as const },
  "u-noto-sans-myanmar": { path: "/System/Library/Fonts/NotoSansMyanmar.ttc", extractor: "native" as const },
  "u-noto-sans-cham": { path: "/System/Library/Fonts/Supplemental/NotoSansCham-Regular.ttf" },
  "u-noto-sans-tai-viet": { path: "/System/Library/Fonts/Supplemental/NotoSansTaiViet-Regular.ttf" },
  "u-noto-sans-meeteimayek": { path: "/System/Library/Fonts/Supplemental/NotoSansMeeteiMayek-Regular.ttf", extractor: "native" as const },
  "u-galvji": { path: "/System/Library/Fonts/Supplemental/Galvji.ttc", postscriptName: "Galvji" },
  "u-noto-sans-linear-b": { path: "/System/Library/Fonts/Supplemental/NotoSansLinearB-Regular.ttf" },
  "u-big-caslon": { path: "/System/Library/Fonts/Supplemental/BigCaslon.ttf" },
  "u-noto-sans-lycian": { path: "/System/Library/Fonts/Supplemental/NotoSansLycian-Regular.ttf" },
  "u-noto-sans-carian": { path: "/System/Library/Fonts/Supplemental/NotoSansCarian-Regular.ttf" },
  "u-noto-sans-old-italic": { path: "/System/Library/Fonts/Supplemental/NotoSansOldItalic-Regular.ttf" },
  "u-noto-sans-gothic": { path: "/System/Library/Fonts/Supplemental/NotoSansGothic-Regular.ttf" },
  "u-noto-sans-old-permic": { path: "/System/Library/Fonts/Supplemental/NotoSansOldPermic-Regular.ttf" },
  "u-noto-sans-ugaritic": { path: "/System/Library/Fonts/Supplemental/NotoSansUgaritic-Regular.ttf" },
  "u-noto-sans-oldpersian": { path: "/System/Library/Fonts/Supplemental/NotoSansOldPersian-Regular.ttf" },
  "u-noto-sans-osmanya": { path: "/System/Library/Fonts/Supplemental/NotoSansOsmanya-Regular.ttf" },
  "u-noto-sans-osage": { path: "/System/Library/Fonts/Supplemental/NotoSansOsage-Regular.ttf" },
  "u-noto-sans-elbasan": { path: "/System/Library/Fonts/Supplemental/NotoSansElbasan-Regular.ttf" },
  "u-noto-sans-caucalban": { path: "/System/Library/Fonts/Supplemental/NotoSansCaucasianAlbanian-Regular.ttf" },
  "u-noto-sans-linear-a": { path: "/System/Library/Fonts/Supplemental/NotoSansLinearA-Regular.ttf" },
  "u-noto-sans-cypriot": { path: "/System/Library/Fonts/Supplemental/NotoSansCypriot-Regular.ttf" },
  "u-noto-sans-imparamaic": { path: "/System/Library/Fonts/Supplemental/NotoSansImperialAramaic-Regular.ttf" },
  "u-noto-sans-palmyrene": { path: "/System/Library/Fonts/Supplemental/NotoSansPalmyrene-Regular.ttf" },
  "u-noto-sans-nabataean": { path: "/System/Library/Fonts/Supplemental/NotoSansNabataean-Regular.ttf" },
  "u-noto-sans-hatran": { path: "/System/Library/Fonts/Supplemental/NotoSansHatran-Regular.ttf" },
  "u-noto-sans-phoenician": { path: "/System/Library/Fonts/Supplemental/NotoSansPhoenician-Regular.ttf" },
  "u-noto-sans-lydian": { path: "/System/Library/Fonts/Supplemental/NotoSansLydian-Regular.ttf" },
  "u-noto-sans-meroitic": { path: "/System/Library/Fonts/Supplemental/NotoSansMeroitic-Regular.ttf" },
  "u-noto-sans-kharoshthi": { path: "/System/Library/Fonts/Supplemental/NotoSansKharoshthi-Regular.ttf", extractor: "native" as const },
  "u-noto-sans-oldsouarab": { path: "/System/Library/Fonts/Supplemental/NotoSansOldSouthArabian-Regular.ttf" },
  "u-noto-sans-oldnorarab": { path: "/System/Library/Fonts/Supplemental/NotoSansOldNorthArabian-Regular.ttf" },
  "u-noto-sans-manichaean": { path: "/System/Library/Fonts/Supplemental/NotoSansManichaean-Regular.ttf" },
  "u-noto-sans-avestan": { path: "/System/Library/Fonts/Supplemental/NotoSansAvestan-Regular.ttf" },
  "u-noto-sans-insparthi": { path: "/System/Library/Fonts/Supplemental/NotoSansInscriptionalParthian-Regular.ttf" },
  "u-noto-sans-inspahlavi": { path: "/System/Library/Fonts/Supplemental/NotoSansInscriptionalPahlavi-Regular.ttf" },
  "u-noto-sans-psapahlavi": { path: "/System/Library/Fonts/Supplemental/NotoSansPsalterPahlavi-Regular.ttf" },
  "u-noto-sans-old-turkic": { path: "/System/Library/Fonts/Supplemental/NotoSansOldTurkic-Regular.ttf" },
  "u-noto-sans-oldhung": { path: "/System/Library/Fonts/Supplemental/NotoSansOldHungarian-Regular.ttf" },
  "u-noto-sans-hanifirohg": { path: "/System/Library/Fonts/Supplemental/NotoSansHanifiRohingya-Regular.ttf" },
  "u-noto-serif-yezidi": { path: "/System/Library/Fonts/Supplemental/NotoSerifYezidi-Regular.otf" },
  "u-noto-sans-brahmi": { path: "/System/Library/Fonts/Supplemental/NotoSansBrahmi-Regular.ttf", extractor: "native" as const },
  "u-noto-sans-kaithi": { path: "/System/Library/Fonts/Supplemental/NotoSansKaithi-Regular.ttf", extractor: "native" as const },
  "u-noto-sans-sorasomp": { path: "/System/Library/Fonts/Supplemental/NotoSansSoraSompeng-Regular.ttf" },
  "u-noto-sans-chakma": { path: "/System/Library/Fonts/Supplemental/NotoSansChakma-Regular.ttf", extractor: "native" as const },
  "u-noto-sans-mahajani": { path: "/System/Library/Fonts/Supplemental/NotoSansMahajani-Regular.ttf" },
  "u-noto-sans-sharada": { path: "/System/Library/Fonts/Supplemental/NotoSansSharada-Regular.ttf", extractor: "native" as const },
  "u-noto-sans-khojki": { path: "/System/Library/Fonts/Supplemental/NotoSansKhojki-Regular.ttf", extractor: "native" as const },
  "u-noto-sans-multani": { path: "/System/Library/Fonts/Supplemental/NotoSansMultani-Regular.ttf" },
  "u-noto-sans-khudawadi": { path: "/System/Library/Fonts/Supplemental/NotoSansKhudawadi-Regular.ttf" },
  "u-noto-sans-newa": { path: "/System/Library/Fonts/Supplemental/NotoSansNewa-Regular.ttf" },
  "u-noto-sans-tirhuta": { path: "/System/Library/Fonts/Supplemental/NotoSansTirhuta-Regular.ttf", extractor: "native" as const },
  "u-noto-sans-siddham": { path: "/System/Library/Fonts/Supplemental/NotoSansSiddham-Regular.otf", extractor: "native" as const },
  "u-noto-sans-modi": { path: "/System/Library/Fonts/Supplemental/NotoSansModi-Regular.ttf", extractor: "native" as const },
  "u-noto-sans-takri": { path: "/System/Library/Fonts/Supplemental/NotoSansTakri-Regular.ttf", extractor: "native" as const },
  "u-noto-serif-ahom": { path: "/System/Library/Fonts/Supplemental/NotoSerifAhom-Regular.ttf" },
  "u-noto-sans-warangciti": { path: "/System/Library/Fonts/Supplemental/NotoSansWarangCiti-Regular.ttf" },
  "u-noto-sans-paucinhau": { path: "/System/Library/Fonts/Supplemental/NotoSansPauCinHau-Regular.ttf" },
  "u-noto-sans-bhaiksuki": { path: "/System/Library/Fonts/Supplemental/NotoSansBhaiksuki-Regular.ttf" },
  "u-noto-sans-marchen": { path: "/System/Library/Fonts/Supplemental/NotoSansMarchen-Regular.ttf" },
  "u-noto-sans-masaram-gondi": { path: "/System/Library/Fonts/Supplemental/NotoSansMasaramGondi-Regular.otf" },
  "u-noto-sans-gunjala-gondi": { path: "/System/Library/Fonts/Supplemental/NotoSansGunjalaGondi-Regular.otf" },
  "u-noto-sans-cuneiform": { path: "/System/Library/Fonts/Supplemental/NotoSansCuneiform-Regular.ttf" },
  "u-noto-sans-egypthiero": { path: "/System/Library/Fonts/Supplemental/NotoSansEgyptianHieroglyphs-Regular.ttf" },
  "u-noto-sans-mro": { path: "/System/Library/Fonts/Supplemental/NotoSansMro-Regular.ttf" },
  "u-noto-sans-bassa-vah": { path: "/System/Library/Fonts/Supplemental/NotoSansBassaVah-Regular.ttf" },
  "u-noto-sans-pahawh-hmong": { path: "/System/Library/Fonts/Supplemental/NotoSansPahawhHmong-Regular.ttf" },
  "u-noto-sans-miao": { path: "/System/Library/Fonts/Supplemental/NotoSansMiao-Regular.ttf" },
  "u-noto-sans-duployan": { path: "/System/Library/Fonts/Supplemental/NotoSansDuployan-Regular.ttf" },
  "u-sf-compact": { path: "/System/Library/Fonts/SFCompact.ttf" },
  "u-noto-serif-hmong-nyiakeng": { path: "/System/Library/Fonts/Supplemental/NotoSerifNyiakengPuachueHmong-Regular.ttf" },
  "u-noto-sans-wancho": { path: "/System/Library/Fonts/Supplemental/NotoSansWancho-Regular.ttf" },
  "u-noto-sans-nag-mundari": { path: "/System/Library/Fonts/Supplemental/NotoSansNagMundari-Regular.ttf" },
  "u-noto-sans-mende-kikakui": { path: "/System/Library/Fonts/Supplemental/NotoSansMendeKikakui-Regular.ttf" },
  "u-noto-sans-adlam": { path: "/System/Library/Fonts/Supplemental/NotoSansAdlam-Regular.ttf" },
  "u-hiragino-kaku-gothic-pron": { path: "/System/Library/Fonts/ヒラギノ角ゴシック W3.ttc", postscriptName: "HiraKakuProN-W3" },
};

/** [start, end, fontKey] tuples sorted by start. Probed by binary-searching for the matching range. */
export const UNICODE_FONT_RANGES: ReadonlyArray<readonly [number, number, string]> = [
  [0x0, 0x7F, "u-sf-pro-text"], // 0000-007F-basic-latin (SF Pro Text)
  [0x80, 0xFF, "u-sf-pro-text"], // 0080-00FF-latin-1-supplement (SF Pro Text)
  [0x100, 0x17F, "u-sf-pro-text"], // 0100-017F-latin-extended-a (SF Pro Text)
  [0x180, 0x24F, "u-helvetica-neue"], // 0180-024F-latin-extended-b (Helvetica Neue)
  [0x250, 0x2AF, "u-sf-pro-text"], // 0250-02AF-ipa-extensions (SF Pro Text)
  [0x2B0, 0x2FF, "u-sf-pro-text"], // 02B0-02FF-spacing-modifier-letters (SF Pro Text)
  [0x300, 0x36F, "u-sf-pro-text"], // 0300-036F-combining-diacritical-marks (SF Pro Text)
  [0x370, 0x3FF, "u-noto-sans"], // 0370-03FF-greek-and-coptic (Noto Sans)
  [0x400, 0x4FF, "u-sf-pro-text"], // 0400-04FF-cyrillic (SF Pro Text)
  [0x500, 0x52F, "u-helvetica-neue"], // 0500-052F-cyrillic-supplement (Helvetica Neue)
  [0x530, 0x58F, "u-mshtakan"], // 0530-058F-armenian (Mshtakan)
  [0x590, 0x5FF, "u-arial-unicode-ms"], // 0590-05FF-hebrew (Arial Unicode MS)
  [0x600, 0x6FF, "u-geeza-pro"], // 0600-06FF-arabic (Geeza Pro)
  [0x700, 0x74F, "u-noto-sans-syriac"], // 0700-074F-syriac (Noto Sans Syriac)
  [0x750, 0x77F, "u-geeza-pro"], // 0750-077F-arabic-supplement (Geeza Pro)
  [0x780, 0x7BF, "u-noto-sans-thaana"], // 0780-07BF-thaana (Noto Sans Thaana)
  [0x7C0, 0x7FF, "u-noto-sans-nko"], // 07C0-07FF-nko (Noto Sans NKo)
  [0x800, 0x83F, "u-noto-sans-samaritan"], // 0800-083F-samaritan (Noto Sans Samaritan)
  [0x840, 0x85F, "u-noto-sans-mandaic"], // 0840-085F-mandaic (Noto Sans Mandaic)
  [0x860, 0x86F, "u-arial-unicode-ms"], // 0860-086F-syriac-supplement (Arial Unicode MS)
  [0x870, 0x89F, "u-arial-unicode-ms"], // 0870-089F-arabic-extended-b (Arial Unicode MS)
  [0x8A0, 0x8FF, "u-sf-arabic"], // 08A0-08FF-arabic-extended-a (SF Arabic)
  [0x900, 0x97F, "u-itf-devanagari"], // 0900-097F-devanagari (ITF Devanagari)
  [0x980, 0x9FF, "u-kohinoor-bangla"], // 0980-09FF-bengali (Kohinoor Bangla)
  [0xA00, 0xA7F, "u-gurmukhi-sangam-mn"], // 0A00-0A7F-gurmukhi (Gurmukhi Sangam MN)
  [0xA80, 0xAFF, "u-kohinoor-gujarati"], // 0A80-0AFF-gujarati (Kohinoor Gujarati)
  [0xB00, 0xB7F, "u-oriya-sangam-mn"], // 0B00-0B7F-oriya (Oriya Sangam MN)
  [0xB80, 0xBFF, "u-tamil-sangam-mn"], // 0B80-0BFF-tamil (Tamil Sangam MN)
  [0xC00, 0xC7F, "u-kohinoor-telugu"], // 0C00-0C7F-telugu (Kohinoor Telugu)
  [0xC80, 0xCFF, "u-kannada-sangam-mn"], // 0C80-0CFF-kannada (Kannada Sangam MN)
  [0xD00, 0xD7F, "u-sf-malayalam"], // 0D00-0D7F-malayalam (.SF Malayalam)
  [0xD80, 0xDFF, "u-sinhala-sangam-mn"], // 0D80-0DFF-sinhala (Sinhala Sangam MN)
  [0xE00, 0xE7F, "u-sukhumvit-set"], // 0E00-0E7F-thai (Sukhumvit Set)
  [0xE80, 0xEFF, "u-lao-sangam-mn"], // 0E80-0EFF-lao (Lao Sangam MN)
  [0xF00, 0xFFF, "u-kailasa"], // 0F00-0FFF-tibetan (Kailasa)
  [0x1000, 0x109F, "u-myanmar-sangam-mn"], // 1000-109F-myanmar (Myanmar Sangam MN)
  [0x10A0, 0x10FF, "u-arial-unicode-ms"], // 10A0-10FF-georgian (Arial Unicode MS)
  [0x1100, 0x11FF, "u-apple-sd-gothic-neo"], // 1100-11FF-hangul-jamo (Apple SD Gothic Neo)
  [0x1200, 0x137F, "u-kefa-iii"], // 1200-137F-ethiopic (Kefa III)
  [0x1380, 0x139F, "u-kefa-iii"], // 1380-139F-ethiopic-supplement (Kefa III)
  [0x13A0, 0x13FF, "u-plantagenet-cherokee"], // 13A0-13FF-cherokee (Plantagenet Cherokee)
  [0x1400, 0x167F, "u-euphemia-ucas"], // 1400-167F-unified-canadian-aboriginal-syllabics (Euphemia UCAS)
  [0x1680, 0x169F, "u-apple-symbols"], // 1680-169F-ogham (Apple Symbols)
  [0x16A0, 0x16FF, "u-apple-symbols"], // 16A0-16FF-runic (Apple Symbols)
  [0x1700, 0x171F, "u-noto-sans-tagalog"], // 1700-171F-tagalog (Noto Sans Tagalog)
  [0x1720, 0x173F, "u-noto-sans-hanunoo"], // 1720-173F-hanunoo (Noto Sans Hanunoo)
  [0x1740, 0x175F, "u-noto-sans-buhid"], // 1740-175F-buhid (Noto Sans Buhid)
  [0x1760, 0x177F, "u-noto-sans-tagbanwa"], // 1760-177F-tagbanwa (Noto Sans Tagbanwa)
  [0x1780, 0x17FF, "u-khmer-sangam-mn"], // 1780-17FF-khmer (Khmer Sangam MN)
  [0x1800, 0x18AF, "u-noto-sans-mongolian"], // 1800-18AF-mongolian (Noto Sans Mongolian)
  [0x18B0, 0x18FF, "u-euphemia-ucas"], // 18B0-18FF-unified-canadian-aboriginal-syllabics-extended (Euphemia UCAS)
  [0x1900, 0x194F, "u-noto-sans-limbu"], // 1900-194F-limbu (Noto Sans Limbu)
  [0x1950, 0x197F, "u-noto-sans-tai-le"], // 1950-197F-tai-le (Noto Sans Tai Le)
  [0x1980, 0x19DF, "u-noto-sans-newtailue"], // 1980-19DF-new-tai-lue (Noto Sans NewTaiLue)
  [0x19E0, 0x19FF, "u-khmer-sangam-mn"], // 19E0-19FF-khmer-symbols (Khmer Sangam MN)
  [0x1A00, 0x1A1F, "u-noto-sans-buginese"], // 1A00-1A1F-buginese (Noto Sans Buginese)
  [0x1A20, 0x1AAF, "u-noto-sans-tai-tham"], // 1A20-1AAF-tai-tham (Noto Sans Tai Tham)
  [0x1AB0, 0x1AFF, "u-noto-sans"], // 1AB0-1AFF-combining-diacritical-marks-extended (Noto Sans)
  [0x1B00, 0x1B7F, "u-noto-serif-balinese"], // 1B00-1B7F-balinese (Noto Serif Balinese)
  [0x1B80, 0x1BBF, "u-noto-sans-sundanese"], // 1B80-1BBF-sundanese (Noto Sans Sundanese)
  [0x1BC0, 0x1BFF, "u-noto-sans-batak"], // 1BC0-1BFF-batak (Noto Sans Batak)
  [0x1C00, 0x1C4F, "u-noto-sans-lepcha"], // 1C00-1C4F-lepcha (Noto Sans Lepcha)
  [0x1C50, 0x1C7F, "u-noto-sans-ol-chiki"], // 1C50-1C7F-ol-chiki (Noto Sans Ol Chiki)
  [0x1C80, 0x1C8F, "u-noto-sans"], // 1C80-1C8F-cyrillic-extended-c (Noto Sans)
  [0x1C90, 0x1CBF, "u-helvetica-neue"], // 1C90-1CBF-georgian-extended (Helvetica Neue)
  [0x1CC0, 0x1CCF, "u-noto-sans-sundanese"], // 1CC0-1CCF-sundanese-supplement (Noto Sans Sundanese)
  [0x1CD0, 0x1CFF, "u-grantha-sangam-mn"], // 1CD0-1CFF-vedic-extensions (Grantha Sangam MN)
  [0x1D00, 0x1D7F, "u-sf-pro-text"], // 1D00-1D7F-phonetic-extensions (SF Pro Text)
  [0x1D80, 0x1DBF, "u-arial"], // 1D80-1DBF-phonetic-extensions-supplement (Arial)
  [0x1DC0, 0x1DFF, "u-helvetica-neue"], // 1DC0-1DFF-combining-diacritical-marks-supplement (Helvetica Neue)
  [0x1E00, 0x1EFF, "u-sf-pro-text"], // 1E00-1EFF-latin-extended-additional (SF Pro Text)
  [0x1F00, 0x1FFF, "u-helvetica-neue"], // 1F00-1FFF-greek-extended (Helvetica Neue)
  [0x2000, 0x206F, "u-sf-pro-text"], // 2000-206F-general-punctuation (SF Pro Text)
  [0x2070, 0x209F, "u-sf-pro-text"], // 2070-209F-superscripts-and-subscripts (SF Pro Text)
  [0x20A0, 0x20CF, "u-helvetica-neue"], // 20A0-20CF-currency-symbols (Helvetica Neue)
  [0x20D0, 0x20FF, "u-stix-two-math"], // 20D0-20FF-combining-diacritical-marks-for-symbols (STIX Two Math)
  [0x2100, 0x214F, "u-sf-pro-text"], // 2100-214F-letterlike-symbols (SF Pro Text)
  [0x2150, 0x218F, "u-sf-pro-text"], // 2150-218F-number-forms (SF Pro Text)
  [0x2190, 0x21FF, "u-sf-pro-text"], // 2190-21FF-arrows (SF Pro Text)
  [0x2200, 0x22FF, "u-apple-symbols"], // 2200-22FF-mathematical-operators (Apple Symbols)
  [0x2300, 0x23FF, "u-sf-pro-text"], // 2300-23FF-miscellaneous-technical (SF Pro Text)
  [0x2400, 0x243F, "u-apple-symbols"], // 2400-243F-control-pictures (Apple Symbols)
  [0x2440, 0x245F, "u-apple-symbols"], // 2440-245F-optical-character-recognition (Apple Symbols)
  [0x2460, 0x24FF, "u-sf-pro-text"], // 2460-24FF-enclosed-alphanumerics (SF Pro Text)
  [0x2500, 0x257F, "u-helvetica-neue"], // 2500-257F-box-drawing (Helvetica Neue)
  [0x2580, 0x259F, "u-arial"], // 2580-259F-block-elements (Arial)
  [0x25A0, 0x25FF, "u-sf-pro-text"], // 25A0-25FF-geometric-shapes (SF Pro Text)
  [0x2600, 0x26FF, "u-apple-symbols"], // 2600-26FF-miscellaneous-symbols (Apple Symbols)
  [0x2700, 0x27BF, "u-arial-unicode-ms"], // 2700-27BF-dingbats (Arial Unicode MS)
  [0x27C0, 0x27EF, "u-apple-symbols"], // 27C0-27EF-miscellaneous-mathematical-symbols-a (Apple Symbols)
  [0x27F0, 0x27FF, "u-apple-symbols"], // 27F0-27FF-supplemental-arrows-a (Apple Symbols)
  [0x2800, 0x28FF, "u-apple-symbols"], // 2800-28FF-braille-patterns (Apple Symbols)
  [0x2900, 0x297F, "u-apple-symbols"], // 2900-297F-supplemental-arrows-b (Apple Symbols)
  [0x2980, 0x29FF, "u-apple-symbols"], // 2980-29FF-miscellaneous-mathematical-symbols-b (Apple Symbols)
  [0x2A00, 0x2AFF, "u-apple-symbols"], // 2A00-2AFF-supplemental-mathematical-operators (Apple Symbols)
  [0x2B00, 0x2BFF, "u-apple-symbols"], // 2B00-2BFF-miscellaneous-symbols-and-arrows (Apple Symbols)
  [0x2C00, 0x2C5F, "u-noto-sans-glagolitic"], // 2C00-2C5F-glagolitic (Noto Sans Glagolitic)
  [0x2C60, 0x2C7F, "u-helvetica-neue"], // 2C60-2C7F-latin-extended-c (Helvetica Neue)
  [0x2C80, 0x2CFF, "u-noto-sans-coptic"], // 2C80-2CFF-coptic (Noto Sans Coptic)
  [0x2D00, 0x2D2F, "u-arial-unicode-ms"], // 2D00-2D2F-georgian-supplement (Arial Unicode MS)
  [0x2D30, 0x2D7F, "u-noto-sans-tifinagh"], // 2D30-2D7F-tifinagh (Noto Sans Tifinagh)
  [0x2D80, 0x2DDF, "u-kefa-iii"], // 2D80-2DDF-ethiopic-extended (Kefa III)
  [0x2DE0, 0x2DFF, "u-noto-sans"], // 2DE0-2DFF-cyrillic-extended-a (Noto Sans)
  [0x2E00, 0x2E7F, "u-helvetica-neue"], // 2E00-2E7F-supplemental-punctuation (Helvetica Neue)
  [0x2E80, 0x2EFF, "u-hiragino-sans-gb"], // 2E80-2EFF-cjk-radicals-supplement (Hiragino Sans GB)
  [0x2F00, 0x2FDF, "u-hiragino-sans-gb"], // 2F00-2FDF-kangxi-radicals (Hiragino Sans GB)
  [0x2FF0, 0x2FFF, "u-heiti-sc"], // 2FF0-2FFF-ideographic-description-characters (Heiti SC)
  [0x3000, 0x303F, "u-arial-unicode-ms"], // 3000-303F-cjk-symbols-and-punctuation (Arial Unicode MS)
  [0x3040, 0x309F, "u-hiragino-sans"], // 3040-309F-hiragana (Hiragino Sans)
  [0x3100, 0x312F, "u-hiragino-sans-gb"], // 3100-312F-bopomofo (Hiragino Sans GB)
  [0x3130, 0x318F, "u-apple-sd-gothic-neo"], // 3130-318F-hangul-compatibility-jamo (Apple SD Gothic Neo)
  [0x3190, 0x319F, "u-arial-unicode-ms"], // 3190-319F-kanbun (Arial Unicode MS)
  [0x31A0, 0x31BF, "u-hiragino-sans-gb"], // 31A0-31BF-bopomofo-extended (Hiragino Sans GB)
  [0x31C0, 0x31EF, "u-noto-sans-kr"], // 31C0-31EF-cjk-strokes (Noto Sans KR)
  [0x31F0, 0x31FF, "u-hiragino-sans"], // 31F0-31FF-katakana-phonetic-extensions (Hiragino Sans)
  [0x3200, 0x32FF, "u-apple-sd-gothic-neo"], // 3200-32FF-enclosed-cjk-letters-and-months (Apple SD Gothic Neo)
  [0x3300, 0x33FF, "u-hiragino-sans"], // 3300-33FF-cjk-compatibility (Hiragino Sans)
  [0x3400, 0x4DBF, "u-hiragino-sans-gb"], // 3400-4DBF-cjk-unified-ideographs-extension-a (Hiragino Sans GB)
  [0x4DC0, 0x4DFF, "u-apple-symbols"], // 4DC0-4DFF-yijing-hexagram-symbols (Apple Symbols)
  [0x4E00, 0x9FFF, "u-hiragino-sans-gb"], // 4E00-9FFF-cjk-unified-ideographs (Hiragino Sans GB)
  [0xA000, 0xA48F, "u-noto-sans-yi"], // A000-A48F-yi-syllables (Noto Sans Yi)
  [0xA490, 0xA4CF, "u-noto-sans-yi"], // A490-A4CF-yi-radicals (Noto Sans Yi)
  [0xA4D0, 0xA4FF, "u-noto-sans-lisu"], // A4D0-A4FF-lisu (Noto Sans Lisu)
  [0xA500, 0xA63F, "u-noto-sans-vai"], // A500-A63F-vai (Noto Sans Vai)
  [0xA640, 0xA69F, "u-noto-sans"], // A640-A69F-cyrillic-extended-b (Noto Sans)
  [0xA6A0, 0xA6FF, "u-noto-sans-bamum"], // A6A0-A6FF-bamum (Noto Sans Bamum)
  [0xA700, 0xA71F, "u-helvetica-neue"], // A700-A71F-modifier-tone-letters (Helvetica Neue)
  [0xA720, 0xA7FF, "u-helvetica-neue"], // A720-A7FF-latin-extended-d (Helvetica Neue)
  [0xA800, 0xA82F, "u-noto-sans-syloti-nagri"], // A800-A82F-syloti-nagri (Noto Sans Syloti Nagri)
  [0xA830, 0xA83F, "u-muktamahee-regular"], // A830-A83F-common-indic-number-forms (MuktaMahee Regular)
  [0xA840, 0xA87F, "u-noto-sans-phagspa"], // A840-A87F-phags-pa (Noto Sans PhagsPa)
  [0xA880, 0xA8DF, "u-noto-sans-saurashtra"], // A880-A8DF-saurashtra (Noto Sans Saurashtra)
  [0xA900, 0xA92F, "u-noto-sans-kayah-li"], // A900-A92F-kayah-li (Noto Sans Kayah Li)
  [0xA930, 0xA95F, "u-noto-sans-rejang"], // A930-A95F-rejang (Noto Sans Rejang)
  [0xA960, 0xA97F, "u-noto-sans-kr"], // A960-A97F-hangul-jamo-extended-a (Noto Sans KR)
  [0xA980, 0xA9DF, "u-noto-sans-javanese"], // A980-A9DF-javanese (Noto Sans Javanese)
  [0xA9E0, 0xA9FF, "u-noto-sans-myanmar"], // A9E0-A9FF-myanmar-extended-b (Noto Sans Myanmar)
  [0xAA00, 0xAA5F, "u-noto-sans-cham"], // AA00-AA5F-cham (Noto Sans Cham)
  [0xAA60, 0xAA7F, "u-noto-sans-myanmar"], // AA60-AA7F-myanmar-extended-a (Noto Sans Myanmar)
  [0xAA80, 0xAADF, "u-noto-sans-tai-viet"], // AA80-AADF-tai-viet (Noto Sans Tai Viet)
  [0xAAE0, 0xAAFF, "u-noto-sans-meeteimayek"], // AAE0-AAFF-meetei-mayek-extensions (Noto Sans MeeteiMayek)
  [0xAB00, 0xAB2F, "u-kefa-iii"], // AB00-AB2F-ethiopic-extended-a (Kefa III)
  [0xAB30, 0xAB6F, "u-noto-sans"], // AB30-AB6F-latin-extended-e (Noto Sans)
  [0xAB70, 0xABBF, "u-galvji"], // AB70-ABBF-cherokee-supplement (Galvji)
  [0xABC0, 0xABFF, "u-noto-sans-meeteimayek"], // ABC0-ABFF-meetei-mayek (Noto Sans MeeteiMayek)
  [0xAC00, 0xD7AF, "u-apple-sd-gothic-neo"], // AC00-D7AF-hangul-syllables (Apple SD Gothic Neo)
  [0xD7B0, 0xD7FF, "u-noto-sans-kr"], // D7B0-D7FF-hangul-jamo-extended-b (Noto Sans KR)
  [0xF900, 0xFAFF, "u-heiti-sc"], // F900-FAFF-cjk-compatibility-ideographs (Heiti SC)
  [0xFB00, 0xFB4F, "u-helvetica-neue"], // FB00-FB4F-alphabetic-presentation-forms (Helvetica Neue)
  [0xFB50, 0xFDFF, "u-geeza-pro"], // FB50-FDFF-arabic-presentation-forms-a (Geeza Pro)
  [0xFE00, 0xFE0F, "u-noto-sans"], // FE00-FE0F-variation-selectors (Noto Sans)
  [0xFE20, 0xFE2F, "u-arial"], // FE20-FE2F-combining-half-marks (Arial)
  [0xFE30, 0xFE4F, "u-arial-unicode-ms"], // FE30-FE4F-cjk-compatibility-forms (Arial Unicode MS)
  [0xFE50, 0xFE6F, "u-apple-symbols"], // FE50-FE6F-small-form-variants (Apple Symbols)
  [0xFE70, 0xFEFF, "u-geeza-pro"], // FE70-FEFF-arabic-presentation-forms-b (Geeza Pro)
  [0xFF00, 0xFFEF, "u-apple-symbols"], // FF00-FFEF-halfwidth-and-fullwidth-forms (Apple Symbols)
  [0xFFF0, 0xFFFF, "u-arial"], // FFF0-FFFF-specials (Arial)
  [0x10000, 0x1007F, "u-noto-sans-linear-b"], // 10000-1007F-linear-b-syllabary (Noto Sans Linear B)
  [0x10080, 0x100FF, "u-noto-sans-linear-b"], // 10080-100FF-linear-b-ideograms (Noto Sans Linear B)
  [0x10100, 0x1013F, "u-apple-symbols"], // 10100-1013F-aegean-numbers (Apple Symbols)
  [0x10140, 0x1018F, "u-apple-symbols"], // 10140-1018F-ancient-greek-numbers (Apple Symbols)
  [0x10190, 0x101CF, "u-big-caslon"], // 10190-101CF-ancient-symbols (Big Caslon)
  [0x101D0, 0x101FF, "u-arial-unicode-ms"], // 101D0-101FF-phaistos-disc (Arial Unicode MS)
  [0x10280, 0x1029F, "u-noto-sans-lycian"], // 10280-1029F-lycian (Noto Sans Lycian)
  [0x102A0, 0x102DF, "u-noto-sans-carian"], // 102A0-102DF-carian (Noto Sans Carian)
  [0x102E0, 0x102FF, "u-noto-sans-coptic"], // 102E0-102FF-coptic-epact-numbers (Noto Sans Coptic)
  [0x10300, 0x1032F, "u-noto-sans-old-italic"], // 10300-1032F-old-italic (Noto Sans Old Italic)
  [0x10330, 0x1034F, "u-noto-sans-gothic"], // 10330-1034F-gothic (Noto Sans Gothic)
  [0x10350, 0x1037F, "u-noto-sans-old-permic"], // 10350-1037F-old-permic (Noto Sans Old Permic)
  [0x10380, 0x1039F, "u-noto-sans-ugaritic"], // 10380-1039F-ugaritic (Noto Sans Ugaritic)
  [0x103A0, 0x103DF, "u-noto-sans-oldpersian"], // 103A0-103DF-old-persian (Noto Sans OldPersian)
  [0x10400, 0x1044F, "u-apple-symbols"], // 10400-1044F-deseret (Apple Symbols)
  [0x10450, 0x1047F, "u-apple-symbols"], // 10450-1047F-shavian (Apple Symbols)
  [0x10480, 0x104AF, "u-noto-sans-osmanya"], // 10480-104AF-osmanya (Noto Sans Osmanya)
  [0x104B0, 0x104FF, "u-noto-sans-osage"], // 104B0-104FF-osage (Noto Sans Osage)
  [0x10500, 0x1052F, "u-noto-sans-elbasan"], // 10500-1052F-elbasan (Noto Sans Elbasan)
  [0x10530, 0x1056F, "u-noto-sans-caucalban"], // 10530-1056F-caucasian-albanian (Noto Sans CaucAlban)
  [0x10570, 0x105BF, "u-arial-unicode-ms"], // 10570-105BF-vithkuqi (Arial Unicode MS)
  [0x105C0, 0x105FF, "u-arial-unicode-ms"], // 105C0-105FF-todhri (Arial Unicode MS)
  [0x10600, 0x1077F, "u-noto-sans-linear-a"], // 10600-1077F-linear-a (Noto Sans Linear A)
  [0x10780, 0x107BF, "u-noto-sans"], // 10780-107BF-latin-extended-f (Noto Sans)
  [0x10800, 0x1083F, "u-noto-sans-cypriot"], // 10800-1083F-cypriot-syllabary (Noto Sans Cypriot)
  [0x10840, 0x1085F, "u-noto-sans-imparamaic"], // 10840-1085F-imperial-aramaic (Noto Sans ImpAramaic)
  [0x10860, 0x1087F, "u-noto-sans-palmyrene"], // 10860-1087F-palmyrene (Noto Sans Palmyrene)
  [0x10880, 0x108AF, "u-noto-sans-nabataean"], // 10880-108AF-nabataean (Noto Sans Nabataean)
  [0x108E0, 0x108FF, "u-noto-sans-hatran"], // 108E0-108FF-hatran (Noto Sans Hatran)
  [0x10900, 0x1091F, "u-noto-sans-phoenician"], // 10900-1091F-phoenician (Noto Sans Phoenician)
  [0x10920, 0x1093F, "u-noto-sans-lydian"], // 10920-1093F-lydian (Noto Sans Lydian)
  [0x10980, 0x1099F, "u-noto-sans-meroitic"], // 10980-1099F-meroitic-hieroglyphs (Noto Sans Meroitic)
  [0x109A0, 0x109FF, "u-noto-sans-meroitic"], // 109A0-109FF-meroitic-cursive (Noto Sans Meroitic)
  [0x10A00, 0x10A5F, "u-noto-sans-kharoshthi"], // 10A00-10A5F-kharoshthi (Noto Sans Kharoshthi)
  [0x10A60, 0x10A7F, "u-noto-sans-oldsouarab"], // 10A60-10A7F-old-south-arabian (Noto Sans OldSouArab)
  [0x10A80, 0x10A9F, "u-noto-sans-oldnorarab"], // 10A80-10A9F-old-north-arabian (Noto Sans OldNorArab)
  [0x10AC0, 0x10AFF, "u-noto-sans-manichaean"], // 10AC0-10AFF-manichaean (Noto Sans Manichaean)
  [0x10B00, 0x10B3F, "u-noto-sans-avestan"], // 10B00-10B3F-avestan (Noto Sans Avestan)
  [0x10B40, 0x10B5F, "u-noto-sans-insparthi"], // 10B40-10B5F-inscriptional-parthian (Noto Sans InsParthi)
  [0x10B60, 0x10B7F, "u-noto-sans-inspahlavi"], // 10B60-10B7F-inscriptional-pahlavi (Noto Sans InsPahlavi)
  [0x10B80, 0x10BAF, "u-noto-sans-psapahlavi"], // 10B80-10BAF-psalter-pahlavi (Noto Sans PsaPahlavi)
  [0x10C00, 0x10C4F, "u-noto-sans-old-turkic"], // 10C00-10C4F-old-turkic (Noto Sans Old Turkic)
  [0x10C80, 0x10CFF, "u-noto-sans-oldhung"], // 10C80-10CFF-old-hungarian (Noto Sans OldHung)
  [0x10D00, 0x10D3F, "u-noto-sans-hanifirohg"], // 10D00-10D3F-hanifi-rohingya (Noto Sans HanifiRohg)
  [0x10D40, 0x10D8F, "u-arial-unicode-ms"], // 10D40-10D8F-garay (Arial Unicode MS)
  [0x10E60, 0x10E7F, "u-arial-unicode-ms"], // 10E60-10E7F-rumi-numeral-symbols (Arial Unicode MS)
  [0x10E80, 0x10EBF, "u-noto-serif-yezidi"], // 10E80-10EBF-yezidi (Noto Serif Yezidi)
  [0x10EC0, 0x10EFF, "u-arial-unicode-ms"], // 10EC0-10EFF-arabic-extended-c (Arial Unicode MS)
  [0x10F00, 0x10F2F, "u-arial-unicode-ms"], // 10F00-10F2F-old-sogdian (Arial Unicode MS)
  [0x10F30, 0x10F6F, "u-arial-unicode-ms"], // 10F30-10F6F-sogdian (Arial Unicode MS)
  [0x10F70, 0x10FAF, "u-arial-unicode-ms"], // 10F70-10FAF-old-uyghur (Arial Unicode MS)
  [0x10FB0, 0x10FDF, "u-arial-unicode-ms"], // 10FB0-10FDF-chorasmian (Arial Unicode MS)
  [0x10FE0, 0x10FFF, "u-arial-unicode-ms"], // 10FE0-10FFF-elymaic (Arial Unicode MS)
  [0x11000, 0x1107F, "u-noto-sans-brahmi"], // 11000-1107F-brahmi (Noto Sans Brahmi)
  [0x11080, 0x110CF, "u-noto-sans-kaithi"], // 11080-110CF-kaithi (Noto Sans Kaithi)
  [0x110D0, 0x110FF, "u-noto-sans-sorasomp"], // 110D0-110FF-sora-sompeng (Noto Sans SoraSomp)
  [0x11100, 0x1114F, "u-noto-sans-chakma"], // 11100-1114F-chakma (Noto Sans Chakma)
  [0x11150, 0x1117F, "u-noto-sans-mahajani"], // 11150-1117F-mahajani (Noto Sans Mahajani)
  [0x11180, 0x111DF, "u-noto-sans-sharada"], // 11180-111DF-sharada (Noto Sans Sharada)
  [0x111E0, 0x111FF, "u-arial-unicode-ms"], // 111E0-111FF-sinhala-archaic-numbers (Arial Unicode MS)
  [0x11200, 0x1124F, "u-noto-sans-khojki"], // 11200-1124F-khojki (Noto Sans Khojki)
  [0x11280, 0x112AF, "u-noto-sans-multani"], // 11280-112AF-multani (Noto Sans Multani)
  [0x112B0, 0x112FF, "u-noto-sans-khudawadi"], // 112B0-112FF-khudawadi (Noto Sans Khudawadi)
  [0x11300, 0x1137F, "u-grantha-sangam-mn"], // 11300-1137F-grantha (Grantha Sangam MN)
  [0x11380, 0x113FF, "u-arial-unicode-ms"], // 11380-113FF-tulu-tigalari (Arial Unicode MS)
  [0x11400, 0x1147F, "u-noto-sans-newa"], // 11400-1147F-newa (Noto Sans Newa)
  [0x11480, 0x114DF, "u-noto-sans-tirhuta"], // 11480-114DF-tirhuta (Noto Sans Tirhuta)
  [0x11580, 0x115FF, "u-noto-sans-siddham"], // 11580-115FF-siddham (Noto Sans Siddham)
  [0x11600, 0x1165F, "u-noto-sans-modi"], // 11600-1165F-modi (Noto Sans Modi)
  [0x11660, 0x1167F, "u-noto-sans-mongolian"], // 11660-1167F-mongolian-supplement (Noto Sans Mongolian)
  [0x11680, 0x116CF, "u-noto-sans-takri"], // 11680-116CF-takri (Noto Sans Takri)
  [0x116D0, 0x116FF, "u-arial-unicode-ms"], // 116D0-116FF-myanmar-extended-c (Arial Unicode MS)
  [0x11700, 0x1174F, "u-noto-serif-ahom"], // 11700-1174F-ahom (Noto Serif Ahom)
  [0x11800, 0x1184F, "u-arial-unicode-ms"], // 11800-1184F-dogra (Arial Unicode MS)
  [0x118A0, 0x118FF, "u-noto-sans-warangciti"], // 118A0-118FF-warang-citi (Noto Sans WarangCiti)
  [0x11900, 0x1195F, "u-arial-unicode-ms"], // 11900-1195F-dives-akuru (Arial Unicode MS)
  [0x119A0, 0x119FF, "u-arial-unicode-ms"], // 119A0-119FF-nandinagari (Arial Unicode MS)
  [0x11A00, 0x11A4F, "u-arial-unicode-ms"], // 11A00-11A4F-zanabazar-square (Arial Unicode MS)
  [0x11A50, 0x11AAF, "u-arial-unicode-ms"], // 11A50-11AAF-soyombo (Arial Unicode MS)
  [0x11AB0, 0x11ABF, "u-euphemia-ucas"], // 11AB0-11ABF-unified-canadian-aboriginal-syllabics-extended-a (Euphemia UCAS)
  [0x11AC0, 0x11AFF, "u-noto-sans-paucinhau"], // 11AC0-11AFF-pau-cin-hau (Noto Sans PauCinHau)
  [0x11B00, 0x11B5F, "u-arial-unicode-ms"], // 11B00-11B5F-devanagari-extended-a (Arial Unicode MS)
  [0x11BC0, 0x11BFF, "u-arial-unicode-ms"], // 11BC0-11BFF-sunuwar (Arial Unicode MS)
  [0x11C00, 0x11C6F, "u-noto-sans-bhaiksuki"], // 11C00-11C6F-bhaiksuki (Noto Sans Bhaiksuki)
  [0x11C70, 0x11CBF, "u-noto-sans-marchen"], // 11C70-11CBF-marchen (Noto Sans Marchen)
  [0x11D00, 0x11D5F, "u-noto-sans-masaram-gondi"], // 11D00-11D5F-masaram-gondi (Noto Sans Masaram Gondi)
  [0x11D60, 0x11DAF, "u-noto-sans-gunjala-gondi"], // 11D60-11DAF-gunjala-gondi (Noto Sans Gunjala Gondi)
  [0x11EE0, 0x11EFF, "u-arial-unicode-ms"], // 11EE0-11EFF-makasar (Arial Unicode MS)
  [0x11F00, 0x11F5F, "u-arial-unicode-ms"], // 11F00-11F5F-kawi (Arial Unicode MS)
  [0x11FB0, 0x11FBF, "u-arial-unicode-ms"], // 11FB0-11FBF-lisu-supplement (Arial Unicode MS)
  [0x11FC0, 0x11FFF, "u-tamil-sangam-mn"], // 11FC0-11FFF-tamil-supplement (Tamil Sangam MN)
  [0x12000, 0x123FF, "u-noto-sans-cuneiform"], // 12000-123FF-cuneiform (Noto Sans Cuneiform)
  [0x12400, 0x1247F, "u-noto-sans-cuneiform"], // 12400-1247F-cuneiform-numbers-and-punctuation (Noto Sans Cuneiform)
  [0x12480, 0x1254F, "u-noto-sans-cuneiform"], // 12480-1254F-early-dynastic-cuneiform (Noto Sans Cuneiform)
  [0x12F90, 0x12FFF, "u-arial-unicode-ms"], // 12F90-12FFF-cypro-minoan (Arial Unicode MS)
  [0x13000, 0x1342F, "u-noto-sans-egypthiero"], // 13000-1342F-egyptian-hieroglyphs (Noto Sans EgyptHiero)
  [0x13430, 0x1345F, "u-arial-unicode-ms"], // 13430-1345F-egyptian-hieroglyph-format-controls (Arial Unicode MS)
  [0x13460, 0x143FF, "u-arial-unicode-ms"], // 13460-143FF-egyptian-hieroglyphs-extended-a (Arial Unicode MS)
  [0x14400, 0x1467F, "u-arial-unicode-ms"], // 14400-1467F-anatolian-hieroglyphs (Arial Unicode MS)
  [0x16100, 0x1613F, "u-arial-unicode-ms"], // 16100-1613F-gurung-khema (Arial Unicode MS)
  [0x16800, 0x16A3F, "u-noto-sans-bamum"], // 16800-16A3F-bamum-supplement (Noto Sans Bamum)
  [0x16A40, 0x16A6F, "u-noto-sans-mro"], // 16A40-16A6F-mro (Noto Sans Mro)
  [0x16A70, 0x16ACF, "u-arial-unicode-ms"], // 16A70-16ACF-tangsa (Arial Unicode MS)
  [0x16AD0, 0x16AFF, "u-noto-sans-bassa-vah"], // 16AD0-16AFF-bassa-vah (Noto Sans Bassa Vah)
  [0x16B00, 0x16B8F, "u-noto-sans-pahawh-hmong"], // 16B00-16B8F-pahawh-hmong (Noto Sans Pahawh Hmong)
  [0x16D40, 0x16D7F, "u-arial-unicode-ms"], // 16D40-16D7F-kirat-rai (Arial Unicode MS)
  [0x16E40, 0x16E9F, "u-arial-unicode-ms"], // 16E40-16E9F-medefaidrin (Arial Unicode MS)
  [0x16F00, 0x16F9F, "u-noto-sans-miao"], // 16F00-16F9F-miao (Noto Sans Miao)
  [0x16FE0, 0x16FFF, "u-arial-unicode-ms"], // 16FE0-16FFF-ideographic-symbols-and-punctuation (Arial Unicode MS)
  [0x17000, 0x187FF, "u-arial-unicode-ms"], // 17000-187FF-tangut (Arial Unicode MS)
  [0x18800, 0x18AFF, "u-arial-unicode-ms"], // 18800-18AFF-tangut-components (Arial Unicode MS)
  [0x18B00, 0x18CFF, "u-arial-unicode-ms"], // 18B00-18CFF-khitan-small-script (Arial Unicode MS)
  [0x18D00, 0x18D7F, "u-arial-unicode-ms"], // 18D00-18D7F-tangut-supplement (Arial Unicode MS)
  [0x1AFF0, 0x1AFFF, "u-arial-unicode-ms"], // 1AFF0-1AFFF-kana-extended-b (Arial Unicode MS)
  [0x1B100, 0x1B12F, "u-arial-unicode-ms"], // 1B100-1B12F-kana-extended-a (Arial Unicode MS)
  [0x1B130, 0x1B16F, "u-arial-unicode-ms"], // 1B130-1B16F-small-kana-extension (Arial Unicode MS)
  [0x1B170, 0x1B2FF, "u-arial-unicode-ms"], // 1B170-1B2FF-nushu (Arial Unicode MS)
  [0x1BC00, 0x1BC9F, "u-noto-sans-duployan"], // 1BC00-1BC9F-duployan (Noto Sans Duployan)
  [0x1CC00, 0x1CEBF, "u-arial-unicode-ms"], // 1CC00-1CEBF-symbols-for-legacy-computing-supplement (Arial Unicode MS)
  [0x1CF00, 0x1CFCF, "u-arial-unicode-ms"], // 1CF00-1CFCF-znamenny-musical-notation (Arial Unicode MS)
  [0x1D000, 0x1D0FF, "u-arial-unicode-ms"], // 1D000-1D0FF-byzantine-musical-symbols (Arial Unicode MS)
  [0x1D100, 0x1D1FF, "u-apple-symbols"], // 1D100-1D1FF-musical-symbols (Apple Symbols)
  [0x1D200, 0x1D24F, "u-arial-unicode-ms"], // 1D200-1D24F-ancient-greek-musical-notation (Arial Unicode MS)
  [0x1D2C0, 0x1D2DF, "u-arial-unicode-ms"], // 1D2C0-1D2DF-kaktovik-numerals (Arial Unicode MS)
  [0x1D2E0, 0x1D2FF, "u-arial-unicode-ms"], // 1D2E0-1D2FF-mayan-numerals (Arial Unicode MS)
  [0x1D300, 0x1D35F, "u-apple-symbols"], // 1D300-1D35F-tai-xuan-jing-symbols (Apple Symbols)
  [0x1D360, 0x1D37F, "u-apple-symbols"], // 1D360-1D37F-counting-rod-numerals (Apple Symbols)
  [0x1D400, 0x1D7FF, "u-stix-two-math"], // 1D400-1D7FF-mathematical-alphanumeric-symbols (STIX Two Math)
  [0x1D800, 0x1DAAF, "u-sf-compact"], // 1D800-1DAAF-sutton-signwriting (SF Compact)
  [0x1DF00, 0x1DFFF, "u-noto-sans"], // 1DF00-1DFFF-latin-extended-g (Noto Sans)
  [0x1E000, 0x1E02F, "u-noto-sans-glagolitic"], // 1E000-1E02F-glagolitic-supplement (Noto Sans Glagolitic)
  [0x1E030, 0x1E08F, "u-arial-unicode-ms"], // 1E030-1E08F-cyrillic-extended-d (Arial Unicode MS)
  [0x1E100, 0x1E14F, "u-noto-serif-hmong-nyiakeng"], // 1E100-1E14F-nyiakeng-puachue-hmong (Noto Serif Hmong Nyiakeng)
  [0x1E290, 0x1E2BF, "u-arial-unicode-ms"], // 1E290-1E2BF-toto (Arial Unicode MS)
  [0x1E2C0, 0x1E2FF, "u-noto-sans-wancho"], // 1E2C0-1E2FF-wancho (Noto Sans Wancho)
  [0x1E4D0, 0x1E4FF, "u-noto-sans-nag-mundari"], // 1E4D0-1E4FF-nag-mundari (Noto Sans Nag Mundari)
  [0x1E5D0, 0x1E5FF, "u-arial-unicode-ms"], // 1E5D0-1E5FF-ol-onal (Arial Unicode MS)
  [0x1E7E0, 0x1E7FF, "u-arial-unicode-ms"], // 1E7E0-1E7FF-ethiopic-extended-b (Arial Unicode MS)
  [0x1E800, 0x1E8DF, "u-noto-sans-mende-kikakui"], // 1E800-1E8DF-mende-kikakui (Noto Sans Mende Kikakui)
  [0x1E900, 0x1E95F, "u-noto-sans-adlam"], // 1E900-1E95F-adlam (Noto Sans Adlam)
  [0x1EC70, 0x1ECBF, "u-arial-unicode-ms"], // 1EC70-1ECBF-indic-siyaq-numbers (Arial Unicode MS)
  [0x1ED00, 0x1ED4F, "u-arial-unicode-ms"], // 1ED00-1ED4F-ottoman-siyaq-numbers (Arial Unicode MS)
  [0x1EE00, 0x1EEFF, "u-stix-two-math"], // 1EE00-1EEFF-arabic-mathematical-alphabetic-symbols (STIX Two Math)
  [0x1F000, 0x1F02F, "u-apple-symbols"], // 1F000-1F02F-mahjong-tiles (Apple Symbols)
  [0x1F030, 0x1F09F, "u-apple-symbols"], // 1F030-1F09F-domino-tiles (Apple Symbols)
  [0x1F0A0, 0x1F0FF, "u-apple-symbols"], // 1F0A0-1F0FF-playing-cards (Apple Symbols)
  [0x1F100, 0x1F1FF, "u-hiragino-kaku-gothic-pron"], // 1F100-1F1FF-enclosed-alphanumeric-supplement (Hiragino Kaku Gothic ProN)
  [0x1F200, 0x1F2FF, "u-noto-sans-kr"], // 1F200-1F2FF-enclosed-ideographic-supplement (Noto Sans KR)
  [0x1F650, 0x1F67F, "u-arial-unicode-ms"], // 1F650-1F67F-ornamental-dingbats (Arial Unicode MS)
  [0x1F700, 0x1F77F, "u-apple-symbols"], // 1F700-1F77F-alchemical-symbols (Apple Symbols)
  [0x1FA00, 0x1FA6F, "u-arial-unicode-ms"], // 1FA00-1FA6F-chess-symbols (Arial Unicode MS)
  [0x1FB00, 0x1FBFF, "u-arial-unicode-ms"], // 1FB00-1FBFF-symbols-for-legacy-computing (Arial Unicode MS)
  [0x20000, 0x2A6DF, "u-heiti-sc"], // 20000-2A6DF-cjk-unified-ideographs-extension-b (Heiti SC)
  [0x2A700, 0x2B73F, "u-hiragino-sans-gb"], // 2A700-2B73F-cjk-unified-ideographs-extension-c (Hiragino Sans GB)
  [0x2B740, 0x2B81F, "u-hiragino-sans"], // 2B740-2B81F-cjk-unified-ideographs-extension-d (Hiragino Sans)
  [0x2B820, 0x2CEAF, "u-hiragino-sans-gb"], // 2B820-2CEAF-cjk-unified-ideographs-extension-e (Hiragino Sans GB)
  [0x2CEB0, 0x2EBEF, "u-hiragino-sans"], // 2CEB0-2EBEF-cjk-unified-ideographs-extension-f (Hiragino Sans)
  [0x2EBF0, 0x2EE5F, "u-arial-unicode-ms"], // 2EBF0-2EE5F-cjk-unified-ideographs-extension-i (Arial Unicode MS)
  [0x2F800, 0x2FA1F, "u-arial-unicode-ms"], // 2F800-2FA1F-cjk-compatibility-ideographs-supplement (Arial Unicode MS)
  [0x30000, 0x3134F, "u-noto-sans-kr"], // 30000-3134F-cjk-unified-ideographs-extension-g (Noto Sans KR)
  [0x31350, 0x323AF, "u-arial-unicode-ms"], // 31350-323AF-cjk-unified-ideographs-extension-h (Arial Unicode MS)
  [0xE0100, 0xE01EF, "u-arial-unicode-ms"], // E0100-E01EF-variation-selectors-supplement (Arial Unicode MS)
];
