// AUTO-GENERATED by tools/probe-983-genroutes-noto-linux.mjs — do not edit by hand.
// Desktop-Linux **Noto profile** per-Unicode-block fallback routing (DM-1404).
// Source data: tests/output/unicode-fonts.noto-linux.json + family-to-path.noto-linux.json,
// produced by tools/calibrate-linux-noto-profile.sh inside the Playwright *-noble
// container with the noble-only fallback fonts stripped and the mainstream Noto set
// installed, so Chromium's fontconfig picks match a real desktop-Linux host.
// Selected at runtime by `linuxFontProfile() === 'noto'`; keys namespaced `un-...`.

export interface UnicodeFontEntry { path: string; postscriptName?: string; extractor?: "fontkit" | "native" }

export const UNICODE_FONT_PATHS_NOTO_LINUX: Record<string, UnicodeFontEntry> = {
  "un-liberation-sans": { path: "/usr/share/fonts/truetype/liberation/LiberationSans-Regular.ttf", postscriptName: "LiberationSans" },
  "un-noto-kufi-arabic": { path: "/usr/share/fonts/truetype/noto/NotoKufiArabic-Regular.ttf", postscriptName: "NotoKufiArabic-Regular" },
  "un-noto-music": { path: "/usr/share/fonts/truetype/noto/NotoMusic-Regular.ttf", postscriptName: "NotoMusic-Regular" },
  "un-noto-naskh-arabic-ui": { path: "/usr/share/fonts/truetype/noto/NotoNaskhArabicUI-Regular.ttf", postscriptName: "NotoNaskhArabicUI-Regular" },
  "un-noto-sans": { path: "/usr/share/fonts/truetype/noto/NotoSans-Regular.ttf", postscriptName: "NotoSans-Regular" },
  "un-noto-sans-adlam": { path: "/usr/share/fonts/truetype/noto/NotoSansAdlam-Regular.ttf", postscriptName: "NotoSansAdlam-Regular" },
  "un-noto-sans-anatohiero": { path: "/usr/share/fonts/truetype/noto/NotoSansAnatolianHieroglyphs-Regular.ttf", postscriptName: "NotoSansAnatolianHieroglyphs-Regular" },
  "un-noto-sans-armenian": { path: "/usr/share/fonts/truetype/noto/NotoSansArmenian-Regular.ttf", postscriptName: "NotoSansArmenian-Regular" },
  "un-noto-sans-avestan": { path: "/usr/share/fonts/truetype/noto/NotoSansAvestan-Regular.ttf", postscriptName: "NotoSansAvestan-Regular" },
  "un-noto-sans-bamum": { path: "/usr/share/fonts/truetype/noto/NotoSansBamum-Regular.ttf", postscriptName: "NotoSansBamum-Regular" },
  "un-noto-sans-bassa-vah": { path: "/usr/share/fonts/truetype/noto/NotoSansBassaVah-Regular.ttf", postscriptName: "NotoSansBassaVah-Regular" },
  "un-noto-sans-batak": { path: "/usr/share/fonts/truetype/noto/NotoSansBatak-Regular.ttf", postscriptName: "NotoSansBatak-Regular" },
  "un-noto-sans-bengali": { path: "/usr/share/fonts/truetype/noto/NotoSansBengali-Regular.ttf", postscriptName: "NotoSansBengali-Regular" },
  "un-noto-sans-bhaiksuki": { path: "/usr/share/fonts/truetype/noto/NotoSansBhaiksuki-Regular.ttf", postscriptName: "NotoSansBhaiksuki-Regular" },
  "un-noto-sans-brahmi": { path: "/usr/share/fonts/truetype/noto/NotoSansBrahmi-Regular.ttf", postscriptName: "NotoSansBrahmi-Regular" },
  "un-noto-sans-buginese": { path: "/usr/share/fonts/truetype/noto/NotoSansBuginese-Regular.ttf", postscriptName: "NotoSansBuginese-Regular" },
  "un-noto-sans-buhid": { path: "/usr/share/fonts/truetype/noto/NotoSansBuhid-Regular.ttf", postscriptName: "NotoSansBuhid-Regular" },
  "un-noto-sans-canaborig": { path: "/usr/share/fonts/truetype/noto/NotoSansCanadianAboriginal-Regular.ttf", postscriptName: "NotoSansCanadianAboriginal-Regular" },
  "un-noto-sans-carian": { path: "/usr/share/fonts/truetype/noto/NotoSansCarian-Regular.ttf", postscriptName: "NotoSansCarian-Regular" },
  "un-noto-sans-caucalban": { path: "/usr/share/fonts/truetype/noto/NotoSansCaucasianAlbanian-Regular.ttf", postscriptName: "NotoSansCaucasianAlbanian-Regular" },
  "un-noto-sans-chakma": { path: "/usr/share/fonts/truetype/noto/NotoSansChakma-Regular.ttf", postscriptName: "NotoSansChakma-Regular" },
  "un-noto-sans-cham": { path: "/usr/share/fonts/truetype/noto/NotoSansCham-Regular.ttf", postscriptName: "NotoSansCham-Regular" },
  "un-noto-sans-cherokee": { path: "/usr/share/fonts/truetype/noto/NotoSansCherokee-Regular.ttf", postscriptName: "NotoSansCherokee-Regular" },
  "un-noto-sans-cjk-jp": { path: "/usr/share/fonts/opentype/noto/NotoSansCJK-Regular.ttc", postscriptName: "NotoSansCJKjp-Regular" },
  "un-noto-sans-coptic": { path: "/usr/share/fonts/truetype/noto/NotoSansCoptic-Regular.ttf", postscriptName: "NotoSansCoptic-Regular" },
  "un-noto-sans-cuneiform": { path: "/usr/share/fonts/truetype/noto/NotoSansCuneiform-Regular.ttf", postscriptName: "NotoSansCuneiform-Regular" },
  "un-noto-sans-cypriot": { path: "/usr/share/fonts/truetype/noto/NotoSansCypriot-Regular.ttf", postscriptName: "NotoSansCypriot-Regular" },
  "un-noto-sans-deseret": { path: "/usr/share/fonts/truetype/noto/NotoSansDeseret-Regular.ttf", postscriptName: "NotoSansDeseret-Regular" },
  "un-noto-sans-devanagari": { path: "/usr/share/fonts/truetype/noto/NotoSansDevanagari-Regular.ttf", postscriptName: "NotoSansDevanagari-Regular" },
  "un-noto-sans-duployan": { path: "/usr/share/fonts/truetype/noto/NotoSansDuployan-Regular.ttf", postscriptName: "NotoSansDuployan-Regular" },
  "un-noto-sans-egypthiero": { path: "/usr/share/fonts/truetype/noto/NotoSansEgyptianHieroglyphs-Regular.ttf", postscriptName: "NotoSansEgyptianHieroglyphs-Regular" },
  "un-noto-sans-elbasan": { path: "/usr/share/fonts/truetype/noto/NotoSansElbasan-Regular.ttf", postscriptName: "NotoSansElbasan-Regular" },
  "un-noto-sans-elymaic": { path: "/usr/share/fonts/truetype/noto/NotoSansElymaic-Regular.ttf", postscriptName: "NotoSansElymaic-Regular" },
  "un-noto-sans-ethiopic": { path: "/usr/share/fonts/truetype/noto/NotoSansEthiopic-Regular.ttf", postscriptName: "NotoSansEthiopic-Regular" },
  "un-noto-sans-georgian": { path: "/usr/share/fonts/truetype/noto/NotoSansGeorgian-Regular.ttf", postscriptName: "NotoSansGeorgian-Regular" },
  "un-noto-sans-glagolitic": { path: "/usr/share/fonts/truetype/noto/NotoSansGlagolitic-Regular.ttf", postscriptName: "NotoSansGlagolitic-Regular" },
  "un-noto-sans-gothic": { path: "/usr/share/fonts/truetype/noto/NotoSansGothic-Regular.ttf", postscriptName: "NotoSansGothic-Regular" },
  "un-noto-sans-grantha": { path: "/usr/share/fonts/truetype/noto/NotoSansGrantha-Regular.ttf", postscriptName: "NotoSansGrantha-Regular" },
  "un-noto-sans-gunjala-gondi": { path: "/usr/share/fonts/truetype/noto/NotoSansGunjalaGondi-Regular.ttf", postscriptName: "NotoSansGunjalaGondi-Regular" },
  "un-noto-sans-gurmukhi": { path: "/usr/share/fonts/truetype/noto/NotoSansGurmukhi-Regular.ttf", postscriptName: "NotoSansGurmukhi-Regular" },
  "un-noto-sans-hanifi-rohingya": { path: "/usr/share/fonts/truetype/noto/NotoSansHanifiRohingya-Regular.ttf", postscriptName: "NotoSansHanifiRohingya-Regular" },
  "un-noto-sans-hanunoo": { path: "/usr/share/fonts/truetype/noto/NotoSansHanunoo-Regular.ttf", postscriptName: "NotoSansHanunoo-Regular" },
  "un-noto-sans-hatran": { path: "/usr/share/fonts/truetype/noto/NotoSansHatran-Regular.ttf", postscriptName: "NotoSansHatran-Regular" },
  "un-noto-sans-imparamaic": { path: "/usr/share/fonts/truetype/noto/NotoSansImperialAramaic-Regular.ttf", postscriptName: "NotoSansImperialAramaic-Regular" },
  "un-noto-sans-indic-siyaq-numbers": { path: "/usr/share/fonts/truetype/noto/NotoSansIndicSiyaqNumbers-Regular.ttf", postscriptName: "NotoSansIndicSiyaqNumbers-Regular" },
  "un-noto-sans-inspahlavi": { path: "/usr/share/fonts/truetype/noto/NotoSansInscriptionalPahlavi-Regular.ttf", postscriptName: "NotoSansInscriptionalPahlavi-Regular" },
  "un-noto-sans-insparthi": { path: "/usr/share/fonts/truetype/noto/NotoSansInscriptionalParthian-Regular.ttf", postscriptName: "NotoSansInscriptionalParthian-Regular" },
  "un-noto-sans-javanese": { path: "/usr/share/fonts/truetype/noto/NotoSansJavanese-Regular.ttf", postscriptName: "NotoSansJavanese-Regular" },
  "un-noto-sans-kaithi": { path: "/usr/share/fonts/truetype/noto/NotoSansKaithi-Regular.ttf", postscriptName: "NotoSansKaithi-Regular" },
  "un-noto-sans-kayah-li": { path: "/usr/share/fonts/truetype/noto/NotoSansKayahLi-Regular.ttf", postscriptName: "NotoSansKayahLi-Regular" },
  "un-noto-sans-kharoshthi": { path: "/usr/share/fonts/truetype/noto/NotoSansKharoshthi-Regular.ttf", postscriptName: "NotoSansKharoshthi-Regular" },
  "un-noto-sans-khmer": { path: "/usr/share/fonts/truetype/noto/NotoSansKhmer-Regular.ttf", postscriptName: "NotoSansKhmer-Regular" },
  "un-noto-sans-khojki": { path: "/usr/share/fonts/truetype/noto/NotoSansKhojki-Regular.ttf", postscriptName: "NotoSansKhojki-Regular" },
  "un-noto-sans-khudawadi": { path: "/usr/share/fonts/truetype/noto/NotoSansKhudawadi-Regular.ttf", postscriptName: "NotoSansKhudawadi-Regular" },
  "un-noto-sans-lao": { path: "/usr/share/fonts/truetype/noto/NotoSansLao-Regular.ttf", postscriptName: "NotoSansLao-Regular" },
  "un-noto-sans-lepcha": { path: "/usr/share/fonts/truetype/noto/NotoSansLepcha-Regular.ttf", postscriptName: "NotoSansLepcha-Regular" },
  "un-noto-sans-limbu": { path: "/usr/share/fonts/truetype/noto/NotoSansLimbu-Regular.ttf", postscriptName: "NotoSansLimbu-Regular" },
  "un-noto-sans-linear-a": { path: "/usr/share/fonts/truetype/noto/NotoSansLinearA-Regular.ttf", postscriptName: "NotoSansLinearA-Regular" },
  "un-noto-sans-linear-b": { path: "/usr/share/fonts/truetype/noto/NotoSansLinearB-Regular.ttf", postscriptName: "NotoSansLinearB-Regular" },
  "un-noto-sans-lisu": { path: "/usr/share/fonts/truetype/noto/NotoSansLisu-Regular.ttf", postscriptName: "NotoSansLisu-Regular" },
  "un-noto-sans-lycian": { path: "/usr/share/fonts/truetype/noto/NotoSansLycian-Regular.ttf", postscriptName: "NotoSansLycian-Regular" },
  "un-noto-sans-lydian": { path: "/usr/share/fonts/truetype/noto/NotoSansLydian-Regular.ttf", postscriptName: "NotoSansLydian-Regular" },
  "un-noto-sans-mahajani": { path: "/usr/share/fonts/truetype/noto/NotoSansMahajani-Regular.ttf", postscriptName: "NotoSansMahajani-Regular" },
  "un-noto-sans-malayalam": { path: "/usr/share/fonts/truetype/noto/NotoSansMalayalam-Regular.ttf", postscriptName: "NotoSansMalayalam-Regular" },
  "un-noto-sans-mandaic": { path: "/usr/share/fonts/truetype/noto/NotoSansMandaic-Regular.ttf", postscriptName: "NotoSansMandaic-Regular" },
  "un-noto-sans-manichaean": { path: "/usr/share/fonts/truetype/noto/NotoSansManichaean-Regular.ttf", postscriptName: "NotoSansManichaean-Regular" },
  "un-noto-sans-marchen": { path: "/usr/share/fonts/truetype/noto/NotoSansMarchen-Regular.ttf", postscriptName: "NotoSansMarchen-Regular" },
  "un-noto-sans-masaram-gondi": { path: "/usr/share/fonts/truetype/noto/NotoSansMasaramGondi-Regular.ttf", postscriptName: "NotoSansMasaramGondi-Regular" },
  "un-noto-sans-math": { path: "/usr/share/fonts/truetype/noto/NotoSansMath-Regular.ttf", postscriptName: "NotoSansMath-Regular" },
  "un-noto-sans-medefaidrin": { path: "/usr/share/fonts/truetype/noto/NotoSansMedefaidrin-Regular.ttf", postscriptName: "NotoSansMedefaidrin-Regular" },
  "un-noto-sans-meeteimayek": { path: "/usr/share/fonts/truetype/noto/NotoSansMeeteiMayek-Regular.ttf", postscriptName: "NotoSansMeeteiMayek-Regular" },
  "un-noto-sans-mende-kikakui": { path: "/usr/share/fonts/truetype/noto/NotoSansMendeKikakui-Regular.ttf", postscriptName: "NotoSansMendeKikakui-Regular" },
  "un-noto-sans-meroitic": { path: "/usr/share/fonts/truetype/noto/NotoSansMeroitic-Regular.ttf", postscriptName: "NotoSansMeroitic-Regular" },
  "un-noto-sans-miao": { path: "/usr/share/fonts/truetype/noto/NotoSansMiao-Regular.ttf", postscriptName: "NotoSansMiao-Regular" },
  "un-noto-sans-modi": { path: "/usr/share/fonts/truetype/noto/NotoSansModi-Regular.ttf", postscriptName: "NotoSansModi-Regular" },
  "un-noto-sans-mongolian": { path: "/usr/share/fonts/truetype/noto/NotoSansMongolian-Regular.ttf", postscriptName: "NotoSansMongolian-Regular" },
  "un-noto-sans-mono": { path: "/usr/share/fonts/truetype/noto/NotoSansMono-Regular.ttf", postscriptName: "NotoSansMono-Regular" },
  "un-noto-sans-mro": { path: "/usr/share/fonts/truetype/noto/NotoSansMro-Regular.ttf", postscriptName: "NotoSansMro-Regular" },
  "un-noto-sans-multani": { path: "/usr/share/fonts/truetype/noto/NotoSansMultani-Regular.ttf", postscriptName: "NotoSansMultani-Regular" },
  "un-noto-sans-myanmar": { path: "/usr/share/fonts/truetype/noto/NotoSansMyanmar-Regular.ttf", postscriptName: "NotoSansMyanmar-Regular" },
  "un-noto-sans-nabataean": { path: "/usr/share/fonts/truetype/noto/NotoSansNabataean-Regular.ttf", postscriptName: "NotoSansNabataean-Regular" },
  "un-noto-sans-newa": { path: "/usr/share/fonts/truetype/noto/NotoSansNewa-Regular.ttf", postscriptName: "NotoSansNewa-Regular" },
  "un-noto-sans-newtailue": { path: "/usr/share/fonts/truetype/noto/NotoSansNewTaiLue-Regular.ttf", postscriptName: "NotoSansNewTaiLue-Regular" },
  "un-noto-sans-nko": { path: "/usr/share/fonts/truetype/noto/NotoSansNKo-Regular.ttf", postscriptName: "NotoSansNKo-Regular" },
  "un-noto-sans-nushu": { path: "/usr/share/fonts/truetype/noto/NotoSansNushu-Regular.ttf", postscriptName: "NotoSansNushu-Regular" },
  "un-noto-sans-ogham": { path: "/usr/share/fonts/truetype/noto/NotoSansOgham-Regular.ttf", postscriptName: "NotoSansOgham-Regular" },
  "un-noto-sans-ol-chiki": { path: "/usr/share/fonts/truetype/noto/NotoSansOlChiki-Regular.ttf", postscriptName: "NotoSansOlChiki-Regular" },
  "un-noto-sans-old-italic": { path: "/usr/share/fonts/truetype/noto/NotoSansOldItalic-Regular.ttf", postscriptName: "NotoSansOldItalic-Regular" },
  "un-noto-sans-old-permic": { path: "/usr/share/fonts/truetype/noto/NotoSansOldPermic-Regular.ttf", postscriptName: "NotoSansOldPermic-Regular" },
  "un-noto-sans-old-turkic": { path: "/usr/share/fonts/truetype/noto/NotoSansOldTurkic-Regular.ttf", postscriptName: "NotoSansOldTurkic-Regular" },
  "un-noto-sans-oldhung": { path: "/usr/share/fonts/truetype/noto/NotoSansOldHungarian-Regular.ttf", postscriptName: "NotoSansOldHungarian-Regular" },
  "un-noto-sans-oldnorarab": { path: "/usr/share/fonts/truetype/noto/NotoSansOldNorthArabian-Regular.ttf", postscriptName: "NotoSansOldNorthArabian-Regular" },
  "un-noto-sans-oldpersian": { path: "/usr/share/fonts/truetype/noto/NotoSansOldPersian-Regular.ttf", postscriptName: "NotoSansOldPersian-Regular" },
  "un-noto-sans-oldsogdian": { path: "/usr/share/fonts/truetype/noto/NotoSansOldSogdian-Regular.ttf", postscriptName: "NotoSansOldSogdian-Regular" },
  "un-noto-sans-oldsouarab": { path: "/usr/share/fonts/truetype/noto/NotoSansOldSouthArabian-Regular.ttf", postscriptName: "NotoSansOldSouthArabian-Regular" },
  "un-noto-sans-oriya": { path: "/usr/share/fonts/truetype/noto/NotoSansOriya-Regular.ttf", postscriptName: "NotoSansOriya-Regular" },
  "un-noto-sans-osage": { path: "/usr/share/fonts/truetype/noto/NotoSansOsage-Regular.ttf", postscriptName: "NotoSansOsage-Regular" },
  "un-noto-sans-osmanya": { path: "/usr/share/fonts/truetype/noto/NotoSansOsmanya-Regular.ttf", postscriptName: "NotoSansOsmanya-Regular" },
  "un-noto-sans-pahawh-hmong": { path: "/usr/share/fonts/truetype/noto/NotoSansPahawhHmong-Regular.ttf", postscriptName: "NotoSansPahawhHmong-Regular" },
  "un-noto-sans-palmyrene": { path: "/usr/share/fonts/truetype/noto/NotoSansPalmyrene-Regular.ttf", postscriptName: "NotoSansPalmyrene-Regular" },
  "un-noto-sans-paucinhau": { path: "/usr/share/fonts/truetype/noto/NotoSansPauCinHau-Regular.ttf", postscriptName: "NotoSansPauCinHau-Regular" },
  "un-noto-sans-phagspa": { path: "/usr/share/fonts/truetype/noto/NotoSansPhagsPa-Regular.ttf", postscriptName: "NotoSansPhagsPa-Regular" },
  "un-noto-sans-phoenician": { path: "/usr/share/fonts/truetype/noto/NotoSansPhoenician-Regular.ttf", postscriptName: "NotoSansPhoenician-Regular" },
  "un-noto-sans-psapahlavi": { path: "/usr/share/fonts/truetype/noto/NotoSansPsalterPahlavi-Regular.ttf", postscriptName: "NotoSansPsalterPahlavi-Regular" },
  "un-noto-sans-rejang": { path: "/usr/share/fonts/truetype/noto/NotoSansRejang-Regular.ttf", postscriptName: "NotoSansRejang-Regular" },
  "un-noto-sans-runic": { path: "/usr/share/fonts/truetype/noto/NotoSansRunic-Regular.ttf", postscriptName: "NotoSansRunic-Regular" },
  "un-noto-sans-samaritan": { path: "/usr/share/fonts/truetype/noto/NotoSansSamaritan-Regular.ttf", postscriptName: "NotoSansSamaritan-Regular" },
  "un-noto-sans-saurashtra": { path: "/usr/share/fonts/truetype/noto/NotoSansSaurashtra-Regular.ttf", postscriptName: "NotoSansSaurashtra-Regular" },
  "un-noto-sans-sharada": { path: "/usr/share/fonts/truetype/noto/NotoSansSharada-Regular.ttf", postscriptName: "NotoSansSharada-Regular" },
  "un-noto-sans-shavian": { path: "/usr/share/fonts/truetype/noto/NotoSansShavian-Regular.ttf", postscriptName: "NotoSansShavian-Regular" },
  "un-noto-sans-siddham": { path: "/usr/share/fonts/truetype/noto/NotoSansSiddham-Regular.ttf", postscriptName: "NotoSansSiddham-Regular" },
  "un-noto-sans-signwrit": { path: "/usr/share/fonts/truetype/noto/NotoSansSignWriting-Regular.ttf", postscriptName: "NotoSansSignWriting-Regular" },
  "un-noto-sans-sogdian": { path: "/usr/share/fonts/truetype/noto/NotoSansSogdian-Regular.ttf", postscriptName: "NotoSansSogdian-Regular" },
  "un-noto-sans-sora-sompeng": { path: "/usr/share/fonts/truetype/noto/NotoSansSoraSompeng-Regular.ttf", postscriptName: "NotoSansSoraSompeng-Regular" },
  "un-noto-sans-soyombo": { path: "/usr/share/fonts/truetype/noto/NotoSansSoyombo-Regular.ttf", postscriptName: "NotoSansSoyombo-Regular" },
  "un-noto-sans-sundanese": { path: "/usr/share/fonts/truetype/noto/NotoSansSundanese-Regular.ttf", postscriptName: "NotoSansSundanese-Regular" },
  "un-noto-sans-syloti-nagri": { path: "/usr/share/fonts/truetype/noto/NotoSansSylotiNagri-Regular.ttf", postscriptName: "NotoSansSylotiNagri-Regular" },
  "un-noto-sans-symbols": { path: "/usr/share/fonts/truetype/noto/NotoSansSymbols-Regular.ttf", postscriptName: "NotoSansSymbols-Regular" },
  "un-noto-sans-symbols2": { path: "/usr/share/fonts/truetype/noto/NotoSansSymbols2-Regular.ttf", postscriptName: "NotoSansSymbols2-Regular" },
  "un-noto-sans-syriac": { path: "/usr/share/fonts/truetype/noto/NotoSansSyriac-Regular.ttf", postscriptName: "NotoSansSyriac-Regular" },
  "un-noto-sans-tagalog": { path: "/usr/share/fonts/truetype/noto/NotoSansTagalog-Regular.ttf", postscriptName: "NotoSansTagalog-Regular" },
  "un-noto-sans-tagbanwa": { path: "/usr/share/fonts/truetype/noto/NotoSansTagbanwa-Regular.ttf", postscriptName: "NotoSansTagbanwa-Regular" },
  "un-noto-sans-tai-le": { path: "/usr/share/fonts/truetype/noto/NotoSansTaiLe-Regular.ttf", postscriptName: "NotoSansTaiLe-Regular" },
  "un-noto-sans-tai-tham": { path: "/usr/share/fonts/truetype/noto/NotoSansTaiTham-Regular.ttf", postscriptName: "NotoSansTaiTham-Regular" },
  "un-noto-sans-tai-viet": { path: "/usr/share/fonts/truetype/noto/NotoSansTaiViet-Regular.ttf", postscriptName: "NotoSansTaiViet-Regular" },
  "un-noto-sans-takri": { path: "/usr/share/fonts/truetype/noto/NotoSansTakri-Regular.ttf", postscriptName: "NotoSansTakri-Regular" },
  "un-noto-sans-tamil": { path: "/usr/share/fonts/truetype/noto/NotoSansTamil-Regular.ttf", postscriptName: "NotoSansTamil-Regular" },
  "un-noto-sans-tamil-supplement": { path: "/usr/share/fonts/truetype/noto/NotoSansTamilSupplement-Regular.ttf", postscriptName: "NotoSansTamilSupplement-Regular" },
  "un-noto-sans-telugu": { path: "/usr/share/fonts/truetype/noto/NotoSansTelugu-Regular.ttf", postscriptName: "NotoSansTelugu-Regular" },
  "un-noto-sans-thaana": { path: "/usr/share/fonts/truetype/noto/NotoSansThaana-Regular.ttf", postscriptName: "NotoSansThaana-Regular" },
  "un-noto-sans-thai": { path: "/usr/share/fonts/truetype/noto/NotoSansThai-Regular.ttf", postscriptName: "NotoSansThai-Regular" },
  "un-noto-sans-tifinagh": { path: "/usr/share/fonts/truetype/noto/NotoSansTifinagh-Regular.ttf", postscriptName: "NotoSansTifinagh-Regular" },
  "un-noto-sans-tirhuta": { path: "/usr/share/fonts/truetype/noto/NotoSansTirhuta-Regular.ttf", postscriptName: "NotoSansTirhuta-Regular" },
  "un-noto-sans-ugaritic": { path: "/usr/share/fonts/truetype/noto/NotoSansUgaritic-Regular.ttf", postscriptName: "NotoSansUgaritic-Regular" },
  "un-noto-sans-vai": { path: "/usr/share/fonts/truetype/noto/NotoSansVai-Regular.ttf", postscriptName: "NotoSansVai-Regular" },
  "un-noto-sans-wancho": { path: "/usr/share/fonts/truetype/noto/NotoSansWancho-Regular.ttf", postscriptName: "NotoSansWancho-Regular" },
  "un-noto-sans-warangciti": { path: "/usr/share/fonts/truetype/noto/NotoSansWarangCiti-Regular.ttf", postscriptName: "NotoSansWarangCiti-Regular" },
  "un-noto-sans-yi": { path: "/usr/share/fonts/truetype/noto/NotoSansYi-Regular.ttf", postscriptName: "NotoSansYi-Regular" },
  "un-noto-sans-zanabazar": { path: "/usr/share/fonts/truetype/noto/NotoSansZanabazarSquare-Regular.ttf", postscriptName: "NotoSansZanabazarSquare-Regular" },
  "un-noto-serif-ahom": { path: "/usr/share/fonts/truetype/noto/NotoSerifAhom-Regular.ttf", postscriptName: "NotoSerifAhom-Regular" },
  "un-noto-serif-balinese": { path: "/usr/share/fonts/truetype/noto/NotoSerifBalinese-Regular.ttf", postscriptName: "NotoSerifBalinese-Regular" },
  "un-noto-serif-dogra": { path: "/usr/share/fonts/truetype/noto/NotoSerifDogra-Regular.ttf", postscriptName: "NotoSerifDogra-Regular" },
  "un-noto-serif-gujarati": { path: "/usr/share/fonts/truetype/noto/NotoSerifGujarati-Regular.ttf", postscriptName: "NotoSerifGujarati-Regular" },
  "un-noto-serif-hmong-nyiakeng": { path: "/usr/share/fonts/truetype/noto/NotoSerifNyiakengPuachueHmong-Regular.ttf", postscriptName: "NotoSerifHmongNyiakeng-Regular" },
  "un-noto-serif-kannada": { path: "/usr/share/fonts/truetype/noto/NotoSerifKannada-Regular.ttf", postscriptName: "NotoSerifKannada-Regular" },
  "un-noto-serif-sinhala": { path: "/usr/share/fonts/truetype/noto/NotoSerifSinhala-Regular.ttf", postscriptName: "NotoSerifSinhala-Regular" },
  "un-noto-serif-tangut": { path: "/usr/share/fonts/truetype/noto/NotoSerifTangut-Regular.ttf", postscriptName: "NotoSerifTangut-Regular" },
  "un-noto-serif-tibetan": { path: "/usr/share/fonts/truetype/noto/NotoSerifTibetan-Regular.ttf", postscriptName: "NotoSerifTibetan-Regular" },
  "un-noto-serif-yezidi": { path: "/usr/share/fonts/truetype/noto/NotoSerifYezidi-Regular.ttf", postscriptName: "NotoSerifYezidi-Regular" },
};

/** [start, end, fontKey] tuples sorted by start. Binary-searched per codepoint. */
export const UNICODE_FONT_RANGES_NOTO_LINUX: ReadonlyArray<readonly [number, number, string]> = [
  [0x0, 0x7F, "un-noto-sans"], // 0000-007F-basic-latin (Noto Sans)
  [0x80, 0xFF, "un-noto-sans"], // 0080-00FF-latin-1-supplement (Noto Sans)
  [0x100, 0x17F, "un-noto-sans"], // 0100-017F-latin-extended-a (Noto Sans)
  [0x180, 0x24F, "un-noto-sans"], // 0180-024F-latin-extended-b (Noto Sans)
  [0x250, 0x2AF, "un-noto-sans"], // 0250-02AF-ipa-extensions (Noto Sans)
  [0x2B0, 0x2FF, "un-noto-sans"], // 02B0-02FF-spacing-modifier-letters (Noto Sans)
  [0x300, 0x36F, "un-noto-sans"], // 0300-036F-combining-diacritical-marks (Noto Sans)
  [0x370, 0x3FF, "un-noto-sans"], // 0370-03FF-greek-and-coptic (Noto Sans)
  [0x400, 0x4FF, "un-noto-sans"], // 0400-04FF-cyrillic (Noto Sans)
  [0x500, 0x52F, "un-noto-sans"], // 0500-052F-cyrillic-supplement (Noto Sans)
  [0x530, 0x58F, "un-noto-sans-armenian"], // 0530-058F-armenian (Noto Sans Armenian)
  [0x590, 0x5FF, "un-liberation-sans"], // 0590-05FF-hebrew (Liberation Sans)
  [0x600, 0x6FF, "un-noto-naskh-arabic-ui"], // 0600-06FF-arabic (Noto Naskh Arabic UI)
  [0x700, 0x74F, "un-noto-sans-syriac"], // 0700-074F-syriac (Noto Sans Syriac)
  [0x750, 0x77F, "un-noto-kufi-arabic"], // 0750-077F-arabic-supplement (Noto Kufi Arabic)
  [0x780, 0x7BF, "un-noto-sans-thaana"], // 0780-07BF-thaana (Noto Sans Thaana)
  [0x7C0, 0x7FF, "un-noto-sans-nko"], // 07C0-07FF-nko (Noto Sans NKo)
  [0x800, 0x83F, "un-noto-sans-samaritan"], // 0800-083F-samaritan (Noto Sans Samaritan)
  [0x840, 0x85F, "un-noto-sans-mandaic"], // 0840-085F-mandaic (Noto Sans Mandaic)
  [0x860, 0x86F, "un-noto-sans"], // 0860-086F-syriac-supplement (Noto Sans)
  [0x870, 0x89F, "un-noto-sans"], // 0870-089F-arabic-extended-b (Noto Sans)
  [0x8A0, 0x8FF, "un-noto-naskh-arabic-ui"], // 08A0-08FF-arabic-extended-a (Noto Naskh Arabic UI)
  [0x900, 0x97F, "un-noto-sans-devanagari"], // 0900-097F-devanagari (Noto Sans Devanagari)
  [0x980, 0x9FF, "un-noto-sans-bengali"], // 0980-09FF-bengali (Noto Sans Bengali)
  [0xA00, 0xA7F, "un-noto-sans-gurmukhi"], // 0A00-0A7F-gurmukhi (Noto Sans Gurmukhi)
  [0xA80, 0xAFF, "un-noto-serif-gujarati"], // 0A80-0AFF-gujarati (Noto Serif Gujarati)
  [0xB00, 0xB7F, "un-noto-sans-oriya"], // 0B00-0B7F-oriya (Noto Sans Oriya)
  [0xB80, 0xBFF, "un-noto-sans-tamil"], // 0B80-0BFF-tamil (Noto Sans Tamil)
  [0xC00, 0xC7F, "un-noto-sans-telugu"], // 0C00-0C7F-telugu (Noto Sans Telugu)
  [0xC80, 0xCFF, "un-noto-serif-kannada"], // 0C80-0CFF-kannada (Noto Serif Kannada)
  [0xD00, 0xD7F, "un-noto-sans-malayalam"], // 0D00-0D7F-malayalam (Noto Sans Malayalam)
  [0xD80, 0xDFF, "un-noto-serif-sinhala"], // 0D80-0DFF-sinhala (Noto Serif Sinhala)
  [0xE00, 0xE7F, "un-noto-sans-thai"], // 0E00-0E7F-thai (Noto Sans Thai)
  [0xE80, 0xEFF, "un-noto-sans-lao"], // 0E80-0EFF-lao (Noto Sans Lao)
  [0xF00, 0xFFF, "un-noto-serif-tibetan"], // 0F00-0FFF-tibetan (Noto Serif Tibetan)
  [0x1000, 0x109F, "un-noto-sans-myanmar"], // 1000-109F-myanmar (Noto Sans Myanmar)
  [0x10A0, 0x10FF, "un-noto-sans-georgian"], // 10A0-10FF-georgian (Noto Sans Georgian)
  [0x1100, 0x11FF, "un-noto-sans-cjk-jp"], // 1100-11FF-hangul-jamo (Noto Sans CJK JP)
  [0x1200, 0x137F, "un-noto-sans-ethiopic"], // 1200-137F-ethiopic.0 (Noto Sans Ethiopic)
  [0x1380, 0x139F, "un-noto-sans-ethiopic"], // 1380-139F-ethiopic-supplement (Noto Sans Ethiopic)
  [0x13A0, 0x13FF, "un-noto-sans-cherokee"], // 13A0-13FF-cherokee (Noto Sans Cherokee)
  [0x1400, 0x167F, "un-noto-sans-canaborig"], // 1400-167F-unified-canadian-aboriginal-syllabics.0 (Noto Sans CanAborig)
  [0x1680, 0x169F, "un-noto-sans-ogham"], // 1680-169F-ogham (Noto Sans Ogham)
  [0x16A0, 0x16FF, "un-noto-sans-runic"], // 16A0-16FF-runic (Noto Sans Runic)
  [0x1700, 0x171F, "un-noto-sans-tagalog"], // 1700-171F-tagalog (Noto Sans Tagalog)
  [0x1720, 0x173F, "un-noto-sans-hanunoo"], // 1720-173F-hanunoo (Noto Sans Hanunoo)
  [0x1740, 0x175F, "un-noto-sans-buhid"], // 1740-175F-buhid (Noto Sans Buhid)
  [0x1760, 0x177F, "un-noto-sans-tagbanwa"], // 1760-177F-tagbanwa (Noto Sans Tagbanwa)
  [0x1780, 0x17FF, "un-noto-sans-khmer"], // 1780-17FF-khmer (Noto Sans Khmer)
  [0x1800, 0x18AF, "un-noto-sans-mongolian"], // 1800-18AF-mongolian (Noto Sans Mongolian)
  [0x18B0, 0x18FF, "un-noto-sans-canaborig"], // 18B0-18FF-unified-canadian-aboriginal-syllabics-extended (Noto Sans CanAborig)
  [0x1900, 0x194F, "un-noto-sans-limbu"], // 1900-194F-limbu (Noto Sans Limbu)
  [0x1950, 0x197F, "un-noto-sans-tai-le"], // 1950-197F-tai-le (Noto Sans Tai Le)
  [0x1980, 0x19DF, "un-noto-sans-newtailue"], // 1980-19DF-new-tai-lue (Noto Sans NewTaiLue)
  [0x19E0, 0x19FF, "un-noto-sans-khmer"], // 19E0-19FF-khmer-symbols (Noto Sans Khmer)
  [0x1A00, 0x1A1F, "un-noto-sans-buginese"], // 1A00-1A1F-buginese (Noto Sans Buginese)
  [0x1A20, 0x1AAF, "un-noto-sans-tai-tham"], // 1A20-1AAF-tai-tham (Noto Sans Tai Tham)
  [0x1AB0, 0x1AFF, "un-noto-sans"], // 1AB0-1AFF-combining-diacritical-marks-extended (Noto Sans)
  [0x1B00, 0x1B7F, "un-noto-serif-balinese"], // 1B00-1B7F-balinese (Noto Serif Balinese)
  [0x1B80, 0x1BBF, "un-noto-sans-sundanese"], // 1B80-1BBF-sundanese (Noto Sans Sundanese)
  [0x1BC0, 0x1BFF, "un-noto-sans-batak"], // 1BC0-1BFF-batak (Noto Sans Batak)
  [0x1C00, 0x1C4F, "un-noto-sans-lepcha"], // 1C00-1C4F-lepcha (Noto Sans Lepcha)
  [0x1C50, 0x1C7F, "un-noto-sans-ol-chiki"], // 1C50-1C7F-ol-chiki (Noto Sans Ol Chiki)
  [0x1C80, 0x1C8F, "un-noto-sans"], // 1C80-1C8F-cyrillic-extended-c (Noto Sans)
  [0x1C90, 0x1CBF, "un-noto-sans-georgian"], // 1C90-1CBF-georgian-extended (Noto Sans Georgian)
  [0x1CC0, 0x1CCF, "un-noto-sans-sundanese"], // 1CC0-1CCF-sundanese-supplement (Noto Sans Sundanese)
  [0x1CD0, 0x1CFF, "un-noto-serif-kannada"], // 1CD0-1CFF-vedic-extensions (Noto Serif Kannada)
  [0x1D00, 0x1D7F, "un-noto-sans"], // 1D00-1D7F-phonetic-extensions (Noto Sans)
  [0x1D80, 0x1DBF, "un-liberation-sans"], // 1D80-1DBF-phonetic-extensions-supplement (Liberation Sans)
  [0x1DC0, 0x1DFF, "un-noto-sans"], // 1DC0-1DFF-combining-diacritical-marks-supplement (Noto Sans)
  [0x1E00, 0x1EFF, "un-noto-sans"], // 1E00-1EFF-latin-extended-additional (Noto Sans)
  [0x1F00, 0x1FFF, "un-noto-sans"], // 1F00-1FFF-greek-extended (Noto Sans)
  [0x2000, 0x206F, "un-noto-sans"], // 2000-206F-general-punctuation (Noto Sans)
  [0x2070, 0x209F, "un-noto-sans"], // 2070-209F-superscripts-and-subscripts (Noto Sans)
  [0x20A0, 0x20CF, "un-noto-sans"], // 20A0-20CF-currency-symbols (Noto Sans)
  [0x20D0, 0x20FF, "un-noto-sans-math"], // 20D0-20FF-combining-diacritical-marks-for-symbols (Noto Sans Math)
  [0x2100, 0x214F, "un-noto-sans"], // 2100-214F-letterlike-symbols (Noto Sans)
  [0x2150, 0x218F, "un-noto-sans"], // 2150-218F-number-forms (Noto Sans)
  [0x2190, 0x21FF, "un-liberation-sans"], // 2190-21FF-arrows (Liberation Sans)
  [0x2200, 0x22FF, "un-noto-sans-mono"], // 2200-22FF-mathematical-operators (Noto Sans Mono)
  [0x2300, 0x23FF, "un-noto-sans-symbols"], // 2300-23FF-miscellaneous-technical (Noto Sans Symbols)
  [0x2400, 0x243F, "un-noto-sans-symbols2"], // 2400-243F-control-pictures (Noto Sans Symbols2)
  [0x2440, 0x245F, "un-noto-sans-symbols2"], // 2440-245F-optical-character-recognition (Noto Sans Symbols2)
  [0x2460, 0x24FF, "un-noto-sans-cjk-jp"], // 2460-24FF-enclosed-alphanumerics (Noto Sans CJK JP)
  [0x2500, 0x257F, "un-liberation-sans"], // 2500-257F-box-drawing (Liberation Sans)
  [0x2580, 0x259F, "un-liberation-sans"], // 2580-259F-block-elements (Liberation Sans)
  [0x25A0, 0x25FF, "un-liberation-sans"], // 25A0-25FF-geometric-shapes (Liberation Sans)
  [0x2600, 0x26FF, "un-noto-sans-cjk-jp"], // 2600-26FF-miscellaneous-symbols (Noto Sans CJK JP)
  [0x2700, 0x27BF, "un-noto-sans-symbols2"], // 2700-27BF-dingbats (Noto Sans Symbols2)
  [0x27C0, 0x27EF, "un-noto-sans-math"], // 27C0-27EF-miscellaneous-mathematical-symbols-a (Noto Sans Math)
  [0x27F0, 0x27FF, "un-noto-sans-math"], // 27F0-27FF-supplemental-arrows-a (Noto Sans Math)
  [0x2800, 0x28FF, "un-noto-sans-symbols2"], // 2800-28FF-braille-patterns (Noto Sans Symbols2)
  [0x2900, 0x297F, "un-noto-sans-math"], // 2900-297F-supplemental-arrows-b (Noto Sans Math)
  [0x2980, 0x29FF, "un-noto-sans-math"], // 2980-29FF-miscellaneous-mathematical-symbols-b (Noto Sans Math)
  [0x2A00, 0x2AFF, "un-noto-sans-mono"], // 2A00-2AFF-supplemental-mathematical-operators (Noto Sans Mono)
  [0x2B00, 0x2BFF, "un-noto-sans-symbols2"], // 2B00-2BFF-miscellaneous-symbols-and-arrows (Noto Sans Symbols2)
  [0x2C00, 0x2C5F, "un-noto-sans-glagolitic"], // 2C00-2C5F-glagolitic (Noto Sans Glagolitic)
  [0x2C60, 0x2C7F, "un-noto-sans"], // 2C60-2C7F-latin-extended-c (Noto Sans)
  [0x2C80, 0x2CFF, "un-noto-sans-coptic"], // 2C80-2CFF-coptic (Noto Sans Coptic)
  [0x2D00, 0x2D2F, "un-noto-sans-georgian"], // 2D00-2D2F-georgian-supplement (Noto Sans Georgian)
  [0x2D30, 0x2D7F, "un-noto-sans-tifinagh"], // 2D30-2D7F-tifinagh (Noto Sans Tifinagh)
  [0x2D80, 0x2DDF, "un-noto-sans-ethiopic"], // 2D80-2DDF-ethiopic-extended (Noto Sans Ethiopic)
  [0x2DE0, 0x2DFF, "un-noto-sans"], // 2DE0-2DFF-cyrillic-extended-a (Noto Sans)
  [0x2E00, 0x2E7F, "un-noto-sans"], // 2E00-2E7F-supplemental-punctuation (Noto Sans)
  [0x2E80, 0x2EFF, "un-noto-sans-cjk-jp"], // 2E80-2EFF-cjk-radicals-supplement (Noto Sans CJK JP)
  [0x2F00, 0x2FDF, "un-noto-sans-cjk-jp"], // 2F00-2FDF-kangxi-radicals (Noto Sans CJK JP)
  [0x2FF0, 0x2FFF, "un-noto-sans-cjk-jp"], // 2FF0-2FFF-ideographic-description-characters (Noto Sans CJK JP)
  [0x3000, 0x303F, "un-noto-sans-cjk-jp"], // 3000-303F-cjk-symbols-and-punctuation (Noto Sans CJK JP)
  [0x3040, 0x309F, "un-noto-sans-cjk-jp"], // 3040-309F-hiragana (Noto Sans CJK JP)
  [0x30A0, 0x30FF, "un-noto-sans-cjk-jp"], // 30A0-30FF-katakana (Noto Sans CJK JP)
  [0x3100, 0x312F, "un-noto-sans-cjk-jp"], // 3100-312F-bopomofo (Noto Sans CJK JP)
  [0x3130, 0x318F, "un-noto-sans-cjk-jp"], // 3130-318F-hangul-compatibility-jamo (Noto Sans CJK JP)
  [0x3190, 0x319F, "un-noto-sans-cjk-jp"], // 3190-319F-kanbun (Noto Sans CJK JP)
  [0x31A0, 0x31BF, "un-noto-sans-cjk-jp"], // 31A0-31BF-bopomofo-extended (Noto Sans CJK JP)
  [0x31C0, 0x31EF, "un-noto-sans-cjk-jp"], // 31C0-31EF-cjk-strokes (Noto Sans CJK JP)
  [0x31F0, 0x31FF, "un-noto-sans-cjk-jp"], // 31F0-31FF-katakana-phonetic-extensions (Noto Sans CJK JP)
  [0x3200, 0x32FF, "un-noto-sans-cjk-jp"], // 3200-32FF-enclosed-cjk-letters-and-months (Noto Sans CJK JP)
  [0x3300, 0x33FF, "un-noto-sans-cjk-jp"], // 3300-33FF-cjk-compatibility (Noto Sans CJK JP)
  [0x3400, 0x4DBF, "un-noto-sans-cjk-jp"], // 3400-4DBF-cjk-unified-ideographs-extension-a.0 (Noto Sans CJK JP)
  [0x4DC0, 0x4DFF, "un-noto-sans-symbols2"], // 4DC0-4DFF-yijing-hexagram-symbols (Noto Sans Symbols2)
  [0x4E00, 0x9FFF, "un-noto-sans-cjk-jp"], // 4E00-9FFF-cjk-unified-ideographs.0 (Noto Sans CJK JP)
  [0xA000, 0xA48F, "un-noto-sans-yi"], // A000-A48F-yi-syllables.0 (Noto Sans Yi)
  [0xA490, 0xA4CF, "un-noto-sans-yi"], // A490-A4CF-yi-radicals (Noto Sans Yi)
  [0xA4D0, 0xA4FF, "un-noto-sans-lisu"], // A4D0-A4FF-lisu (Noto Sans Lisu)
  [0xA500, 0xA63F, "un-noto-sans-vai"], // A500-A63F-vai.0 (Noto Sans Vai)
  [0xA640, 0xA69F, "un-noto-sans"], // A640-A69F-cyrillic-extended-b (Noto Sans)
  [0xA6A0, 0xA6FF, "un-noto-sans-bamum"], // A6A0-A6FF-bamum (Noto Sans Bamum)
  [0xA700, 0xA71F, "un-noto-sans"], // A700-A71F-modifier-tone-letters (Noto Sans)
  [0xA720, 0xA7FF, "un-noto-sans"], // A720-A7FF-latin-extended-d (Noto Sans)
  [0xA800, 0xA82F, "un-noto-sans-syloti-nagri"], // A800-A82F-syloti-nagri (Noto Sans Syloti Nagri)
  [0xA830, 0xA83F, "un-noto-sans-takri"], // A830-A83F-common-indic-number-forms (Noto Sans Takri)
  [0xA840, 0xA87F, "un-noto-sans-phagspa"], // A840-A87F-phags-pa (Noto Sans PhagsPa)
  [0xA880, 0xA8DF, "un-noto-sans-saurashtra"], // A880-A8DF-saurashtra (Noto Sans Saurashtra)
  [0xA8E0, 0xA8FF, "un-noto-sans-devanagari"], // A8E0-A8FF-devanagari-extended (Noto Sans Devanagari)
  [0xA900, 0xA92F, "un-noto-sans-kayah-li"], // A900-A92F-kayah-li (Noto Sans Kayah Li)
  [0xA930, 0xA95F, "un-noto-sans-rejang"], // A930-A95F-rejang (Noto Sans Rejang)
  [0xA960, 0xA97F, "un-noto-sans-cjk-jp"], // A960-A97F-hangul-jamo-extended-a (Noto Sans CJK JP)
  [0xA980, 0xA9DF, "un-noto-sans-javanese"], // A980-A9DF-javanese (Noto Sans Javanese)
  [0xA9E0, 0xA9FF, "un-noto-sans-myanmar"], // A9E0-A9FF-myanmar-extended-b (Noto Sans Myanmar)
  [0xAA00, 0xAA5F, "un-noto-sans-cham"], // AA00-AA5F-cham (Noto Sans Cham)
  [0xAA60, 0xAA7F, "un-noto-sans-myanmar"], // AA60-AA7F-myanmar-extended-a (Noto Sans Myanmar)
  [0xAA80, 0xAADF, "un-noto-sans-tai-viet"], // AA80-AADF-tai-viet (Noto Sans Tai Viet)
  [0xAAE0, 0xAAFF, "un-noto-sans-meeteimayek"], // AAE0-AAFF-meetei-mayek-extensions (Noto Sans MeeteiMayek)
  [0xAB00, 0xAB2F, "un-noto-sans-ethiopic"], // AB00-AB2F-ethiopic-extended-a (Noto Sans Ethiopic)
  [0xAB30, 0xAB6F, "un-noto-sans"], // AB30-AB6F-latin-extended-e (Noto Sans)
  [0xAB70, 0xABBF, "un-noto-sans-cherokee"], // AB70-ABBF-cherokee-supplement (Noto Sans Cherokee)
  [0xABC0, 0xABFF, "un-noto-sans-meeteimayek"], // ABC0-ABFF-meetei-mayek (Noto Sans MeeteiMayek)
  [0xAC00, 0xD7AF, "un-noto-sans-cjk-jp"], // AC00-D7AF-hangul-syllables.0 (Noto Sans CJK JP)
  [0xD7B0, 0xD7FF, "un-noto-sans-cjk-jp"], // D7B0-D7FF-hangul-jamo-extended-b (Noto Sans CJK JP)
  [0xF900, 0xFAFF, "un-noto-sans-cjk-jp"], // F900-FAFF-cjk-compatibility-ideographs.0 (Noto Sans CJK JP)
  [0xFB00, 0xFB4F, "un-noto-sans"], // FB00-FB4F-alphabetic-presentation-forms (Noto Sans)
  [0xFB50, 0xFDFF, "un-noto-naskh-arabic-ui"], // FB50-FDFF-arabic-presentation-forms-a.0 (Noto Naskh Arabic UI)
  [0xFE00, 0xFE0F, "un-noto-sans"], // FE00-FE0F-variation-selectors (Noto Sans)
  [0xFE10, 0xFE1F, "un-noto-sans-cjk-jp"], // FE10-FE1F-vertical-forms (Noto Sans CJK JP)
  [0xFE20, 0xFE2F, "un-liberation-sans"], // FE20-FE2F-combining-half-marks (Liberation Sans)
  [0xFE30, 0xFE4F, "un-noto-sans-cjk-jp"], // FE30-FE4F-cjk-compatibility-forms (Noto Sans CJK JP)
  [0xFE50, 0xFE6F, "un-noto-sans-cjk-jp"], // FE50-FE6F-small-form-variants (Noto Sans CJK JP)
  [0xFE70, 0xFEFF, "un-noto-kufi-arabic"], // FE70-FEFF-arabic-presentation-forms-b (Noto Kufi Arabic)
  [0xFF00, 0xFFEF, "un-noto-sans-cjk-jp"], // FF00-FFEF-halfwidth-and-fullwidth-forms (Noto Sans CJK JP)
  [0xFFF0, 0xFFFF, "un-liberation-sans"], // FFF0-FFFF-specials (Liberation Sans)
  [0x10000, 0x1007F, "un-noto-sans-linear-b"], // 10000-1007F-linear-b-syllabary (Noto Sans Linear B)
  [0x10080, 0x100FF, "un-noto-sans-linear-b"], // 10080-100FF-linear-b-ideograms (Noto Sans Linear B)
  [0x10100, 0x1013F, "un-noto-sans-linear-b"], // 10100-1013F-aegean-numbers (Noto Sans Linear B)
  [0x10140, 0x1018F, "un-noto-sans-symbols2"], // 10140-1018F-ancient-greek-numbers (Noto Sans Symbols2)
  [0x10190, 0x101CF, "un-noto-sans-symbols2"], // 10190-101CF-ancient-symbols (Noto Sans Symbols2)
  [0x101D0, 0x101FF, "un-noto-sans-symbols2"], // 101D0-101FF-phaistos-disc (Noto Sans Symbols2)
  [0x10280, 0x1029F, "un-noto-sans-lycian"], // 10280-1029F-lycian (Noto Sans Lycian)
  [0x102A0, 0x102DF, "un-noto-sans-carian"], // 102A0-102DF-carian (Noto Sans Carian)
  [0x102E0, 0x102FF, "un-noto-sans-coptic"], // 102E0-102FF-coptic-epact-numbers (Noto Sans Coptic)
  [0x10300, 0x1032F, "un-noto-sans-old-italic"], // 10300-1032F-old-italic (Noto Sans Old Italic)
  [0x10330, 0x1034F, "un-noto-sans-gothic"], // 10330-1034F-gothic (Noto Sans Gothic)
  [0x10350, 0x1037F, "un-noto-sans-old-permic"], // 10350-1037F-old-permic (Noto Sans Old Permic)
  [0x10380, 0x1039F, "un-noto-sans-ugaritic"], // 10380-1039F-ugaritic (Noto Sans Ugaritic)
  [0x103A0, 0x103DF, "un-noto-sans-oldpersian"], // 103A0-103DF-old-persian (Noto Sans OldPersian)
  [0x10400, 0x1044F, "un-noto-sans-deseret"], // 10400-1044F-deseret (Noto Sans Deseret)
  [0x10450, 0x1047F, "un-noto-sans-shavian"], // 10450-1047F-shavian (Noto Sans Shavian)
  [0x10480, 0x104AF, "un-noto-sans-osmanya"], // 10480-104AF-osmanya (Noto Sans Osmanya)
  [0x104B0, 0x104FF, "un-noto-sans-osage"], // 104B0-104FF-osage (Noto Sans Osage)
  [0x10500, 0x1052F, "un-noto-sans-elbasan"], // 10500-1052F-elbasan (Noto Sans Elbasan)
  [0x10530, 0x1056F, "un-noto-sans-caucalban"], // 10530-1056F-caucasian-albanian (Noto Sans CaucAlban)
  [0x10570, 0x105BF, "un-noto-sans"], // 10570-105BF-vithkuqi (Noto Sans)
  [0x105C0, 0x105FF, "un-noto-sans"], // 105C0-105FF-todhri (Noto Sans)
  [0x10600, 0x1077F, "un-noto-sans-linear-a"], // 10600-1077F-linear-a.0 (Noto Sans Linear A)
  [0x10780, 0x107BF, "un-noto-sans"], // 10780-107BF-latin-extended-f (Noto Sans)
  [0x10800, 0x1083F, "un-noto-sans-cypriot"], // 10800-1083F-cypriot-syllabary (Noto Sans Cypriot)
  [0x10840, 0x1085F, "un-noto-sans-imparamaic"], // 10840-1085F-imperial-aramaic (Noto Sans ImpAramaic)
  [0x10860, 0x1087F, "un-noto-sans-palmyrene"], // 10860-1087F-palmyrene (Noto Sans Palmyrene)
  [0x10880, 0x108AF, "un-noto-sans-nabataean"], // 10880-108AF-nabataean (Noto Sans Nabataean)
  [0x108E0, 0x108FF, "un-noto-sans-hatran"], // 108E0-108FF-hatran (Noto Sans Hatran)
  [0x10900, 0x1091F, "un-noto-sans-phoenician"], // 10900-1091F-phoenician (Noto Sans Phoenician)
  [0x10920, 0x1093F, "un-noto-sans-lydian"], // 10920-1093F-lydian (Noto Sans Lydian)
  [0x10980, 0x1099F, "un-noto-sans-meroitic"], // 10980-1099F-meroitic-hieroglyphs (Noto Sans Meroitic)
  [0x109A0, 0x109FF, "un-noto-sans-meroitic"], // 109A0-109FF-meroitic-cursive (Noto Sans Meroitic)
  [0x10A00, 0x10A5F, "un-noto-sans-kharoshthi"], // 10A00-10A5F-kharoshthi (Noto Sans Kharoshthi)
  [0x10A60, 0x10A7F, "un-noto-sans-oldsouarab"], // 10A60-10A7F-old-south-arabian (Noto Sans OldSouArab)
  [0x10A80, 0x10A9F, "un-noto-sans-oldnorarab"], // 10A80-10A9F-old-north-arabian (Noto Sans OldNorArab)
  [0x10AC0, 0x10AFF, "un-noto-sans-manichaean"], // 10AC0-10AFF-manichaean (Noto Sans Manichaean)
  [0x10B00, 0x10B3F, "un-noto-sans-avestan"], // 10B00-10B3F-avestan (Noto Sans Avestan)
  [0x10B40, 0x10B5F, "un-noto-sans-insparthi"], // 10B40-10B5F-inscriptional-parthian (Noto Sans InsParthi)
  [0x10B60, 0x10B7F, "un-noto-sans-inspahlavi"], // 10B60-10B7F-inscriptional-pahlavi (Noto Sans InsPahlavi)
  [0x10B80, 0x10BAF, "un-noto-sans-psapahlavi"], // 10B80-10BAF-psalter-pahlavi (Noto Sans PsaPahlavi)
  [0x10C00, 0x10C4F, "un-noto-sans-old-turkic"], // 10C00-10C4F-old-turkic (Noto Sans Old Turkic)
  [0x10C80, 0x10CFF, "un-noto-sans-oldhung"], // 10C80-10CFF-old-hungarian (Noto Sans OldHung)
  [0x10D00, 0x10D3F, "un-noto-sans-hanifi-rohingya"], // 10D00-10D3F-hanifi-rohingya (Noto Sans Hanifi Rohingya)
  [0x10D40, 0x10D8F, "un-noto-sans"], // 10D40-10D8F-garay (Noto Sans)
  [0x10E60, 0x10E7F, "un-noto-sans-symbols2"], // 10E60-10E7F-rumi-numeral-symbols (Noto Sans Symbols2)
  [0x10E80, 0x10EBF, "un-noto-serif-yezidi"], // 10E80-10EBF-yezidi (Noto Serif Yezidi)
  [0x10EC0, 0x10EFF, "un-noto-sans"], // 10EC0-10EFF-arabic-extended-c (Noto Sans)
  [0x10F00, 0x10F2F, "un-noto-sans-oldsogdian"], // 10F00-10F2F-old-sogdian (Noto Sans OldSogdian)
  [0x10F30, 0x10F6F, "un-noto-sans-sogdian"], // 10F30-10F6F-sogdian (Noto Sans Sogdian)
  [0x10F70, 0x10FAF, "un-noto-sans"], // 10F70-10FAF-old-uyghur (Noto Sans)
  [0x10FB0, 0x10FDF, "un-noto-sans"], // 10FB0-10FDF-chorasmian (Noto Sans)
  [0x10FE0, 0x10FFF, "un-noto-sans-elymaic"], // 10FE0-10FFF-elymaic (Noto Sans Elymaic)
  [0x11000, 0x1107F, "un-noto-sans-brahmi"], // 11000-1107F-brahmi (Noto Sans Brahmi)
  [0x11080, 0x110CF, "un-noto-sans-kaithi"], // 11080-110CF-kaithi (Noto Sans Kaithi)
  [0x110D0, 0x110FF, "un-noto-sans-sora-sompeng"], // 110D0-110FF-sora-sompeng (Noto Sans Sora Sompeng)
  [0x11100, 0x1114F, "un-noto-sans-chakma"], // 11100-1114F-chakma (Noto Sans Chakma)
  [0x11150, 0x1117F, "un-noto-sans-mahajani"], // 11150-1117F-mahajani (Noto Sans Mahajani)
  [0x11180, 0x111DF, "un-noto-sans-sharada"], // 11180-111DF-sharada (Noto Sans Sharada)
  [0x111E0, 0x111FF, "un-noto-serif-sinhala"], // 111E0-111FF-sinhala-archaic-numbers (Noto Serif Sinhala)
  [0x11200, 0x1124F, "un-noto-sans-khojki"], // 11200-1124F-khojki (Noto Sans Khojki)
  [0x11280, 0x112AF, "un-noto-sans-multani"], // 11280-112AF-multani (Noto Sans Multani)
  [0x112B0, 0x112FF, "un-noto-sans-khudawadi"], // 112B0-112FF-khudawadi (Noto Sans Khudawadi)
  [0x11300, 0x1137F, "un-noto-sans-grantha"], // 11300-1137F-grantha (Noto Sans Grantha)
  [0x11380, 0x113FF, "un-noto-sans"], // 11380-113FF-tulu-tigalari (Noto Sans)
  [0x11400, 0x1147F, "un-noto-sans-newa"], // 11400-1147F-newa (Noto Sans Newa)
  [0x11480, 0x114DF, "un-noto-sans-tirhuta"], // 11480-114DF-tirhuta (Noto Sans Tirhuta)
  [0x11580, 0x115FF, "un-noto-sans-siddham"], // 11580-115FF-siddham (Noto Sans Siddham)
  [0x11600, 0x1165F, "un-noto-sans-modi"], // 11600-1165F-modi (Noto Sans Modi)
  [0x11660, 0x1167F, "un-noto-sans-mongolian"], // 11660-1167F-mongolian-supplement (Noto Sans Mongolian)
  [0x11680, 0x116CF, "un-noto-sans-takri"], // 11680-116CF-takri (Noto Sans Takri)
  [0x116D0, 0x116FF, "un-noto-sans"], // 116D0-116FF-myanmar-extended-c (Noto Sans)
  [0x11700, 0x1174F, "un-noto-serif-ahom"], // 11700-1174F-ahom (Noto Serif Ahom)
  [0x11800, 0x1184F, "un-noto-serif-dogra"], // 11800-1184F-dogra (Noto Serif Dogra)
  [0x118A0, 0x118FF, "un-noto-sans-warangciti"], // 118A0-118FF-warang-citi (Noto Sans WarangCiti)
  [0x11900, 0x1195F, "un-noto-sans"], // 11900-1195F-dives-akuru (Noto Sans)
  [0x119A0, 0x119FF, "un-noto-sans"], // 119A0-119FF-nandinagari (Noto Sans)
  [0x11A00, 0x11A4F, "un-noto-sans-zanabazar"], // 11A00-11A4F-zanabazar-square (Noto Sans Zanabazar)
  [0x11A50, 0x11AAF, "un-noto-sans-soyombo"], // 11A50-11AAF-soyombo (Noto Sans Soyombo)
  [0x11AB0, 0x11ABF, "un-noto-sans"], // 11AB0-11ABF-unified-canadian-aboriginal-syllabics-extended-a (Noto Sans)
  [0x11AC0, 0x11AFF, "un-noto-sans-paucinhau"], // 11AC0-11AFF-pau-cin-hau (Noto Sans PauCinHau)
  [0x11B00, 0x11B5F, "un-noto-sans"], // 11B00-11B5F-devanagari-extended-a (Noto Sans)
  [0x11BC0, 0x11BFF, "un-noto-sans"], // 11BC0-11BFF-sunuwar (Noto Sans)
  [0x11C00, 0x11C6F, "un-noto-sans-bhaiksuki"], // 11C00-11C6F-bhaiksuki (Noto Sans Bhaiksuki)
  [0x11C70, 0x11CBF, "un-noto-sans-marchen"], // 11C70-11CBF-marchen (Noto Sans Marchen)
  [0x11D00, 0x11D5F, "un-noto-sans-masaram-gondi"], // 11D00-11D5F-masaram-gondi (Noto Sans Masaram Gondi)
  [0x11D60, 0x11DAF, "un-noto-sans-gunjala-gondi"], // 11D60-11DAF-gunjala-gondi (Noto Sans Gunjala Gondi)
  [0x11EE0, 0x11EFF, "un-noto-sans"], // 11EE0-11EFF-makasar (Noto Sans)
  [0x11F00, 0x11F5F, "un-noto-sans"], // 11F00-11F5F-kawi (Noto Sans)
  [0x11FB0, 0x11FBF, "un-noto-sans"], // 11FB0-11FBF-lisu-supplement (Noto Sans)
  [0x11FC0, 0x11FFF, "un-noto-sans-tamil-supplement"], // 11FC0-11FFF-tamil-supplement (Noto Sans Tamil Supplement)
  [0x12000, 0x123FF, "un-noto-sans-cuneiform"], // 12000-123FF-cuneiform.0 (Noto Sans Cuneiform)
  [0x12400, 0x1247F, "un-noto-sans-cuneiform"], // 12400-1247F-cuneiform-numbers-and-punctuation (Noto Sans Cuneiform)
  [0x12480, 0x1254F, "un-noto-sans-cuneiform"], // 12480-1254F-early-dynastic-cuneiform (Noto Sans Cuneiform)
  [0x12F90, 0x12FFF, "un-noto-sans"], // 12F90-12FFF-cypro-minoan (Noto Sans)
  [0x13000, 0x1342F, "un-noto-sans-egypthiero"], // 13000-1342F-egyptian-hieroglyphs.0 (Noto Sans EgyptHiero)
  [0x13430, 0x1345F, "un-noto-sans"], // 13430-1345F-egyptian-hieroglyph-format-controls (Noto Sans)
  [0x13460, 0x143FF, "un-noto-sans"], // 13460-143FF-egyptian-hieroglyphs-extended-a.0 (Noto Sans)
  [0x14400, 0x1467F, "un-noto-sans-anatohiero"], // 14400-1467F-anatolian-hieroglyphs.0 (Noto Sans AnatoHiero)
  [0x16100, 0x1613F, "un-noto-sans"], // 16100-1613F-gurung-khema (Noto Sans)
  [0x16800, 0x16A3F, "un-noto-sans-bamum"], // 16800-16A3F-bamum-supplement.0 (Noto Sans Bamum)
  [0x16A40, 0x16A6F, "un-noto-sans-mro"], // 16A40-16A6F-mro (Noto Sans Mro)
  [0x16A70, 0x16ACF, "un-noto-sans"], // 16A70-16ACF-tangsa (Noto Sans)
  [0x16AD0, 0x16AFF, "un-noto-sans-bassa-vah"], // 16AD0-16AFF-bassa-vah (Noto Sans Bassa Vah)
  [0x16B00, 0x16B8F, "un-noto-sans-pahawh-hmong"], // 16B00-16B8F-pahawh-hmong (Noto Sans Pahawh Hmong)
  [0x16D40, 0x16D7F, "un-noto-sans"], // 16D40-16D7F-kirat-rai (Noto Sans)
  [0x16E40, 0x16E9F, "un-noto-sans-medefaidrin"], // 16E40-16E9F-medefaidrin (Noto Sans Medefaidrin)
  [0x16F00, 0x16F9F, "un-noto-sans-miao"], // 16F00-16F9F-miao (Noto Sans Miao)
  [0x16FE0, 0x16FFF, "un-noto-serif-tangut"], // 16FE0-16FFF-ideographic-symbols-and-punctuation (Noto Serif Tangut)
  [0x17000, 0x187FF, "un-noto-serif-tangut"], // 17000-187FF-tangut.0 (Noto Serif Tangut)
  [0x18800, 0x18AFF, "un-noto-serif-tangut"], // 18800-18AFF-tangut-components.0 (Noto Serif Tangut)
  [0x18B00, 0x18CFF, "un-noto-sans"], // 18B00-18CFF-khitan-small-script.0 (Noto Sans)
  [0x18D00, 0x18D7F, "un-noto-sans"], // 18D00-18D7F-tangut-supplement (Noto Sans)
  [0x1AFF0, 0x1AFFF, "un-noto-sans"], // 1AFF0-1AFFF-kana-extended-b (Noto Sans)
  [0x1B000, 0x1B0FF, "un-noto-sans"], // 1B000-1B0FF-kana-supplement (Noto Sans)
  [0x1B100, 0x1B12F, "un-noto-sans"], // 1B100-1B12F-kana-extended-a (Noto Sans)
  [0x1B130, 0x1B16F, "un-noto-sans"], // 1B130-1B16F-small-kana-extension (Noto Sans)
  [0x1B170, 0x1B2FF, "un-noto-sans-nushu"], // 1B170-1B2FF-nushu.0 (Noto Sans Nushu)
  [0x1BC00, 0x1BC9F, "un-noto-sans-duployan"], // 1BC00-1BC9F-duployan (Noto Sans Duployan)
  [0x1CC00, 0x1CEBF, "un-noto-sans"], // 1CC00-1CEBF-symbols-for-legacy-computing-supplement.0 (Noto Sans)
  [0x1CF00, 0x1CFCF, "un-noto-sans"], // 1CF00-1CFCF-znamenny-musical-notation (Noto Sans)
  [0x1D000, 0x1D0FF, "un-noto-music"], // 1D000-1D0FF-byzantine-musical-symbols (Noto Music)
  [0x1D100, 0x1D1FF, "un-noto-music"], // 1D100-1D1FF-musical-symbols (Noto Music)
  [0x1D200, 0x1D24F, "un-noto-music"], // 1D200-1D24F-ancient-greek-musical-notation (Noto Music)
  [0x1D2C0, 0x1D2DF, "un-noto-sans"], // 1D2C0-1D2DF-kaktovik-numerals (Noto Sans)
  [0x1D2E0, 0x1D2FF, "un-noto-sans-symbols2"], // 1D2E0-1D2FF-mayan-numerals (Noto Sans Symbols2)
  [0x1D300, 0x1D35F, "un-noto-sans-symbols2"], // 1D300-1D35F-tai-xuan-jing-symbols (Noto Sans Symbols2)
  [0x1D360, 0x1D37F, "un-noto-sans-symbols2"], // 1D360-1D37F-counting-rod-numerals (Noto Sans Symbols2)
  [0x1D400, 0x1D7FF, "un-noto-sans-math"], // 1D400-1D7FF-mathematical-alphanumeric-symbols.0 (Noto Sans Math)
  [0x1D800, 0x1DAAF, "un-noto-sans-signwrit"], // 1D800-1DAAF-sutton-signwriting.0 (Noto Sans SignWrit)
  [0x1DF00, 0x1DFFF, "un-noto-sans"], // 1DF00-1DFFF-latin-extended-g (Noto Sans)
  [0x1E000, 0x1E02F, "un-noto-sans-glagolitic"], // 1E000-1E02F-glagolitic-supplement (Noto Sans Glagolitic)
  [0x1E030, 0x1E08F, "un-noto-sans"], // 1E030-1E08F-cyrillic-extended-d (Noto Sans)
  [0x1E100, 0x1E14F, "un-noto-serif-hmong-nyiakeng"], // 1E100-1E14F-nyiakeng-puachue-hmong (Noto Serif Hmong Nyiakeng)
  [0x1E290, 0x1E2BF, "un-noto-sans"], // 1E290-1E2BF-toto (Noto Sans)
  [0x1E2C0, 0x1E2FF, "un-noto-sans-wancho"], // 1E2C0-1E2FF-wancho (Noto Sans Wancho)
  [0x1E4D0, 0x1E4FF, "un-noto-sans"], // 1E4D0-1E4FF-nag-mundari (Noto Sans)
  [0x1E5D0, 0x1E5FF, "un-noto-sans"], // 1E5D0-1E5FF-ol-onal (Noto Sans)
  [0x1E7E0, 0x1E7FF, "un-noto-sans"], // 1E7E0-1E7FF-ethiopic-extended-b (Noto Sans)
  [0x1E800, 0x1E8DF, "un-noto-sans-mende-kikakui"], // 1E800-1E8DF-mende-kikakui (Noto Sans Mende Kikakui)
  [0x1E900, 0x1E95F, "un-noto-sans-adlam"], // 1E900-1E95F-adlam (Noto Sans Adlam)
  [0x1EC70, 0x1ECBF, "un-noto-sans-indic-siyaq-numbers"], // 1EC70-1ECBF-indic-siyaq-numbers (Noto Sans Indic Siyaq Numbers)
  [0x1ED00, 0x1ED4F, "un-noto-sans"], // 1ED00-1ED4F-ottoman-siyaq-numbers (Noto Sans)
  [0x1EE00, 0x1EEFF, "un-noto-sans-math"], // 1EE00-1EEFF-arabic-mathematical-alphabetic-symbols (Noto Sans Math)
  [0x1F000, 0x1F02F, "un-noto-sans-symbols2"], // 1F000-1F02F-mahjong-tiles (Noto Sans Symbols2)
  [0x1F030, 0x1F09F, "un-noto-sans-symbols2"], // 1F030-1F09F-domino-tiles (Noto Sans Symbols2)
  [0x1F0A0, 0x1F0FF, "un-noto-sans-symbols2"], // 1F0A0-1F0FF-playing-cards (Noto Sans Symbols2)
  [0x1F100, 0x1F1FF, "un-noto-sans-cjk-jp"], // 1F100-1F1FF-enclosed-alphanumeric-supplement (Noto Sans CJK JP)
  [0x1F200, 0x1F2FF, "un-noto-sans-cjk-jp"], // 1F200-1F2FF-enclosed-ideographic-supplement (Noto Sans CJK JP)
  [0x1F650, 0x1F67F, "un-noto-sans-symbols2"], // 1F650-1F67F-ornamental-dingbats (Noto Sans Symbols2)
  [0x1F700, 0x1F77F, "un-noto-sans-symbols"], // 1F700-1F77F-alchemical-symbols (Noto Sans Symbols)
  [0x1F780, 0x1F7FF, "un-noto-sans-symbols2"], // 1F780-1F7FF-geometric-shapes-extended (Noto Sans Symbols2)
  [0x1F800, 0x1F8FF, "un-noto-sans-symbols2"], // 1F800-1F8FF-supplemental-arrows-c (Noto Sans Symbols2)
  [0x1F900, 0x1F9FF, "un-noto-sans"], // 1F900-1F9FF-supplemental-symbols-and-pictographs (Noto Sans)
  [0x1FA00, 0x1FA6F, "un-noto-sans-symbols2"], // 1FA00-1FA6F-chess-symbols (Noto Sans Symbols2)
  [0x1FB00, 0x1FBFF, "un-noto-sans-symbols2"], // 1FB00-1FBFF-symbols-for-legacy-computing (Noto Sans Symbols2)
  [0x20000, 0x2A6DF, "un-noto-sans"], // 20000-2A6DF-cjk-unified-ideographs-extension-b.0 (Noto Sans)
  [0x2A700, 0x2B73F, "un-noto-sans"], // 2A700-2B73F-cjk-unified-ideographs-extension-c.0 (Noto Sans)
  [0x2B740, 0x2B81F, "un-noto-sans"], // 2B740-2B81F-cjk-unified-ideographs-extension-d (Noto Sans)
  [0x2B820, 0x2CEAF, "un-noto-sans"], // 2B820-2CEAF-cjk-unified-ideographs-extension-e.0 (Noto Sans)
  [0x2CEB0, 0x2EBEF, "un-noto-sans"], // 2CEB0-2EBEF-cjk-unified-ideographs-extension-f.0 (Noto Sans)
  [0x2EBF0, 0x2EE5F, "un-noto-sans"], // 2EBF0-2EE5F-cjk-unified-ideographs-extension-i.0 (Noto Sans)
  [0x2F800, 0x2FA1F, "un-noto-sans"], // 2F800-2FA1F-cjk-compatibility-ideographs-supplement.0 (Noto Sans)
  [0x30000, 0x3134F, "un-noto-sans"], // 30000-3134F-cjk-unified-ideographs-extension-g.0 (Noto Sans)
  [0x31350, 0x323AF, "un-noto-sans"], // 31350-323AF-cjk-unified-ideographs-extension-h.0 (Noto Sans)
  [0xE0100, 0xE01EF, "un-noto-sans"], // E0100-E01EF-variation-selectors-supplement (Noto Sans)
];
