export { captureElementTree, captureElementTreeWithWarnings, elementTreeToSvg, wrapSvg, rootSvgColorSchemeAttr, transparentRootBgRect, getLastCaptureWarnings, logCaptureWarnings, embedRemoteImages, embedResizedDataUri } from "./dom-to-svg.js";
export { resizeEmbeddedImages } from "./resize-embedded-images.js";
export type { ResizeEmbeddedImagesOptions } from "./resize-embedded-images.js";
export type { CapturedElement, CaptureWarning } from "./dom-to-svg.js";
export { generateAnimatedSvg } from "./animator.js";
export type { AnimationConfig, AnimationFrame, Overlay, TypingOverlay, TapOverlay, SvgOverlay, IntraFrameAnimation } from "./animator.js";
export type { CursorOverlay, CursorEvent, CursorMoveEvent, CursorClickEvent, CursorShowEvent, CursorHideEvent, CursorStyle, SelectorResolver } from "./cursor-overlay.js";
export { DemoRecorder, launchChromium } from "./capture.js";
export type { CaptureOptions } from "./capture.js";
export { optimizeSvg, gzipSvg } from "./optimize.js";
export { cullFrame } from "./viewbox-culling.js";
export { getGlyphDefs, clearGlyphDefs, registerWebfont, clearWebfonts } from "./text-to-path.js";
export { discoverAndRegisterWebfonts, attachWebfontTracker } from "./capture.js";
